.github/workflows/diff.yaml
Update workflow to enable forked PR to execute on CI
=> [master < T0729] Update workflow

.github/workflows/package_all.yaml, environment/os/debian-11.sh, release/package/debian-11/Dockerfile, release/package/docker-compose.yml, release/package/run.sh
=> [master < T0696-MG] Add support for Debian 11

README.md, environment/README.md, release/README.md
=> Add internals pages link

.clang-tidy, src/query/procedure/module.cpp, src/utils/license.cpp
=> [master < T0758-MG] Turn off concurent-mt in clang-tidy

include/mg_procedure.h, include/mgp.py, src/integrations/kafka/consumer.cpp, src/integrations/kafka/consumer.hpp, src/query/procedure/mg_procedure_impl.cpp, src/query/procedure/mg_procedure_impl.hpp, src/query/procedure/module.cpp, src/query/procedure/module.hpp, src/query/procedure/py_module.cpp, src/query/streams.cpp, src/query/streams.hpp, tests/e2e/streams/streams_tests.py, tests/e2e/streams/transformations/transform.py, tests/unit/mgp_kafka_c_api.cpp
=> [master  <  T0740-MG] Add procedure for setting a kafka stream offset 

src/utils/csv_parsing.cpp, src/utils/logging.hpp
=> [master < T0760-MG] Add more information to the MG_ASSERT in release mode

src/integrations/kafka/consumer.cpp
=> [master < T0360-MG] Fix check stream not reseting back to the correct offset

src/memgraph.cpp, src/query/common.hpp, src/query/config.hpp, src/query/exceptions.hpp, src/query/plan/operator.cpp, src/query/stream/streams.cpp
=> [master < T0759-MG] Retry transaction on consumer

licenses/BSL.txt
=> Update license date

.github/workflows/package_all.yaml, release/docker/memgraph.dockerfile, release/package/run.sh
=> Update debian base image

src/CMakeLists.txt, src/communication/CMakeLists.txt, src/communication/websocket/listener.cpp, src/communication/websocket/listener.hpp, src/communication/websocket/server.cpp, src/communication/websocket/server.hpp, src/communication/websocket/session.cpp, src/communication/websocket/session.hpp, src/memgraph.cpp
=> [E0108-MG < T0780-MG] Add websocket server and log stream

src/query/procedure/py_module.cpp
=> [master < MG] Increase reference count when returning Py_None

src/integrations/kafka/consumer.cpp
=> Use correct error in log message

.githooks/pre-commit, tools/header-checker.py
=> Adapt header-checker

src/auth/CMakeLists.txt, src/auth/models.cpp, src/auth/models.hpp, src/communication/CMakeLists.txt, src/communication/websocket/auth.cpp, src/communication/websocket/auth.hpp, src/communication/websocket/listener.cpp, src/communication/websocket/listener.hpp, src/communication/websocket/server.cpp, src/communication/websocket/server.hpp, src/communication/websocket/session.cpp, src/communication/websocket/session.hpp, src/glue/auth.cpp, src/memgraph.cpp, src/query/frontend/ast/ast.lcp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/frontend/opencypher/grammar/MemgraphCypher.g4, src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4, src/query/frontend/stripped_lexer_constants.hpp, tests/unit/cypher_main_visitor.cpp
=> [E108-MG < T0783-MG] Add websocket authentication

src/communication/websocket/session.cpp
=> [E108 < T0801-MG] Fix authorization check

src/communication/websocket/auth.hpp, src/communication/websocket/listener.cpp, src/communication/websocket/listener.hpp, src/communication/websocket/server.cpp, src/communication/websocket/server.hpp, src/communication/websocket/session.cpp, src/communication/websocket/session.hpp, src/memgraph.cpp, tests/unit/CMakeLists.txt, tests/unit/websocket.cpp
=> [E108-MG < T0787-MG] Websocket tests

environment/os/centos-7.sh
=> [master < T0825] Fix centos 7 release process

CMakeLists.txt, src/communication/context.cpp, src/communication/v2/listener.hpp, src/communication/v2/pool.hpp, src/communication/v2/server.hpp, src/communication/v2/session.hpp, src/communication/websocket/listener.hpp, src/communication/websocket/server.hpp, src/communication/websocket/session.hpp, src/memgraph.cpp
=> [E-109-MG < T0785-MG] Use asio socket

licenses/BSL.txt
=> [master < T0838-MG] Update license year

src/query/procedure/module.cpp, tests/e2e/CMakeLists.txt, tests/e2e/magic_functions/CMakeLists.txt, tests/e2e/streams/kafka_streams_tests.py, tests/e2e/streams/transformations/CMakeLists.txt, tests/e2e/streams/transformations/c_transformations.cpp
=> [master < T0840-MG] fix shared module loading

.githooks/pre-commit, .pre-commit-config.yaml, init
This PR introduces new commit hooks:
- `black` formatter for python files,
- Trailing space check,
- Newline check.
and it updates how we run the `clang-format` hook with the automated pre-commit repository.
=> [master < T0847-MG] Update precommit hooks

include/mg_procedure.h, include/mgp.py
=> [master < MG] Improve magic functions docs

.clang-tidy, src/mg_import_csv.cpp, src/query/db_accessor.hpp, src/query/dump.cpp, src/query/interpret/eval.hpp, src/query/plan/operator.cpp, src/query/procedure/module.cpp, src/query/procedure/module.hpp, src/query/typed_value.cpp, src/query/typed_value.hpp, src/slk/serialization.hpp, src/storage/v2/durability/serialization.cpp, src/storage/v2/durability/serialization.hpp, src/storage/v2/name_id_mapper.hpp, src/storage/v2/replication/serialization.cpp, src/storage/v2/replication/serialization.hpp, src/storage/v2/storage.cpp, src/storage/v2/storage.hpp, src/utils/file.cpp, src/utils/file.hpp, src/utils/fnv.hpp, src/utils/string.hpp, tests/unit/cypher_main_visitor.cpp
=> [master < T0656-MG] Remove ref from std::string_view

src/query/interpreter.cpp, src/query/interpreter.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/replication/replication_server.cpp, src/storage/v2/replication/replication_server.hpp, src/storage/v2/replication/rpc.lcp, src/storage/v2/storage.cpp, src/storage/v2/storage.hpp, tests/e2e/memgraph.py, tests/e2e/replication/show.py, tests/e2e/replication/show_while_creating_invalid_state.py, tests/e2e/replication/workloads.yaml
Documentation [PR](https://github.com/memgraph/docs/pull/439)
=> [master < T0880-MG] Add information on show replicas to express how uptodate is replica

.github/workflows/diff.yaml, tests/e2e/replication/show.py
Github workflow, no external documentation needed.
=> [master < T0892] Adding concurrency to cancel current workflow if one commits on the same branch.

.github/workflows/package_all.yaml, .github/workflows/release_docker.yaml
This PR introduces one fix and one update to the release process:
- Fix arm destination directory
- Update the docker release action that checks that we do not override the already existing version on DockerHub.
Examples of two successfully runs:
- Package all: https://github.com/memgraph/memgraph/actions/runs/2574414247
- Publish Docker image: https://github.com/memgraph/memgraph/actions/runs/2575111539
=> [master < T0888-MG] Update docker release process

src/query/frontend/ast/ast.lcp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/frontend/opencypher/grammar/MemgraphCypher.g4, src/query/interpreter.cpp, src/query/interpreter.hpp, src/storage/v2/replication/config.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/storage.cpp, src/storage/v2/storage.hpp, tests/e2e/interactive_mg_runner.py, tests/e2e/replication/show.py, tests/e2e/replication/show_while_creating_invalid_state.py, tests/e2e/replication/workloads.yaml, tests/jepsen/resources/node-config.edn, tests/jepsen/run.sh, tests/jepsen/src/jepsen/memgraph/client.clj, tests/jepsen/src/jepsen/memgraph/core.clj, tests/unit/cypher_main_visitor.cpp, tests/unit/storage_v2_replication.cpp
Doc [PR](https://github.com/memgraph/docs/pull/457)
=> [master < T0890-MG] Remove sync with timeout

.github/pull_request_template.md
```
Extend the PR template with the git message guide
```
=> [master < task] Extend the PR template

.github/workflows/diff.yaml
Commit message:
Update clang tidy job to only check the diff against the base branch.
=> [master < T0991-MG] Update clang-tidy job

src/query/v2/plan/operator_distributed.cpp, src/query/v2/plan/operator_distributed.lcp, tests/unit/query_v2_query_plan_common.hpp, tests/unit/query_v2_query_plan_hard_coded_queries.cpp
=> T0908 mg hard coded queries limit orderby distinc edgeuniqunessfilter

src/query/v2/requests.hpp
=> [project-pineapples < T1026-MG] Add shard requests responses

src/communication/bolt/v1/value.hpp, src/glue/communication.cpp, src/glue/communication.hpp, src/query/CMakeLists.txt, src/query/common.cpp, src/query/db_accessor.cpp, src/query/db_accessor.hpp, src/query/frontend/ast/ast.lcp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/graph.cpp, src/query/graph.hpp, src/query/interpret/awesome_memgraph_functions.cpp, src/query/interpret/eval.hpp, src/query/path.hpp, src/query/plan/operator.cpp, src/query/procedure/mg_procedure_impl.cpp, src/query/procedure/mg_procedure_impl.hpp, src/query/procedure/module.hpp, src/query/typed_value.cpp, src/query/typed_value.hpp, tests/e2e/write_procedures/CMakeLists.txt, tests/e2e/write_procedures/procedures/read.py, tests/e2e/write_procedures/procedures/write.py, tests/e2e/write_procedures/read_subgraph.py, tests/e2e/write_procedures/workloads.yaml, tests/gql_behave/tests/memgraph_V1/features/aggregations.feature, tests/unit/formatters.hpp, tests/unit/query_procedures_mgp_graph.cpp
=> [E130-MG < T1011-MG] Graph project feature implementation

src/glue/communication.cpp, src/glue/communication.hpp, src/query/CMakeLists.txt, src/query/common.cpp, src/query/db_accessor.cpp, src/query/db_accessor.hpp, src/query/frontend/ast/ast.lcp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/graph.cpp, src/query/graph.hpp, src/query/interpret/awesome_memgraph_functions.cpp, src/query/interpret/eval.hpp, src/query/path.hpp, src/query/plan/operator.cpp, src/query/procedure/mg_procedure_impl.cpp, src/query/procedure/mg_procedure_impl.hpp, src/query/typed_value.cpp, src/query/typed_value.hpp, tests/e2e/write_procedures/CMakeLists.txt, tests/e2e/write_procedures/procedures/read.py, tests/e2e/write_procedures/procedures/write.py, tests/e2e/write_procedures/read_subgraph.py, tests/e2e/write_procedures/workloads.yaml, tests/gql_behave/tests/memgraph_V1/features/aggregations.feature, tests/unit/formatters.hpp, tests/unit/query_procedures_mgp_graph.cpp
=> [master < E130-MG] Graph project feature implementation (#508)

src/communication/bolt/v1/session.hpp, src/communication/bolt/v1/states/init.hpp, src/memgraph.cpp, tests/e2e/telemetry/README.md, tests/e2e/telemetry/get-run_id.js, tests/e2e/telemetry/package.json, tests/unit/bolt_session.cpp
=> [E157-MG < T1036-MG] Switch to query summary, remove from bolt init

licenses/BSL.txt
__Commit message:__
- Update license date
=> [master < MG-license] Update license date

environment/os/debian-11-arm.sh, environment/util.sh, init, release/package/run.sh
__Commit message:__
- Fix centos 7 python virtualenv
- Fix the ubuntu git repository
- Fix architecture check for arm
=> [master < MG-release] Update release process

src/query/procedure/mg_procedure_impl.cpp
=> [master < T1076-MG] Bug fix for EdgeType and Label getters in pymodule

src/query/procedure/mg_procedure_impl.cpp
=> [master < T1107-MG] Bug fix for in-edges iterator

src/storage/v3/bindings/db_accessor.hpp, src/storage/v3/key_store.hpp, src/storage/v3/schema_validator.cpp, src/storage/v3/schema_validator.hpp, src/storage/v3/shard.cpp, src/storage/v3/shard.hpp, src/storage/v3/shard_rsm.cpp, src/storage/v3/value_conversions.hpp, src/storage/v3/vertex_accessor.cpp, tests/simulation/shard_rsm.cpp, tests/unit/storage_v3.cpp, tests/unit/storage_v3_edge.cpp, tests/unit/storage_v3_expr.cpp, tests/unit/storage_v3_indices.cpp, tests/unit/storage_v3_isolation_level.cpp, tests/unit/storage_v3_schema.cpp, tests/unit/storage_v3_vertex_accessors.cpp
Final commit message:
```
Fixed various TODOs that were easy to fix to improve the code quality of the
newly implemented storage.
```
=> [:pineapple: < MG] Fix some storage TODOs

licenses/BSL.txt, licenses/MEL.txt
=> [master < T1156-MG] Update license for release 2.4.2

.github/workflows/daily_benchmark.yaml, .github/workflows/diff.yaml, .github/workflows/full_clang_tidy.yaml, .github/workflows/package_all.yaml, .github/workflows/release_centos8.yaml, .github/workflows/release_debian10.yaml, .github/workflows/release_docker.yaml, .github/workflows/release_ubuntu2004.yaml, .pre-commit-config.yaml, init, pyproject.toml
=> [:pineapple: < MG-add-python-checks] Add python checks

src/glue/v2/communication.cpp, src/glue/v2/communication.hpp, src/memgraph.cpp, src/query/v2/accessors.cpp, src/query/v2/accessors.hpp, src/query/v2/bindings/eval.hpp, src/query/v2/context.hpp, src/query/v2/conversions.hpp, src/query/v2/cypher_query_interpreter.cpp, src/query/v2/cypher_query_interpreter.hpp, src/query/v2/interpret/awesome_memgraph_functions.hpp, src/query/v2/interpreter.cpp, src/query/v2/interpreter.hpp, src/query/v2/plan/operator.cpp, src/query/v2/plan/pretty_print.cpp, src/query/v2/plan/pretty_print.hpp, src/query/v2/plan/vertex_count_cache.hpp, src/query/v2/shard_request_manager.hpp, tests/simulation/shard_request_manager.cpp, tests/simulation/test_cluster.hpp, tests/unit/high_density_shard_create_scan.cpp, tests/unit/machine_manager.cpp
=> Change the namespace of ShardRequestManager to query::v2 instead of msgs

README.md
Updated the lead paragraph of the description and added a link to Benchgraph.
=>  [master < T1006-DX-update-readme] Update README with one new paragraph and link

tests/mgbench/README.md
[master < DX] PR
- This is just a small updated to methodology links and content. 
- Only markdown file has been changed.
=> [master < DX] Update methodology links and polish content

libs/setup.sh
=> [master < MG-update-mgconsole] Raise mgconsole version

src/query/frontend/ast/ast.lcp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/plan/operator.cpp, src/query/plan/operator.lcp, src/query/plan/pretty_print.cpp, src/query/plan/rule_based_planner.cpp, tests/mgbench/datasets.py, tests/unit/plan_pretty_print.cpp, tests/unit/query_common.hpp, tests/unit/query_expression_evaluator.cpp, tests/unit/query_plan.cpp, tests/unit/query_plan_accumulate_aggregate.cpp, tests/unit/query_plan_checker.hpp, tests/unit/query_semantic.cpp
* Expanded current Aggregation to work with DISTINCT
=> [master < E202-MG] Add aggregation distinct (#654)

src/expr/interpret/eval.hpp, src/expr/interpret/frame.hpp, src/query/v2/bindings/frame.hpp, src/query/v2/interpreter.cpp, src/storage/v3/bindings/frame.hpp
```
Removing the template part of Frame
```
=> [:pineapple: < T1163-MG]  remove template from frame

include/_mgp.hpp, include/mgp.hpp, query_modules/example.cpp, tests/unit/cpp_api.cpp
=> Fix MAGE C++ API bugs

README.md
I've added community info into readme
=> [master<051222]Add information about community to readme

src/query/db_accessor.cpp, src/query/db_accessor.hpp
=> [master < T474-FL] Fixed graph projection bug

src/query/interpreter.cpp, src/query/plan/operator.cpp, src/utils/csv_parsing.cpp, src/utils/memory.cpp, src/utils/memory.hpp, tests/unit/utils_memory.cpp
Fix LOAD CSV bug for large memory usage
https://github.com/memgraph/memgraph/issues/684
=> [master<T1215-MG] Fix LOAD CSV large memory usage

include/mgp.py
Minor type hint BUG, also present in the documentation, reported by a community member. 
This PR fixes issue #692.
=> [master < DX-T1012 ]Fix create edge type hint and comment.

release/mgp/.gitignore, release/mgp/pyproject.toml
`mgp 1.1.1` release:
- Changed version
- Added fixes: https://github.com/memgraph/memgraph/pull/724
- Added `poetry.lock` to `.gitignore`
=> [master < T1029-DX] Release mgp 1.1.1

libs/setup.sh, tests/unit/bfs_fine_grained.cpp, tests/unit/bfs_single_node.cpp, tests/unit/cypher_main_visitor.cpp, tests/unit/query_plan.cpp, tests/unit/storage_v2_durability.cpp, tests/unit/storage_v2_edge.cpp, tests/unit/storage_v2_isolation_level.cpp, tests/unit/storage_v2_replication.cpp, tests/unit/storage_v2_wal_file.cpp, tests/unit/utils_csv_parsing.cpp, tests/unit/utils_file_locker.cpp, tests/unit/utils_settings.cpp
[master < Task] PR - **NOT NECESSARY**
=> [master < MG] Update googletest to version 1.12.1

licenses/BSL.txt
=> [master < MG] Update license year

.github/workflows/diff.yaml, .pre-commit-config.yaml, init
=> [master < MG] Exclude license dir from CI trigger

src/query/v2/interpreter.cpp, src/query/v2/multiframe.cpp, src/query/v2/plan/operator.cpp, src/query/v2/plan/operator.lcp, src/storage/v3/request_helper.cpp, tests/unit/mock_helpers.hpp
=> [:pineapple:  < T1223-MG] Make access control benchmark run with `MultiFrame`

src/query/procedure/module.cpp
- docs-changelog-message: Disable removing `torch` and `igraph` from `sys.modules` cache because of the issue occuring when reloading.
Connected issue on the PyTorch: https://github.com/pytorch/pytorch/issues/91039
=> [master < T534-FL-torch-mg-load-fix] torch and igraph removing from sys cache

src/query/v2/plan/operator.cpp
=> [:pineapple: <  T1229-MG] Add implementation of `UNWIND` with `MultiFrame`

src/query/v2/interpreter.cpp, src/query/v2/plan/operator.cpp
=> [:pineapple:  < T1126-MG] Implement ScanByPrimaryKey with multiframe

src/query/v2/interpreter.cpp, src/query/v2/plan/operator.cpp, src/query/v2/plan/operator.lcp
=> [:pineapple:  < T1235-MG] Implement edge uniqueness filter with pull multiple

.github/pull_request_template.md
=> [master < T576-FL] Update pull request template

src/query/v2/interpreter.cpp, src/query/v2/multiframe.cpp, src/query/v2/multiframe.hpp, src/query/v2/plan/operator.cpp, src/query/v2/plan/rewrite/index_lookup.hpp, src/query/v2/request_router.hpp, tests/mgbench/compare_results.py, tests/mgbench/dataset_creator_unwind.py, tests/mgbench/datasets.py, tests/mgbench/runners.py, tests/mgbench/splitfiles/accesscontrol_large.shard_configuration, tests/mgbench/splitfiles/accesscontrol_medium.shard_configuration, tests/mgbench/splitfiles/accesscontrol_small.shard_configuration, tests/unit/mock_helpers.hpp, tests/unit/query_v2_create_node_multiframe.cpp, tests/unit/query_v2_expression_evaluator.cpp
=> [🍍 < MG] Fix mgbench access control benchmark

README.md
=> [master < add-fedora-badge] Add fedora badge to README.md

README.md
=> [master < add-redhat-badge] Add RedHat badge to README.md

README.md
=> [master < add-lima-badge] Add Lima badge

.github/workflows/package_all.yaml, environment/os/ubuntu-22.04-arm.sh, environment/toolchain/v4.sh, environment/util.sh, release/package/arm-builders.yml, release/package/run.sh, release/package/ubuntu-22.04-arm/Dockerfile
Necessary changes to support ubuntu 22.04 arm
=> [master < MG-ubuntu-22.04] Support ubuntu 22.04 arm

src/storage/v2/replication/replication_client.cpp
[master < 230214] Update incompatible epoch_id error 
I did nothing as it's just a text change.
Closes https://github.com/memgraph/memgraph/issues/782
=> [master < ] Update incompatible epoch_id error

.pre-commit-config.yaml, CMakeLists.txt
=> #557: Add CPU architecture detection to CMake

src/expr/interpret/eval.hpp, src/expr/interpret/frame.hpp, src/query/v2/plan/operator.cpp, src/query/v2/plan/operator.lcp, tests/unit/query_v2_create_expand_multiframe.cpp
=> [🍍 < ] Add id to Frame

src/query/interpreter.cpp, src/query/interpreter.hpp
=> [master < T620-FL] Fix max block size bug

tests/mgbench/README.md
- Update the methodology README file.
=> [master < ] Update benchgraph methodology 

tests/mgbench/README.md
Update metodology links to proper branches.
=> [Master < ] Fix metodology links

src/query/procedure/py_module.cpp
I PR for batched procedures I was not handling errors properly from init of procedures. Errors can occur, for example on this [PR ](https://github.com/memgraph/mage/pull/209/) on MAGE errors occur on initialization if the file doesn't exist. I forgot to take that into account.
=> Add error handling on py batched proc init

src/auth/models.cpp
If database field is not present in the auth user then default to memgraph access
=> [E952 <] Default to memgraph for pre multi-db user

src/query/exceptions.hpp, src/query/interpreter.cpp
=> [master<] Proposed exceptions and warnings for on-disk mode

tests/unit/transaction_queue_multiple.cpp
=> [master < T1077] Fix flaky tx-queue-multiple test

tests/e2e/transaction_queue/test_transaction_queue.py
NOTE: No need for docs update because this is an internal test improvement.
=> [master < T1102] Fix flaky e2e tx queue test

tests/jepsen/src/jepsen/memgraph/support.clj
- remove extra arguments from start-node and stop-node functions
=> [master < T1091] Remove node argument from start-stop functions

src/storage/v2/disk/label_property_index.hpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/durability.hpp, src/storage/v2/inmemory/indices_utils.hpp, src/storage/v2/inmemory/label_index.cpp, src/storage/v2/inmemory/label_index.hpp, src/storage/v2/inmemory/label_property_index.cpp, src/storage/v2/inmemory/label_property_index.hpp
=> [master] < [Mg fix sequential label property index recovery]

src/storage/v2/disk/label_index.cpp, src/storage/v2/disk/label_property_index.cpp, src/storage/v2/disk/storage.cpp, src/storage/v2/disk/storage.hpp, src/storage/v2/disk/unique_constraints.cpp, tests/unit/storage_v2_indices.cpp
=> [master < T1139] Improve disk indices

src/storage/v2/disk/rocksdb_storage.cpp, src/storage/v2/disk/rocksdb_storage.hpp, src/storage/v2/disk/storage.cpp, src/storage/v2/disk/storage.hpp, src/utils/rocksdb_serialization.hpp, tests/e2e/triggers/workloads.yaml
=> [master < T1145] Filter deleted edges during edge prefetch

src/storage/v2/disk/storage.cpp, src/storage/v2/disk/storage.hpp, src/utils/rocksdb_serialization.hpp
=> [master < T1132] Optimize import of edges on disk

src/storage/v2/inmemory/indices_utils.hpp, src/storage/v2/vertex_accessor.cpp, src/storage/v2/vertex_info_cache.cpp, src/storage/v2/vertex_info_cache.hpp, tests/e2e/configuration/default_config.py
=> [master <] Fix typo threashold -> threshold

src/kvstore/kvstore.cpp, src/kvstore/kvstore.hpp, src/storage/v2/disk/storage.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/replication/replication_server.cpp, src/storage/v2/replication/replication_server.hpp, src/storage/v2/storage.hpp, tests/unit/storage_v2_replication.cpp
Trying to extract replication logic to a higher level.
First iteration just moves the logic into a struct under InMemory and adds the necessary API.
=> [master <] Decoupling replication logic from InMemoryStorage

tests/gql_behave/requirements.txt, tests/gql_behave/steps/test_parameters.py, tests/integration/ldap/requirements.txt, tests/setup.sh
This PR aims to solve PyYAML installation issues that may come up when one runs the `init` script.
> Upgrade PyYAML version to 6.0.1
=> [master < T1174] Bump PyYAML version

tests/unit/storage_v2_durability_inmemory.cpp
Fixed the wait period, this should ensure at least one snapshot was made. Also cleaned up the checking around this. And also better corruption.
=> [master <] Reduce flake SnapshotFallback test

src/storage/v2/indices/indices_utils.hpp, src/storage/v2/inmemory/unique_constraints.cpp, src/storage/v2/property_store.cpp
Improve AnyVersionHasLabelProperty by doing less work in certain cases.
Improve FindSpecificProperty.
=> [master <] Optimise RemoveObsoleteEntries

.github/workflows/performance_benchmarks.yaml
Add manual performance benchmark execution.
=> Add manual performance benchmark execution

config/flags.yaml, src/dbms/database.cpp, src/flags/CMakeLists.txt, src/flags/storage_mode.cpp, src/flags/storage_mode.hpp, src/memgraph.cpp, src/storage/v2/config.hpp, src/storage/v2/disk/rocksdb_storage.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, tests/e2e/configuration/default_config.py
=> Add storage mode flag

src/query/interpreter.cpp, src/storage/v2/disk/storage.hpp, src/storage/v2/inmemory/replication/replication_client.cpp, src/storage/v2/inmemory/replication/replication_client.hpp, src/storage/v2/inmemory/replication/replication_server.cpp, src/storage/v2/inmemory/replication/replication_server.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/replication/config.hpp, src/storage/v2/replication/replication.cpp, src/storage/v2/replication/replication.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/replication/replication_server.cpp, src/storage/v2/replication/replication_server.hpp, src/storage/v2/storage.hpp, tests/unit/storage_v2_replication.cpp
=> Refactor replication client/server for easier construction

README.md
I've [uploaded a new image](https://public-assets.memgraph.com/github-readme-images/github-memgraph-repo-banner.png) and I've updated the path for the new banner that goes on the top of the README.
=> [master < update-logo-readme] Update banner in README

src/query/plan/hint_provider.hpp, tests/gql_behave/.gitignore, tests/gql_behave/continuous_integration
Due to Hash Join, the other PR introduced a visitor which needed to have all the operators implemented in it.
=> Fix gql behave dropping connection on Memgraph

CMakeLists.txt
Revert the changes to CMakeLists commited in this PR https://github.com/memgraph/memgraph/pull/1418
=> Revert CMakeLists

.github/workflows/release_centos8.yaml, .github/workflows/release_debian10.yaml, .github/workflows/release_ubuntu2004.yaml
=> Fix GQL release worklflows

.github/workflows/daily_benchmark.yaml, .github/workflows/performance_benchmarks.yaml
=> Fix mgbench upload script call

src/query/plan/operator.cpp, tests/e2e/CMakeLists.txt, tests/e2e/inspect_query/CMakeLists.txt, tests/e2e/inspect_query/common.py, tests/e2e/inspect_query/inspect_query.py, tests/e2e/inspect_query/workloads.yaml
> Fix bug on profiling queries that contain the Filter operator
=> Fix PROFILE infinite loop

src/storage/v2/durability/durability.cpp
Parallel index loading was not performing in all the cases.
@vpavicic Changelog message: Allow parallel index loading on all paths of code.
=> Fix parallel index loading

src/query/plan/operator.cpp, src/query/plan/operator.hpp, tests/e2e/replication/show_while_creating_invalid_state.py, tests/gql_behave/tests/memgraph_V1/features/aggregations.feature, tests/gql_behave/tests/memgraph_V1_on_disk/features/aggregations.feature, tests/unit/query_plan_accumulate_aggregate.cpp
=> Fix empty aggregation returns null

.github/workflows/package_specific.yaml
=> Add workflow for packaging memgraph for specific target OS

.github/workflows/package_specific.yaml
=> Fix package specific workflow file

.github/workflows/package_specific.yaml
=> Fix error in package specific workflow upload-to-s3 job

CMakeLists.txt, licenses/BSL.txt
=> Prepare for 2.12.1 patch release

src/query/plan/operator.cpp, src/query/plan/operator.hpp, tests/gql_behave/tests/memgraph_V1/features/aggregations.feature, tests/gql_behave/tests/memgraph_V1_on_disk/features/aggregations.feature, tests/unit/query_plan_accumulate_aggregate.cpp
=> Aggregations return empty result when used with group by

src/memory/global_memory_control.cpp
=> Fix memory typo Alloc vs. Free

tests/e2e/garbage_collection/gc_periodic.py
Made GC Periodic test not flaky (also the logic was wrong before).
Changing jemalloc configs (ex. removing muzzy and dirty pages and some others) didn't help so the timer was just extended to 5 GC iterations with periodic checking to not take up time.
This test was reran 1000 times and never failed.
Most of the times it finished after 3 iterations and a couple of times after 4. 
=> Fix flaky GC test

src/license/license.cpp, src/license/license.hpp, src/memgraph.cpp
=> Bugfix: Shutdown blocks due to wrong execution order

licenses/BSL.txt
=> Prepare for 2.14 release

src/utils/skip_list.hpp, tests/e2e/interactive_mg_runner.py, tests/unit/skip_list.cpp
SkipList's iterators and find methods had some issues. 
Fixing them up so that they work as expected.
=> Fix skip list cpp

src/auth/auth.cpp, src/auth/auth.hpp, src/auth/models.cpp, src/flags/general.cpp, src/flags/general.hpp, src/glue/auth_global.hpp, src/glue/auth_handler.cpp, src/glue/auth_handler.hpp, src/memgraph.cpp, tests/integration/telemetry/client.cpp, tests/unit/auth.cpp, tests/unit/auth_handler.cpp, tests/unit/dbms_handler.cpp, tests/unit/dbms_handler_community.cpp, tests/unit/multi_tenancy.cpp, tests/unit/storage_v2_replication.cpp
Moved various flags under a single config. 
Moved regex logic under auth::Auth
=> Simplify auth::Auth

libs/CMakeLists.txt, libs/setup.sh, src/coordination/CMakeLists.txt, src/coordination/coordinator_data.cpp
Adds a NuRaft library into Memgraph codebase.
=> Add NuRaft library

src/coordination/coordinator_instance.cpp, src/coordination/include/coordination/register_main_replica_coordinator_status.hpp, src/query/interpreter.cpp, tests/e2e/high_availability_experimental/single_coordinator.py
=> Forbid multiple mains in cluster

src/dbms/database.hpp, src/dbms/dbms_handler.hpp, src/storage/v2/disk/storage.cpp, src/storage/v2/disk/storage.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/storage.hpp, tests/unit/database_get_info.cpp, tests/unit/storage_v2_get_info.cpp
=> Removed force dir in the GetInfo functions

environment/os/amzn-2.sh, environment/os/centos-7.sh
=> Add openssl to MEMGRAPH_BUILD_DEPS for amzn-2 and centos-7

src/coordination/raft_state.cpp, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/distributed_coords.py
nuRaft has a potential issue when adding a server to the cluster. The request may be accepted but not yet committed, so the next command when it wants to be executed will fail. 
This PR fixes behavior.
Check docs for more info: https://github.dev/eBay/NuRaft
=> Fix bug prone add server to cluster behavior

src/coordination/coordinator_cluster_state.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_log_store.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/nuraft/coordinator_state_machine.hpp, src/coordination/raft_state.cpp, src/query/interpreter.cpp, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/distributed_coords.py
Add distributed tests
Avoid multiple leaders in the cluster
=> Fix snapshot creation in RSM and forbid multiple leaders 

tests/e2e/high_availability/distributed_coords.py
=> Add test to verify log store works properly

src/query/plan/preprocess.cpp, src/query/plan/preprocess.hpp
=> Fix PatternVisitor compilation in toolchain-v5

.github/pull_request_template.md
=> Add new PR template

CMakeLists.txt
TSAN cannot be run together with Jemalloc due to some problems
- Jemalloc will be disabled when run together with TSAN
=> Forbid TSAN with Jemalloc

licenses/MEL.txt
We made a mistake in the MEL, 2 sections were not split/enumerated correctly.
=> Update MEL license

src/coordination/coordinator_cluster_state.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/instance_status.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/include/nuraft/coordinator_cluster_state.hpp, src/coordination/include/nuraft/coordinator_state_machine.hpp, src/coordination/raft_state.cpp, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/distributed_coords.py, tests/unit/coordinator_cluster_state.cpp, tests/unit/coordinator_instance.cpp, tests/unit/high_availability_cluster_setup.cpp, tests/unit/raft_state.cpp
Fix handling of coordinators in `CoordinatorClusterState`.
- **Fix coordinators in `CoordClusterState`**
=> Fix saving coordinators in CoordinatorClusterState

licenses/BSL.txt
Update BSL license change date for 2.15.1
=> Update BSL license change date for 2.15.1

.sonarcloud.properties
Please briefly explain the changes you made here.
- [FINAL GIT MESSAGE]
- **[FINAL GIT MESSAGE]**
=> Restore sonarcloud quality checks

src/storage/v2/inmemory/storage.cpp
Fix edge-type index garbage collection
=> Fix edge-type index garbage collection

README.md
I added a section Compile from Source and updated Features list.
=> Add link to compile from source

src/memgraph.cpp, src/storage/v2/inmemory/storage.cpp
Fixing unexpected behavior. 
Periodic snapshots were being created even in IN_MEMORY_ANALYTICAL mode.
- **Bugfix: Ran periodic snapshot in analytical mode**
- **Fixed periodic snapshots running in analytical mode**
- **NA**
=> Bugfix: Runing periodic snapshot even if in analytical mode

src/storage/v2/edge_accessor.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/storage.cpp, src/storage/v2/vertex_accessor.cpp, src/utils/atomic_memory_block.hpp
Minor changes to fix sonar scanner detected issues
=> Fixes issues identified by Sonar

README.md
This PR will update the `README` file after migrating to `mgbuild CI`.
=> Change build and test status badge target in README

.github/workflows/diff.yaml, .github/workflows/diff_jepsen.yaml, tests/jepsen/README.md, tests/jepsen/run.sh, tests/jepsen/src/jepsen/memgraph/bank.clj, tests/jepsen/src/jepsen/memgraph/client.clj, tests/jepsen/src/jepsen/memgraph/core.clj, tests/jepsen/src/jepsen/memgraph/haclient.clj, tests/jepsen/src/jepsen/memgraph/haempty.clj, tests/jepsen/src/jepsen/memgraph/hanemesis.clj, tests/jepsen/src/jepsen/memgraph/support.clj, tests/jepsen/src/jepsen/memgraph/utils.clj
Added HA Jepsen test. This test doesn't use any data, rather it justs tests cluster behavior from the operative point of view. Both data instances and coordinators get killed.
- **Add empty Jepsen HA test**
=> Add empty Jepsen HA test

src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state.cpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/coordinator_state.hpp, src/coordination/include/coordination/register_main_replica_coordinator_status.hpp, src/coordination/raft_state.cpp, src/dbms/coordinator_handler.cpp, src/dbms/coordinator_handler.hpp, src/query/interpreter.cpp, tests/e2e/high_availability/coord_cluster_registration.py
Throw in the query time explicitly when adding coordinator instance.
- **Check coordinator validity before adding it to cluster**
- **Adding coordinators will fail if coordinator with the same id, bolt endpoint or raft endpoint already exists**
=> Check coordinator validity before adding it to cluster

tests/util.sh
=> Refactor tests/util.sh

tests/jepsen/src/jepsen/memgraph/bank.clj, tests/jepsen/src/jepsen/memgraph/client.clj, tests/jepsen/src/jepsen/memgraph/core.clj, tests/jepsen/src/jepsen/memgraph/haempty.clj, tests/jepsen/src/jepsen/memgraph/large.clj
Avoid using macros from different namespace.
- **Refactor creating Clojure client**
=> Refactor creating Clojure client

libs/setup.sh
This PR fixes asio download from cache
- **[FINAL GIT MESSAGE]**
=> Fix asio download from cache

src/coordination/coordinator_instance.cpp, src/coordination/raft_state.cpp
Add a more verbose logging in coordinator to easier debug what is happening in each thread
- Add more verbose logging in coordinator
- Add more verbose logging in coordinator
=> Add more verbose logging in coordinator

tools/diff_setup.py
This PR fixes a logical bug in the `diff_setup.py` script.
Bug: couldn't run the action with manual workflow because every job was skipped regardless of the inputs.
=> Fix setup_diff_workflow

.github/workflows/package_memgraph.yaml, .github/workflows/reusable_package.yaml, release/package/mgbuild.sh, tools/diff_setup.py
Please briefly explain the changes you made here.
- [FINAL GIT MESSAGE]
- **[FINAL GIT MESSAGE]**
=> Add push to github input to package memgraph workflow

CMakeLists.txt, src/communication/bolt/v1/decoder/chunked_decoder_buffer.hpp, src/communication/websocket/auth.hpp, src/coordination/coordinator_instance.cpp, src/query/plan/operator.hpp, src/query/query_user.hpp, src/query/stream.hpp, src/storage/v2/inmemory/edge_type_index.cpp, src/storage/v2/inmemory/edge_type_index.hpp, src/utils/visitor.hpp
Add extra compile warning flags (as errors) and add a definition to catch potential bugs with libstdc++ usage.
- **Harden the build, more warnings/asserts**
=> Harden the build, more warnings/asserts

release/docker/package_docker, release/package/mgbuild.sh
This PR fixes the image tag for `RelWithDebInfo` docker images.
=> Fix image tag for RelWithDebInfo images

licenses/BSL.txt
This PR will update the BSL license change date for the v2.17.0 release
=> Update BSL license change date for v2.17.0

tests/jepsen/run.sh
We will try to clone Jepsen first from mgdeps-cache, if it fails then try from public repo.
- **Try to clone Jepsen optimistically from mgdeps-cache**
=> Try to clone Jepsen optimistically from mgdeps-cache

tests/jepsen/src/jepsen/memgraph/bank.clj, tests/jepsen/src/jepsen/memgraph/core.clj, tests/jepsen/src/jepsen/memgraph/habank.clj, tests/jepsen/src/jepsen/memgraph/large.clj, tests/jepsen/src/jepsen/memgraph/utils.clj
- Improved exception handling in the bank test.
- Added log parsing as part of the checker.
- Added custom exception handling process.
- Further removing duplication between bank and HA bank
- Managing `ServiceUnavailableException` in the large test
- **Improvements on Jepsen infra**
=> Jepsen improvements (vol.2)

tests/e2e/fine_grained_access/workloads.yaml
Removed disk tests:
1. Create delete filtering on disk
2. Path filtering on disk
3. EdgeType filtering on disk
- **Update e2e CI build**
=> Update e2e CI build

src/query/plan/preprocess.cpp
expressions like `MATCH (n:L), (n:L) RETURN n;` use to do the label filtering twice. Now the redundant check is removed. Effectively becoming `MATCH (n:L) RETURN n;`
Still issues with property filters being redundant, but this is harder to fix because of the extraction of constants as parameters (for cached plan reuse).
=> Deduplicate label filters

tests/e2e/high_availability/distributed_coords.py, tests/e2e/mg_utils.py
This diff fixes an issue where instance_1 or instance_2 in the test could be main, depending on the election
=> Fix test instance_1 or instance_2 main

.github/workflows/release_build_test.yaml
This PR modifies the release_build_test.yml workflow to include RelWithDebInfo builds.
=> Add RelWithDebInfo builds and refactor workflow

src/flags/auth.hpp
=> Fix wrong SSO default values

.github/workflows/diff_debug.yaml, tests/drivers/run_cluster.sh
Improvements on driver tests:
1. Logs are uploaded to GitHub
2. Instances are using TRACE log level
3. Removed query-execution-timeout flag and bolt-inactivity-session
=> Improve driver tests

src/coordination/coordinator_instance.cpp, tests/e2e/high_availability/distributed_coords.py
This diff fixes deadlock in force if all instances are down when an instance wants to be registered
=> Fix deadlock on force reset if all instances are down

src/storage/v2/indices/indices.cpp, src/storage/v2/indices/indices.hpp, src/storage/v2/inmemory/storage.cpp
Please briefly explain the changes you made here.
- [FINAL GIT MESSAGE]
- **[FINAL GIT MESSAGE]**
=> Fix index obsolete objects removal for edge type indices

.github/workflows/package_memgraph.yaml, .github/workflows/promote_rc_release.yml, .github/workflows/release_build_test.yaml, release/package/amd-builders-v4.yml, release/package/amd-builders-v5.yml, release/package/mgbuild.sh
Deprecate builds for amzn-2 and centos-7
=> Deprecate amzn-2 and centos-7

licenses/BSL.txt
Update BSL license change date
=> Update BSL license change date for v2.18.0

tests/jepsen/src/jepsen/memgraph/habank.clj
During `initialize-data` operation, when SYNC replica was down, `initialize-data` operation would fail with TransientException: At least one SYNC replica ... but since our SYNC replication would still continue to replicate to SYNC replica and data would still become durable on MAIN, failure was here a wrong option. The operation handles now this situation by returning ok.
=> Fix Jepsen HA bank test during initialize data

tests/drivers/csharp/v4_1/ParallelEdgeImport/Program.cs, tests/drivers/node/v4_1/parallel_edge_import.js, tests/drivers/python/v4_1/parallel_edge_import.py, tests/drivers/python/v5_8/parallel_edge_import.py, tests/drivers/run.sh, tests/drivers/run_v1.sh
Removed bolt-session-inactivity-timeout since it is not needed in theses tests. Query execution timeout value conflicted with values for specific drivers, also not needed, hence removed.
=> Add fixes for drivers

src/coordination/replication_instance_client.cpp, src/memgraph.cpp, tests/e2e/high_availability/coordinator.py, tests/e2e/memgraph.py
Setup queries from coordinator.py are moved to the interactive_mg_runner setup part. Improved log messages in replication_instance_client.
=> e2e improvements

src/coordination/CMakeLists.txt, src/coordination/coordination_observer.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/include/coordination/coordination_observer.hpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/coordinator_state.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/include/nuraft/coordinator_state_manager.hpp, src/coordination/raft_state.cpp, src/dbms/coordinator_handler.cpp, src/dbms/coordinator_handler.hpp, src/query/interpreter.cpp, src/query/interpreter.hpp, tests/e2e/high_availability/distributed_coords.py, tests/unit/coordinator_instance.cpp, tests/unit/coordinator_raft_state.cpp
This diff moves client creation on config change
=> Separate coordinator client creation from ShowInstances

tests/e2e/high_availability/distributed_coords.py
This diff fixes the issue that the `SHOW REPLICAS` query didn't cover, where `instance_2` becomes main instead of `instance_1`, as the leader coordinators starts pinging  instance_2 earlier than instance_1. Show instances query did have such case covered, but show replicas didn't.
=> Fix issue in flaky HA test for SHOW REPLICAS output

.github/workflows/check_flakiness.yaml
This PR introduces the foundation for developing a workflow for checking flakiness. 
The new workflow is run on workflow dispatch, so this PR needs to be merged as is to allow testing #2199
=> Initialize development of flakiness check workflow

tests/e2e/high_availability/distributed_coords.py
This diff fixes no leader found in test due to no wait period in between
=> Fix no leader found

.github/workflows/promote_rc_release.yml
This PR fixes syntax issues in `promote_rc_release.yaml` workflow file
=> Fix promote to release workflow

tests/drivers/run_cluster.sh
Improve the error handling of the HA driver tests
=> Improve the error handling of the HA driver tests

src/query/time_to_live/time_to_live.cpp
Added new trace messages with more information for TTL.
=> More detailed TTL trace logs

src/coordination/coordinator_instance.cpp, src/coordination/replication_instance_client.cpp
Add logs when promoting instance.
=> Log promotion

tests/unit/query_dump.cpp
Unit test for query dump for edge indices
=> Add query dump test for edge indices

tests/unit/utils_rwlock.cpp
Making timing as tight as possible.
We were getting:
```
/home/mg/memgraph/tests/unit/utils_rwlock.cpp:69: Failure
Expected: (total_time) <= (350ms), actual: 0.350814s vs 350ms
```
Hopefully this fixes the issue.
=> Small change to test, more robust

src/query/interpreter.cpp, src/storage/v2/durability/snapshot.cpp, tests/unit/storage_v2_durability_inmemory.cpp
Move type constraints from enterprise to community features.
=> Make type constraints community feature

licenses/BSL.txt
Git commit description, explain the changes you made here
---
__*Leave above in PR description, copy the below into a comment*__
___
- **[ Release note text ]**
=> Update BSL license change date for v2.20.0

licenses/BSL.txt
Update BSL license change date for 2.20.1
---
__*Leave above in PR description, copy the below into a comment*__
___
- **[ Release note text ]**
=> Update BSL license change date for 2.20.1

src/dbms/inmemory/replication_handlers.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/schema_info.hpp, src/utils/synchronized_metadata_store.hpp
Storage would not be completely cleaned when force resetting or applying snapshots.
=> Bugfix: replication only partially reset storage

src/communication/bolt/v1/states/handlers.hpp, src/glue/SessionHL.cpp, src/query/interpreter.cpp, src/query/interpreter.hpp, src/storage/v2/property_value.hpp, src/utils/logging.cpp, src/utils/logging.hpp, src/utils/string.hpp, tests/drivers/python/v5_8/memgraph_utils.py, tests/drivers/python/v5_8/metadata.py, tests/drivers/python/v5_8/run.sh, tests/unit/property_value_v2.cpp
Moved query logging out of communication into SessionHL 
Created a struct that handles query logging (avoids any work if logging disabled)
Updated MaskSensitiveInformation to use string_view
=> Add query metadata when logging incoming query

src/storage/v2/inmemory/storage.cpp
We were missing a case for tracking when deltas were actually released. This gave the appearance in `SHOW STORAGE INFO;` that we were not actually releasing them. 
Tracking is now correct.
=> Correct unreleased deltas counter

src/storage/v2/replication/replication_client.cpp
We are checking the last durable timestamp the end of the recovery process.
The check determines if the recovery was successful. 
Since the recovery process is async, we could be recovering while committing and updating the timestamp.
Now we lock the engine_lock_ when checking the timestamp and make sure the view is consistent.
=> Align recovery timestamp check with timestamp modifications

src/flags/experimental.cpp, src/flags/experimental.hpp, src/query/interpreter.cpp, tests/drivers/run_cluster.sh, tests/e2e/configuration/default_config.py, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/manual_setting_replicas.py, tests/e2e/high_availability/single_coordinator.py, tests/jepsen/src/memgraph/support.clj
Removes HA from experimental features.
=> Remove HA from experimental

src/communication/http/listener.hpp, src/communication/http/server.hpp, src/communication/v2/listener.hpp, src/communication/v2/pool.hpp, src/communication/v2/session.hpp, src/communication/websocket/listener.cpp, src/communication/websocket/listener.hpp, src/communication/websocket/server.cpp, src/communication/websocket/server.hpp, src/glue/SessionHL.cpp, src/query/plan/operator.cpp, src/utils/memory_layout.hpp, src/utils/small_vector.hpp, tests/unit/monitoring.cpp
Bugfix: UB due to unhandled endpoint errors
Bugfix: UB when using small_vector with small buffer sized 0
Add AbortCheck to all Pulls
Stop sending results on a dropped connection
=> Communication stack improvements

src/dbms/inmemory/replication_handlers.cpp, src/storage/v2/durability/version.hpp, src/storage/v2/durability/wal.cpp, src/storage/v2/durability/wal.hpp, src/storage/v2/id_types.hpp, src/storage/v2/inmemory/storage.hpp, tests/unit/storage_v2_durability_inmemory.cpp, tests/unit/storage_v2_wal_file.cpp
It was one big struct, replaced with variant.
=> Refactor WalDeltaData

src/query/trigger.hpp, src/utils/rw_spin_lock.hpp, src/utils/skip_list.hpp, src/utils/spin_lock.hpp
RWSpinLock added try_lock()
SpinLock removed move capabilities
SkipListGc using guard instead of OnScopeExit
=> SkipListGc fixes

src/query/procedure/module.cpp
Error message when unloading a query module was not correct.
=> Update error message for unloading query modules

src/dbms/replication_handlers.cpp, src/flags/run_time_configurable.cpp, src/http_handlers/metrics.hpp, src/license/license.cpp, src/license/license.hpp, src/query/frontend/ast/ast.hpp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/frontend/opencypher/grammar/Cypher.g4, src/query/frontend/opencypher/grammar/MemgraphCypher.g4, src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4, src/query/frontend/semantic/required_privileges.cpp, src/query/interpreter.cpp, src/replication_handler/system_replication.cpp, tests/e2e/CMakeLists.txt, tests/e2e/show_license_info/CMakeLists.txt, tests/e2e/show_license_info/common.py, tests/e2e/show_license_info/test_show_license_info.py, tests/e2e/show_license_info/workloads.yaml, tests/unit/license.cpp
`SHOW LICENSE INFO` query was added to display a more granular view of what's the status with the license.
=> Add SHOW LICENSE INFO query

tests/e2e/runner.py
Reverts memgraph/memgraph#2584.
New type of issue https://github.com/memgraph/memgraph/actions/runs/12672731702/job/35325581300
=> Revert "Fix cleanup for e2e tests"

src/coordination/coordinator_instance_client.cpp, src/coordination/coordinator_log_store.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/include/coordination/coordinator_communication_config.hpp, src/coordination/include/coordination/coordinator_instance_client.hpp, src/coordination/include/coordination/coordinator_log_store.hpp, src/coordination/include/coordination/coordinator_state_machine.hpp, src/coordination/include/coordination/coordinator_state_manager.hpp, src/coordination/raft_state.cpp, src/coordination/utils.cpp, src/flags/coord_flag_env_handler.cpp, src/flags/coord_flag_env_handler.hpp, src/flags/coordination.cpp, src/flags/coordination.hpp, src/memgraph.cpp, tests/e2e/configuration/default_config.py, tests/e2e/high_availability/distributed_coords.py, tests/unit/coordinator_env_flag_handler.cpp, tests/unit/coordinator_instance.cpp, tests/unit/coordinator_raft_state.cpp, tests/unit/coordinator_state_machine.cpp, tests/unit/coordinator_state_manager.cpp, tests/unit/coordinator_utils.cpp
HA will always use durable storage. Flag `--ha-durability` is removed.
=> Always use durable storage in high availability for coordinator data

.github/workflows/check_flakiness.yaml, .github/workflows/diff.yaml, tools/diff_setup.py
This PR fixes mistakes that were overlooked while adding a new job for testing query modules.
=> Fix query modules CI jobs

include/_mgp.hpp, include/mg_procedure.h, include/mgp.hpp, query_modules/convert.cpp, src/query/procedure/mg_procedure_impl.cpp
Allows for more efficient list population in str2object
=> Add reserve to list in C & C++ APIs

src/query/typed_value.cpp, tests/query_modules/runner.py
This PR delivers a fix of copy and move assignment operators in `TypedValue`.
=> Fix copy and move assignment operators in TypedValue

src/utils/rw_spin_lock.hpp
- `lock()` cannot use `memory_order_relaxed` when querying for readers because it may read a stale value. Changed this to `memory_order_acquire`.
- `lock_shared()` needs to use `memory_order_acq_rel` to publish the incremented reader count.
- `is_locked()` cannot be `memory_order_relaxed`, as this may read stale values. Changed to `memory_order_acquire`.
- (Also fixes a few typos in a struct name and a comment.)
=> fix: Set correct memory ordering for RWSpinLock

src/memgraph.cpp, src/telemetry/telemetry.cpp, src/telemetry/telemetry.hpp, tests/integration/telemetry/client.cpp
Sending a first message after 60s and then every 8h
=> Change telemetry config

src/replication/include/replication/replication_client.hpp, src/replication_handler/replication_handler.cpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/replication/replication_transaction.hpp, tests/e2e/high_availability/single_coordinator.py, tests/e2e/replication/show_while_creating_invalid_state.py, tests/e2e/system_replication/multitenancy.py, tests/unit/storage_v2_replication.cpp
FrequentCheck sets state to BEHIND after 3 failed pings.
GetTimestampInfo uses the local ts, does not send an RPC.
=> SHOW REPLICAS uses local timestamp

tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/utils.clj
Fixes the bug with error handling when adding nodes.
=> Handle failures of add-nodes in Jepsen stress test

src/storage/v2/edge_accessor.cpp
Since removal of EdgeSetFrom, EdgeSetTo, EdgeChangeType this code can be simpler.
This use to take forever to validate visibility of edges, now its fast:
```
CREATE EDGE INDEX ON :R;
CREATE (a), (b) WITH * UNWIND range(1,1000000) AS i CREATE (a)-[:R]->(b);
MATCH ()-[r:R]->() RETURN count(*);
```
=> Optimise EdgeAccessor::IsVisible

src/auth/replication_handlers.cpp, src/coordination/coordinator_instance_management_server_handlers.cpp, src/coordination/coordinator_log_store.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/data_instance_management_server_handlers.cpp, src/dbms/inmemory/replication_handlers.cpp, src/dbms/replication_handlers.cpp, src/io/network/endpoint.cpp, src/replication/replication_server.cpp, src/replication_handler/system_replication.cpp, src/rpc/utils.hpp, src/storage/v2/replication/replication_client.cpp, tests/unit/coordinator_log_store.cpp, tests/unit/coordinator_state_machine.cpp
Adds MT logs to improve debugging experience. Wraps JSON parsing functions in HA code to explicitly crash the database when they occur. Removed unnecessary RPC logs since they are duplicated.
=> Add MT logs, handle json parsing exceptions

licenses/BSL.txt
Updated BSL change date for new release.
=> Update BSL license change date for v3.1.0

tests/jepsen/src/memgraph/mtenancy/test.clj, tests/jepsen/src/memgraph/mtenancy/utils.clj, tests/jepsen/src/memgraph/query.clj, tests/jepsen/src/memgraph/utils.clj
Adds node update and edge creation/deletion queries to the MT Jepsen test.
=> Add update queries to MT Jepsen test

src/flags/CMakeLists.txt, src/flags/storage_access.cpp, src/flags/storage_access.hpp, src/query/interpreter.cpp, tests/e2e/configuration/default_config.py
New flag --storage-access-timeout-sec
=> Storage access timeout as a command line parameter

licenses/BSL.txt
Update BSL license change date for v3.1.1
=> Update BSL license change date for v3.1.1

src/utils/scheduler.cpp
The PR fixes the following situation:
There are 2 threads, 1st one is the periodic snapshot thread running from the scheduler, the 2nd one is the demotion thread running in replication_handler.
T1 takes unique_lock in scheduler and holds it during the function run.
T2 takes unique repl state lock and tries to Pause the periodic snapshot thread. Pausing the snapshot thread requires unique lock in the scheduler, held by T1. T1 in the meantime tries to take repl state lock to read the replication role so it could decide whether to take the snapshot or not (depending on whether it is main or replica).
The correct thing is to release the lock in scheduler before starting snapshot creation.
=> Bugfix: Scheduler cannot be paused while executing its function

src/utils/resource_lock.hpp, tests/unit/utils_resource_lock.cpp
- Refactored ResourceLock to maintain a common pattern
- Make ResourceLock prioritise READ_ONLY over WRITE
- Allow downgrading the lock from WRITE or READ_ONLY, to READ
=> Improve ResourceLock

.github/workflows/reusable_package.yaml
Use self-hosted ARM64 runner for packaging.
=> Remove large arm runner

src/utils/resource_lock.hpp, tests/unit/utils_resource_lock.cpp
Use latch to reduce the jitter to thread creation. Allow for more time.
Also `ro_pending_count` was possible to be updated outside the lock when it failed to try_lock, hence now atomic.
=> Fix reliability for resource lock

.github/workflows/stress_jepsen_ha.yaml
Added guards against empty input variables.
=> Fix Jepsen Workflow

.github/workflows/promote_rc_release.yml
Fixes to promote RC workflow - some images were not being copied across S3 buckets and the cleanup on Dockerhub was failing silently for `relwithdebinfo`.
=> Release 3.2.1 fixes

src/communication/client.hpp, src/coordination/coordinator_instance_connector.cpp, src/coordination/include/coordination/replication_instance_client.hpp, src/coordination/include/coordination/replication_instance_connector.hpp, src/coordination/replication_instance_client.cpp, src/coordination/replication_instance_connector.cpp, src/replication/include/replication/replication_client.hpp, src/replication_coordination_glue/handler.hpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/rpc/client.hpp, src/rpc/protocol.cpp, src/rpc/protocol.hpp, src/rpc/server.hpp, src/storage/v2/inmemory/replication/recovery.hpp, src/storage/v2/replication/replication_client.cpp, tests/e2e/high_availability/rpc_comm.cpp, tests/unit/replication_rpc_progress.cpp, tests/unit/rpc.cpp, tests/unit/rpc_in_progress.cpp, tests/unit/rpc_timeouts.cpp, tests/unit/snapshot_rpc_progress.cpp
Namings and nomenclature is aligned with the book Introduction to Reliable and Secure Distributed Programming. Failure detector is abstracted under its own class. Describes links in distributed env as we use it.
=> Align HA nomenclature. Introduce abstract failure detector

tests/e2e/durability/snapshot_recovery.py
Use nanoseconds and sleep between snapshots.
=> Make bulletproof snapshot recovery e2e test

src/coordination/coordinator_cluster_state.cpp
Properly protect special member functions of a concurrent data structure which represents cluster state.
=> Protect special member functions of a concurrent data structure representing cluster state

.github/workflows/release_mgbench_client.yaml, .github/workflows/reusable_build_mgbench_client.yml
- New job for building a single Docker image
- Allow uploading artifact from CI
=> Add ability to build single mgbench image and create artifact

src/dbms/inmemory/replication_handlers.cpp, src/storage/v2/inmemory/storage.cpp, tests/e2e/durability/snapshot_recovery.py
Fixup of the initial effort to fix the issue: [2976](https://github.com/memgraph/memgraph/pull/2976)
=> Bugfix: Snapshot fails to mark whole range of committed timestamps

src/flags/coord_flag_env_handler.cpp, tests/unit/utils_rwlock.cpp
The starting of the threads added jitter to the timings
=> Improve MultipleReaders unit test

release/package/mgbuild.sh
Install lsof before E2E tests.
=> Install lsof before E2E tests.

src/dbms/inmemory/replication_handlers.cpp
Global ts should only be updated in the commit.
=> Duplicated update of global ts on replica

src/query/hops_limit.hpp, src/query/interpret/awesome_memgraph_functions.cpp, src/query/interpret/awesome_memgraph_functions.hpp, src/query/interpret/eval.hpp, src/query/plan/operator.cpp, tests/gql_behave/tests/memgraph_V1/features/hops_limit.feature
Add function to display hops limit
=> Add get hops limit function

.github/workflows/stress_jepsen_ha.yaml
Added new mode input to Jepsen stress test workflow.
=> Add Jepsen mode input to stress test workflow

tests/jepsen/src/memgraph/high_availability/bank/test.clj
Unhandled error that MAIN could be unwriteable in HA bank test
=> Fix HA bank test flakiness

tests/jepsen/src/memgraph/high_availability/create/test.clj
Running this test to verify I didn't destroy previous replication
=> Original jepsen test for (A)SYNC replication

src/coordination/coordinator_cluster_state.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/coordination/constants.hpp, tests/unit/coordinator_cluster_state.cpp
kDataInstances was changed by accident for 3.3 which caused upgrade to fail.
=> Fix HA upgrade 3.2.1 -> 3.3

src/query/interpreter.cpp, tests/e2e/configuration/storage_info.py
Add database uuid in show storage info
=> Add database uuid in show storage info

src/dbms/inmemory/replication_handlers.cpp, src/dbms/inmemory/replication_handlers.hpp, src/replication_coordination_glue/messages.hpp, src/rpc/client.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/replication/replication_storage_state.cpp, src/storage/v2/replication/replication_storage_state.hpp, src/storage/v2/replication/replication_transaction.cpp, src/storage/v2/replication/replication_transaction.hpp, src/storage/v2/replication/rpc.cpp, src/storage/v2/replication/rpc.hpp
Remove seq_num from PrepareCommitHandler since it was unused and add durability_commit_timestamp cache.
=> Check durability_commit_timestamp and remove seq_num

src/storage/v2/durability/durability.cpp, src/storage/v2/durability/snapshot.cpp
Seems to be fixed by using durable timestamp.
=> Fix WAL chain by comparing ldt

.github/workflows/reusable_release_tests.yaml, .github/workflows/reusable_stress_jepsen.yaml
Fix workflows by copying libstdc++.so
=> Fix Jepsen Workflows

config/mappings.json
=> Add missing apoc mappings

config/mappings.json
Add math.round introduced in [MAGE652](https://github.com/memgraph/mage/pull/652) to GraphQL mappings
=> Add math.round to mappings

config/mappings.json
Fix incorrect GraphQL mappings
=> Fix incorrect GraphQL mappings

src/auth/auth.cpp, src/auth/rpc.cpp, src/auth/rpc.hpp, src/coordination/data_instance_management_server_handlers.cpp, src/dbms/dbms_handler.cpp, src/dbms/rpc.cpp, src/dbms/rpc.hpp, src/replication/include/replication/state.hpp, src/replication/include/replication/status.hpp, src/replication/state.cpp, src/replication/status.cpp, src/replication_handler/replication_handler.cpp, src/storage/v2/durability/durability.cpp, src/system/include/system/action.hpp, src/system/include/system/transaction.hpp, tests/unit/replication_persistence_helper.cpp
Duplicated logic, replication epoch wasn't used.
=> Remove ReplicationEpoch from replication::MainRole

src/replication/include/replication/status.hpp
The PR which broke this was in this release so docs not necessary.
=> Update default durability version

query_modules/convert.c, src/query/procedure/mg_procedure_impl.cpp, tests/query_modules/to_tree_test/test_exclude_filters/test.yml, tests/query_modules/to_tree_test/test_nested/test.yml
Bug introduced and fixed under the v3.5 release
=> Bugfix: ToTree uses wrong ptr checks and might segfault

tests/e2e/high_availability/replication_lag.py
Replicas should be killed before main to be sure the failover doesn't happen.
=> fix: E2E test replication lag

src/query/frontend/ast/cypher_main_visitor.cpp, src/query/frontend/ast/cypher_main_visitor.hpp, src/query/frontend/opencypher/grammar/Cypher.g4, tests/gql_behave/tests/memgraph_V1/features/patterns.feature
Git commit description, explain the changes you made here
---
__*Leave above in PR description, copy the below into a comment*__
___
- What has changed? What does it mean for a user? What should a user do with it? [#{{PR_number}}]({{link to the PR}})
=> Add pattern expressions

src/query/interpreter.cpp, tests/integration/auth/runner.py, tests/integration/fine_grained_access/runner.py
Git commit description, explain the changes you made here
---
__*Leave above in PR description, copy the below into a comment*__
___
- What has changed? What does it mean for a user? What should a user do with it? [#{{PR_number}}]({{link to the PR}})
=> Update authorized query error message.

.github/workflows/package_memgraph.yaml, tools/package_setup.py
Add push to github option back into package memgraph workflow
=> Add push to github option back into package memgraph workflow
