src/query/common.cpp, tests/gql_behave/tests/memgraph_V1/features/match.feature
=> [master < T0766-MG] Fix ORDER BY and temporal types

src/communication/server.hpp
=> [master < T0782-MG] Remove unnecessary use of string in server start method

tests/e2e/memgraph.py
This adds a simple python test method for killing instances under test in a way that is impossible for the process to catch and gracefully clean up, in the way that the existing `stop` method may lead to graceful handling if the subprocess implements a SIGTERM handler.
=> [master < T0876-MG] Add an uncatchable kill method to the python MemgraphInstanceRunner 

src/query/db_accessor.hpp, src/storage/v2/CMakeLists.txt, src/storage/v2/schemas.cpp, src/storage/v2/schemas.hpp, src/storage/v2/storage.cpp, src/storage/v2/storage.hpp
Introducing only in-memory representation of schema, without any support for creating or validating schema against vertices.
[epic < Task] PR
=> [E112-MG < T0848-MG] Add initial schema implementation

include/mg_procedure.h
> Declare `mgp_func_context` outside the callback function
We missed to declare this struct, so it was implicitly declared in the type definition of `mg_func_cb`, but we introduced this for future improvements, currently it doesn't have any value (apart from making sure we can add new functionalities to functions without breaking the API). I added the declaration just to be 100% correct.
As this didn't mean any error to the users, because the struct is currently unused, I am not sure whether we should add this to the changelog or not. What do you think?
=> [master < MG] Declare `mgp_func_context` outside the callback funciton

src/io/simulator/simulator_handle.cpp, src/io/simulator/simulator_handle.hpp
This causes instructions for basic_request.cpp to drop from 281 million to 28 million
=> Optimize simulator RNG usage

tests/unit/main.cpp
allows test log verbosity to be overridden when running individual unit tests by setting the `SPDLOG_LEVEL` env var:
```
SPDLOG_LEVEL=error tests/unit/machine_manager
```
=> load spdlog env in tests

src/coordinator/coordinator_worker.hpp, src/coordinator/shard_map.cpp, src/io/address.hpp, src/io/future.hpp, src/io/message_histogram_collector.hpp, src/io/rsm/raft.hpp, src/io/simulator/simulator_handle.cpp, src/io/simulator/simulator_handle.hpp, src/io/simulator/simulator_stats.hpp, src/io/simulator/simulator_transport.hpp, src/io/transport.hpp, src/machine_manager/machine_config.hpp, src/machine_manager/machine_manager.hpp, src/query/v2/interpreter.cpp, src/storage/v3/shard_manager.hpp, src/storage/v3/shard_worker.hpp, tests/simulation/basic_request.cpp, tests/simulation/cluster_property_test.cpp, tests/simulation/raft.cpp, tests/simulation/shard_rsm.cpp, tests/simulation/test_cluster.hpp
This makes the simulated tests deterministic for basic_request, multithreaded raft tests, and the cluster property tests. 
Determinism is tested explicitly by running tests twice and asserting that the simulator stats and latency histograms are identical, so if we accidentally add non-deterministic behavior, the tests will hopefully flag it quickly. There are cases where threads will behave slightly differently in-between simulator ticks, but this is fine, because the actual cross-thread communication points are fully controlled now, which is the extent of the partial order that we must impose to achieve the goal of replayable tests.
=> [🍍  <-] Improve simulator determinism

src/memgraph.cpp, tests/e2e/configuration/configuration_check.py
before:
```
λ ./memgraph -h
ERROR: unknown command line flag 'h'
```
after is same as --help
=> [master <- ] Add support for -h to show help in addition to --help

src/query/plan/operator.cpp, src/query/plan/operator.lcp, src/query/plan/pretty_print.cpp, src/query/plan/pretty_print.hpp, src/query/plan/read_write_type_checker.cpp, src/query/plan/read_write_type_checker.hpp, src/query/plan/rewrite/index_lookup.hpp, src/query/plan/rule_based_planner.hpp, src/utils/event_counter.cpp, tests/gql_behave/tests/memgraph_V1/features/update_clauses.feature, tests/unit/interpreter.cpp, tests/unit/query_plan.cpp, tests/unit/query_plan_checker.hpp
=> [master < T507-FL] EmptyResult operator

src/query/v2/multiframe.cpp, src/query/v2/multiframe.hpp
```
Correct implementation of MultiFrame iterators::begin. If no Frames are valid, we need to return end()
```
=> [:pineapple: < T1190] Correct implementation of begin iterators

src/query/plan/read_write_type_checker.cpp, src/query/plan/read_write_type_checker.hpp, tests/unit/query_plan_read_write_typecheck.cpp
Closes #705 
^ wrote my view on the problem in the issue. I believe the bug is in the updating of query `rw_type` which I amended here using my own logic and experience from that issue.
=> [master < T1213] Match not allowed on replica

tests/mgbench/benchmark.py, tests/mgbench/graph_bench.py
The bench graph basic queries are ignored in standard CI/CD call `pokec/medium/*/*.` Tail latency has been turned off by default. Since latency is not present at the grafana at the moment.
=> [master < T1201] Run mgbench diff under 30 min

include/_mgp.hpp, include/mgp.hpp, tests/unit/cpp_api.cpp
This PR fixes few bugs:
- there was a problem with getting Properties - since `std::string_view` was used as a key to store Properties in `std::map`, due to the nature of how properties are retrieved from `mgp_properties_get_next` in combination with `std::string_view`, the new property would overwrite the old one and the user wouldn't get the correct state of properties (some would miss, std::map would be filled with same property)
- there was a missing set_property function in both `mgp.hpp` and `_mgp.hpp`
=> [master < T1220-MG] Fix bug on properties in c++ api

src/query/plan/rewrite/index_lookup.hpp, src/query/plan/rule_based_planner.hpp, tests/unit/query_plan.cpp
Indexes were not applied when using optional match with label property index.The actual problem was that in the additional branch, optional match would not see the bounded symbol when filtering by that symbol's property. Index could not be fetched accordingly
FOREACH. Index was not applied correctly since the plan was forbidden to alter the inner children of the foreach logical operator. Merge can be one of the children, hence the index lookup rewriter can create the index.
=> [master < T565-FL] Use indexes in optional match and foreach

src/query/plan/operator.cpp, tests/gql_behave/tests/memgraph_V1/features/foreach.feature, tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
The algorithm outputted duplicated edges when used with an upper bound set to a limiting value. From changes in the code it can be seen that we should have always continued the iteration if we encountered an already expanded edge
=> [master < T569-FL] Allshortest bugfix

.github/workflows/daily_benchmark.yaml, .github/workflows/release_centos8.yaml, .github/workflows/release_debian10.yaml, .github/workflows/release_ubuntu2004.yaml
Since release builds that are run every day take around 10 h to complete, I want them to start at 22 h so they can finish by the time I get to the office. Mostly to be able to start with a release earlier.
=> [master < T583] Change start time of daily build

src/query/plan/operator.cpp, tests/e2e/fine_grained_access/create_delete_filtering_tests.py
```
UNWIND 
[{id: '1', lat: 10, lng: 10}, {id: '2', lat: 10, lng: 10}, {id: '3', lat: 10, lng: 10}] AS row
MERGE (o:Location {id: row.id}) RETURN o;
```
did not work and threw an exception because newly created nodes were not seen and therefore prohibited.
**Changelog message**: Label based auth improved to see information about newly created nodes when merging nodes inside a query.
=> [master < T582-FL] Fix label-based auth using OLD view instead of NEW when merging nodes

src/query/frontend/ast/ast.lcp, src/query/interpret/eval.hpp, tests/unit/query_expression_evaluator.cpp
This PR is one in a series of PRs created due to benchmarking and improving the `LOAD CSV` clause, which was tested and documented [here](https://github.com/memgraph/memgraph/pull/753).
Here I am implementing `ReferenceBasedEvaluator` as it was shown that copying of array of values slows down performance when there are many properties in a `row` created when reading a CSV file.
**Release note**: Implemented `ReferenceBasedEvaluator` as it was shown that copying of an array of values slows down performance when there are many properties in a `row` created when reading a CSV file
**Benchmarking**
| Number of properties per line | Import time (OLD) [seconds] | Import time (NEW) [seconds] | Throughput (OLD) [lines/s] | Throughput (NEW) [lines/s] |
| -- | -- | -- |  -- | -- …
=> [master < T585-FL] Improve Visit performance

tests/mgbench/client.cpp, tests/mgbench/runners.py
- We have moved latency measurment to the client side. Each executed workload/query will come with its standard latency measurements (min, max, mean, p99, p95, p90, p75, p50) 
- Logging has been fixed, client is now reporting everything to stderr and stdout properly. 
- Validation mode accepts single query, execute it, and returns results alongside metadata. For workload validation between different vendors. 
Tasks: 
Optional task:
=> [master < ] Update mgbench c++ client

src/query/common.hpp, src/query/db_accessor.hpp, src/query/plan/operator.cpp, src/storage/v2/edge_accessor.cpp, src/storage/v2/edge_accessor.hpp, src/storage/v2/property_store.cpp, src/storage/v2/property_store.hpp, src/storage/v2/vertex_accessor.cpp, src/storage/v2/vertex_accessor.hpp, tests/gql_behave/tests/memgraph_V1/features/functions.feature, tests/unit/storage_v2_property_store.cpp
**Release note**: Improve performance by storing node or edge properties in a property store all at once on node or edge creation, instead of individually,  when dealing with large numbers of properties.
**Benchmarking**
| Number of properties per line | Import time (OLD) [seconds] | Import time (NEW) [seconds] | Throughput (OLD) [lines/s] | Throughput (NEW) [lines/s] |
| -- | -- | -- |  -- | -- |
|2 | 3.6s | 3.6 s|  |  |
|10 | 9.6s | 8.7 s|   |  |
|20 | 22s | 17.5 s|  |   |
=> [master < T591-FL] Enhance performance of Property Store on node creation

src/query/frontend/semantic/symbol_generator.cpp, src/query/frontend/semantic/symbol_generator.hpp, src/query/plan/rule_based_planner.cpp, tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature
The PR namely concerns SET and WITH clauses where exists() functionality does not work yet. A not implemented exception is thrown.
=> [T1238 < T1247] Add exceptions for unimplemented EXISTS query parts

src/query/procedure/mg_procedure_impl.hpp, tests/unit/cpp_api.cpp
This PR fixes Memgraph crashing when a user’s query procedure attempts to construct a `LocalDateTime` object with invalid parameters
A C++ API `LocalDateTime` object is built upon a `memgraph::utils::LocalDateTime` object, which has a constructor that’s a) noexcept b) constructs a `memgraph::utils::Date` member, which may throw an exception
This error has been fixed together with other `LocalDateTime` constructors that were marked as noexcept but might throw an exception
> Fix Memgraph crashing when constructing mgp::LocalDateTime objects with invalid parameters
> Constructing LocalDateTime objects with invalid parameters doesn’t crash Memgraph anymore, but throws an informative exception.
=> Remove noexcept from functions that may throw

.github/workflows/diff.yaml, tests/setup.sh
Memgraph used outdated pulsar-client 2.8.1.
I updated it to the fresh 3.1.0.
=> Update pulsar client for e2e tests

src/communication/bolt/v1/states/executing.hpp, src/communication/http/listener.hpp, src/communication/http/server.hpp, src/communication/http/session.hpp, src/communication/v2/listener.hpp, src/communication/v2/session.hpp, src/http_handlers/CMakeLists.txt, src/http_handlers/metrics.hpp, src/memgraph.cpp, src/query/frontend/ast/cypher_main_visitor.hpp, src/query/interpreter.cpp, src/query/interpreter.hpp, src/query/plan/operator.cpp, src/query/procedure/py_module.cpp, src/query/stream/streams.cpp, src/query/trigger.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/storage.cpp, src/utils/CMakeLists.txt, src/utils/event_counter.cpp, src/utils/event_gauge.cpp, src/utils/event_gauge.hpp, src/utils/event_histogram.cpp, src/utils/event_histogram.hpp, tests/e2e/configuration/default_config.py, tests/unit/CMakeLists.txt, tests/unit/utils_histogram.cpp
**[Enterprise feature]**
The PR exposes an HTTP endpoint for Memgraph, and adds the possibility to fetch the current metrics via a GET endpoint.
The metrics which are included in the response contain information over:
- transactions
- query latencies
- streams
- triggers
- indexes
- snapshots
- operators
- sessions
- messages
The address and port are configurable and are initially accessed with 0.0.0.0:9091 host and port.
- Final git message: Expose system metrics via HTTP endpoint
=> [master < E218] Expose system metrics over a HTTP endpoint

.clang-format, .pre-commit-config.yaml, src/communication/bolt/v1/session.hpp, src/communication/bolt/v1/states/handlers.hpp, src/memgraph.cpp, src/query/interpreter.cpp, src/query/interpreter.hpp, tests/drivers/csharp/v4_1/Metadata/Metadata.csproj, tests/drivers/csharp/v4_1/Metadata/Program.cs, tests/drivers/go/v4/metadata.go, tests/drivers/go/v4/run.sh, tests/drivers/java/v1/Basic.java, tests/drivers/java/v4_1/Metadata.java, tests/drivers/java/v4_1/run.sh, tests/drivers/node/v4_1/metadata.js, tests/drivers/node/v4_1/run.sh, tests/drivers/python/v4_1/metadata.py, tests/drivers/python/v4_1/run.sh, tests/unit/bolt_session.cpp
This feature should allow users to pass user-defined metadata via their clients. This is useful when a user has many transactions and they would want to better differentiate between them. 
Once the metadata is passed to Memgraph, the user can query it by executing SHOW TRANSACTIONS, whose output has a new field "metadata".
=> [master < T945] Handle user-defined metadata and expose it with SHOW TRANSACTIONS

src/query/interpreter.cpp
CREATE/DROP/USE/SHOW DATABASE queries are disabled in replicas. Replicas have only a single DB and should the user want to have replication for a particular DB, they need to spin up an instance that will handle just that DB.
=> [E952 < T] Handle replication in v1

src/dbms/global.hpp, src/dbms/session_context_handler.hpp, src/dbms/storage_handler.hpp, src/memgraph.cpp, src/query/interpreter.cpp
User can recover previous tenants by passing an argument to memgraph.
In addition drop database will delete the storage directory, so successive creates won't recover old data.
Note: needed to merge on sync so we'll be sure no one is using the storage when the dir gets deleted.
=> [E952 < T] Support tenant recovery at startup

src/query/exceptions.hpp
I was testing replication in Memgraph and noticed that the exception message for when you try to write to MAIN with SYNC replica down consists of a non-existent query. `SHOW REPLICA` query does not exist, and `SHOW REPLICAS` query is the correct one.
=> [master <] Fix replica exception message

src/storage/v2/storage.cpp, src/storage/v2/storage.hpp, src/utils/skip_list.hpp, tests/e2e/CMakeLists.txt, tests/e2e/analytical_mode/CMakeLists.txt, tests/e2e/analytical_mode/common.py, tests/e2e/analytical_mode/free_memory.py, tests/e2e/analytical_mode/workloads.yaml
This fix corrects the garbage collection of our in memory store to handle deletions made while in IN_MEMORY_ANALYTICAL mode. They will now be collected rather than leak.
Closes #957
=> [master < T0957] Fix storage GC to handle IN_MEMORY_ANALYTICAL

include/mgp.hpp
Made an error in the last [PR](https://github.com/memgraph/memgraph/pull/964) as I didn't put inline on function in detail namespace. But when building MAGE there is a multiple definition error, inline is thus required.
=> [master < T] Fix multiple include error

src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_server.cpp, src/storage/v2/storage.cpp
This is related to the [issue](https://github.com/memgraph/memgraph/issues/953) with replication, logging is added to provide a bit more context on what is happening, which at the moment is not really visible.  Logs mostly include starting points on the replica recovery process flow, via Snapshot file or WAL. 
Closes https://github.com/memgraph/memgraph/issues/953.
=> [master < I953 ] Improve replication logging. 

release/package/amzn-2/Dockerfile, release/package/centos-7/Dockerfile, release/package/centos-9/Dockerfile, release/package/debian-10/Dockerfile, release/package/debian-11-arm/Dockerfile, release/package/debian-11/Dockerfile, release/package/fedora-36/Dockerfile, release/package/run.sh, release/package/ubuntu-18.04/Dockerfile, release/package/ubuntu-20.04/Dockerfile, release/package/ubuntu-22.04-arm/Dockerfile, release/package/ubuntu-22.04/Dockerfile
The motivation here is a need for Debian 10 builder image because Jepsen v0.3.0 still requires Debian 10 image (only node containers, e.g., `jepsen-n1`)
=> Add package/release/run.sh build v4 debian-10

environment/util.sh, release/package/ubuntu-22.04/Dockerfile
Needed to be able to build memgraph on macOS hosts via builder Docker images.
=> Add macOS support under environment/util.sh:operating_system

include/mgp.hpp, tests/unit/cpp_api.cpp
During writing collections query module, the need to be able to print the mgp::Type was found, so it was solved with this PR.
You are now able to print the type of mgp::Type() using operator << . For example, if you have a mgp::List() list, cout<< list <<endl will output "list".
=> [master < T1080] overload << operator for mgp::Type

include/mgp.hpp
This is an additional overload of Record::Insert function. While writing collections query module in  C++ API, the need for returning mgp::Any datatype in AddProcedure was discovered. The changes in this PR adress this problem, and by overloading Record::Insert to accept mgp::Value, mgp::Any datatype can be inserted into Record.
You are now able to return mgp::Type::Any inside Record when writing query modules in C++ API.
=> [master < T1094] Extend insert on record to accept mgp::Value

include/mgp.hpp, tests/unit/cpp_api.cpp
Before, when writing C++ query moduels, directly comparing two mgp::Value variables was not possible. With this PR, it is.
You are now able to compare two mgp::Value variables with < operator.
=> [master < T1090] Add overload for operator< in mgp::Value

include/mgp.hpp
Using functions defined in mgp::Value, that return the Type of the value, such as ValueList, that extracted mgp::List from mgp::Value, only returned const types. While writing collections query module, there was need to return non const variables so move semantics could be used, this PR does exactly that.
You are now able to extract non const data from mgp::Value @antoniofilipovic could you help me phrase this better, I dont think this is good.
=> [master < T1099] Add non-const mgp::Value return type for C++ API

src/communication/bolt/v1/value.hpp, tests/drivers/python/v5_8/path.py, tests/drivers/python/v5_8/run.sh
Bolt v5 introduced element_id to Vertex and Edges.
When generating a Path, the edge's element_id got ignored and defaulted to "".
closes #1100
=> [master < ] Bugfix: Path generation ignores edge's element_id

.github/workflows/diff.yaml, .github/workflows/release_centos8.yaml, .github/workflows/release_debian10.yaml, .github/workflows/release_ubuntu2004.yaml, tests/setup.sh
Some e2e tests fail due to misalignment between system compilers/libraries/etc. and our toolchain.
This change will force the use of the toolchain libraries for all e2e tests.
=> Created a custom e2e test activation to include the toolchain libs

README.md
I've removed the link to the Discourse forum for the README.md file.
=> [master < 1137-remove-link-to-discourse] Remove link to Discourse forum

.pre-commit-config.yaml, CMakeLists.txt, libs/CMakeLists.txt, libs/setup.sh, licenses/third-party/abseil-cpp/LICENSE, licenses/third-party/compile-time-regular-expressions/LICENSE, src/query/interpreter.cpp, src/storage/v2/CMakeLists.txt, src/storage/v2/disk/rocksdb_storage.hpp, src/storage/v2/disk/storage.cpp, src/storage/v2/edge_direction.hpp, src/storage/v2/inmemory/indices_utils.hpp, src/storage/v2/inmemory/label_index.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/mvcc.hpp, src/storage/v2/storage.cpp, src/storage/v2/transaction.hpp, src/storage/v2/vertex_accessor.cpp, src/storage/v2/vertex_info_cache.cpp, src/storage/v2/vertex_info_cache.hpp, src/storage/v2/vertex_info_cache_fwd.hpp, src/storage/v2/vertex_info_helpers.hpp, src/utils/skip_list.hpp, src/utils/variant_helpers.hpp, tests/e2e/configuration/default_config.py, tests/unit/storage_v2_durability_inmemory.cpp, tools/github/clang-tidy/clang-tidy-diff.py, tools/pre-commit/clang-tidy.py
=> [master < ] Fixes for 100% percent cpu issues

src/glue/auth_checker.cpp, src/glue/auth_checker.hpp, src/query/auth_checker.hpp, src/query/cypher_query_interpreter.cpp, src/query/interpret/eval.cpp, src/query/interpret/eval.hpp, src/query/interpreter.cpp, src/query/plan/operator.cpp, tests/unit/dbms_interp.cpp, tests/unit/query_trigger.cpp
Some non-transactional queries used the DbAccessor to retrieve information at run-time (mostly to evaluate literals).
Here we created a new evaluator that doesn't use transactional information and has a very limited scope.
=> [master < ] Remove DbAccessor from non-transactional queries

src/glue/communication.cpp, src/storage/v2/durability/snapshot.cpp, src/storage/v2/durability/wal.cpp, src/storage/v2/edge.hpp, src/storage/v2/edge_accessor.cpp, src/storage/v2/indices/indices_utils.hpp, src/storage/v2/inmemory/replication/replication_server.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/unique_constraints.cpp, src/storage/v2/vertex.hpp, src/storage/v2/vertex_accessor.cpp, src/utils/rw_spin_lock.hpp
There are situations where multiple readonly queries in parallel are contended on the same vertex lock. Take for example a highly connected supernode which is repetitively used in result values and it needs encode it to a bolt value for sending to the client.
Since `SpinLock` can only be used exclusively, it causes unnecessary blocking. `RWSpinLock` would allow shared reading.
Before: you can see heavy use of `__pthread_spin_lock`
After: in the same part of the profile the locks don't even appear, this is because of the `RWSpinLock`
closes #1189
=> [master <] Introduce a reader writer spin lock

src/query/db_accessor.hpp, src/query/plan/operator.cpp, src/storage/v2/all_vertices_iterable.cpp, src/storage/v2/all_vertices_iterable.hpp, src/storage/v2/inmemory/label_index.hpp, src/storage/v2/inmemory/label_property_index.hpp, src/storage/v2/vertex_accessor.cpp, src/storage/v2/vertex_accessor.hpp, src/storage/v2/vertices_iterable.cpp, src/storage/v2/vertices_iterable.hpp
For example following query:
```
UNWIND RANGE (1, 500) AS i CREATE ();
MATCH (),(),() RETURN COUNT(*);
```
went from `6.549` seconds to `3.625` seconds
=> [master < T1227] Optimise iteration

tests/stress/common.py, tests/stress/detach_delete.py, tests/stress/requirements.txt
Because installation of gqlalchemy is failing on centos-7, tests are rewritten to use the existing toolset.
=> Remove gqlalchemy from stress tests

include/_mgp.hpp, include/_mgp_mock.py, include/mg_procedure.h, include/mgp.hpp, include/mgp.py, include/mgp_mock.py, src/query/procedure/mg_procedure_impl.cpp, src/query/procedure/py_module.cpp, tests/e2e/mock_api/procedures/path.py, tests/e2e/mock_api/test_compare_mock.py, tests/unit/cpp_api.cpp
There was a need to be able to remove the last element of a path in the C++, C and Python API.
You are now able to remove the last element of a path in C++ (path.Pop()) , C (mgp_path_pop) and Python (path.pop()) API
=> [master < T1249] Add Path.pop to C++ API

.github/workflows/diff.yaml
because graphql e2e gets stuck -> TMP fix just to unblock merging to master
the proper fix should be done when we resolve #1391
=> Revert to Release under Diff Release workflow

README.md
[master <] PR
- The current Contributing section of READMEis bland and there is only subtle sentences about possible contribution from people arriving on the github page. All 3 of us interns weren't able to easily understand how to start up memgraph and work on it, without assistance from mentors. I propose this section be reworded and reorganized to better suit possible new open source contributors who will definitely be able to help memgraph reach greater heights. As memgraph grows and grows there will be more and more eyes on it.
- Contributing section of README has been reworded to better attract possible new open source developers.
=> Revision of Contributing section in README

src/memory/CMakeLists.txt, src/storage/v2/delta.hpp, src/storage/v2/disk/storage.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/transaction.hpp, src/storage/v2/vertex_info_cache.cpp, src/storage/v2/vertex_info_cache.hpp, src/utils/bond.hpp, src/utils/scheduler.hpp, tests/benchmark/CMakeLists.txt, tests/benchmark/storage_v2_gc2.cpp
- Make Bond move assignable
- Make benchmark use jemalloc to be a better indicator of production use
- Make parts of Transaction optional, so not to impact IN_MEMORY's GC
- Reduce contention on committed_transactions_
* No need to do empty check + clear, just do clear
* For some time now, the order of the committed_transactions_ has been random, hence no need to lock to attempt an insert order
* Move all committed_transactions_ to local variable, rather than locking once per transaction being processed.
- Fix subtle GC bug, the commited_transaction unique_ptr that a delta was pointing to was deleted while delta was still potentially accessed
- garbage_undo_buffers_ processing can happen earlier
- As committed_transactions order is random, check all of them to see which can be processed
- …
=> Storage GC changes

src/io/network/socket.cpp, src/io/network/socket.hpp, tests/unit/socket.cpp
Was testing a setup that wasn't used in production. It would start off transferring `10000` then for some reason it would unnecessarily thrash small buffers. 
=> Speedup socket unit test

src/query/plan/operator.cpp, src/query/plan/rewrite/join.hpp, tests/gql_behave/tests/memgraph_V1/features/cartesian.feature
```
MATCH (a), MATCH (b) WHERE a.id = b.id
MATCH (a), MATCH (b) WHERE b.id = a.id
```
was not consistent in result returning
=> Fix hash join expression matching

tests/e2e/garbage_collection/gc_periodic.py
Make gc test go through 2 cycles instead of 1 to make it not flaky.
=> Fix flaky gc test

src/glue/SessionHL.cpp, tests/drivers/python/v5_8/transactions.py
Bolt has specific exception types it expects. 
We need to translate between Bolt and Query worlds. This translation was missing from Commit, Rollback and Discard. 
This would lead to driver behaving wrongly. 
=> Commit, Rollback and Discard were sending back TransientErrors

tests/e2e/interactive_mg_runner.py, tests/e2e/memgraph.py, tests/e2e/runner.py
When an e2e test passes then it data directory does not need to remain.
=> Cleanup filesystem after e2e tests

libs/setup.sh
Example:
* https://github.com/memgraph/memgraph/actions/runs/7113635425/job/19366009223
```
Cloning primary from https://github.com/jemalloc/jemalloc.git secondary from https://github.com/jemalloc/jemalloc.git
Cloning from https://github.com/jemalloc/jemalloc.git
Cloning into 'jemalloc'...
fatal: unable to access 'https://github.com/jemalloc/jemalloc.git/': Could not resolve host: github.com
```
As visible above, the primary URL (which should link to the local dependency cache) was by mistake identical to the secondary (“live”) one.
> Fix unresolved host errors
=> Fix unresolved host errors

src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp
Storage mode configuration flag always set the mode to TRANSACTIONAL instead of the given mode.
closes #1599 
closes #1057
--storage-mode configuration flag is now working properly
=> Fix storage mode flag

src/query/interpret/awesome_memgraph_functions.cpp, tests/gql_behave/tests/memgraph_V1/features/functions.feature
User from community requested this extension for ToBoolean function. Since, e.g., postgresql COPY to CSV will record true values as "t" and false values as "f". 
We also might need to update documentation so it's clear what values ToBoolean casts to true or false.
Release note: Strings "t" and "f" are now resolved into true and false.
closes #1538
=> Extend ToBoolean function so it casts "t" to true and "f" to false.

src/query/plan/rule_based_planner.hpp, tests/gql_behave/tests/memgraph_V1/features/match.feature
Next query would crash database:
`CREATE p0=()-[:T0]->() MERGE ({k:(size(p0))}) RETURN 1`
Problem is that Memgraph isn't updating bound symbols with path identifiers in CREATE. Mentioned problem will be resolved with this PR. 
Release note: It's possible to use path identifier from CREATE clause in other parts of the query.
closes #1331
=> Fix using path in property value after CREATE

.github/workflows/release_debian10.yaml, .github/workflows/release_ubuntu2004.yaml
We didn't apply the changes for e2e tests to release_debian10.yaml and release_ubuntu2004.yaml.
This PR will apply the 2 new steps introduced in PR #1604 .
=> Add changes made to kafka in diff.yml to daily debian10 and ubuntu 20.04 builds

src/query/procedure/py_module.cpp
This is an unstable function and would bump our dependency to python 3.7.
@MarkoBarisic this will fix release build
=> Bugfix don't use _Py_IsFinalizing

src/query/common.hpp, src/query/frontend/ast/ast.hpp, src/query/interpret/eval.hpp, src/query/plan/preprocess.cpp, src/query/plan/preprocess.hpp, src/query/plan/rewrite/index_lookup.hpp, src/query/plan/rule_based_planner.hpp, src/query/typed_value.cpp, src/storage/v2/durability/snapshot.cpp, src/storage/v2/edge_accessor.cpp, src/storage/v2/edge_accessor.hpp, src/storage/v2/indices/indices.cpp, src/storage/v2/indices/indices.hpp, src/storage/v2/indices/indices_utils.hpp, src/storage/v2/inmemory/label_index.cpp, src/storage/v2/inmemory/label_index.hpp, src/storage/v2/inmemory/label_property_index.cpp, src/storage/v2/inmemory/label_property_index.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/inmemory/unique_constraints.cpp, src/storage/v2/inmemory/unique_constraints.hpp, src/storage/v2/property_value.hpp, src/utils/counter.hpp, src/utils/file.cpp, src/utils/skip_list.hpp
While looking at the large data stress test noticed a couple of things which shouldn't have been noticeable.
Some situations which were copying from a local optional, added move to reduce copy of a temporary. 
Also changed `EdgeAccessor::GetProperty` to construct inside of an optional rather than see the cost of `PropertyValue::operator=(PropertyValue &&)`
2024-01-19: Added more things. 
- Added [[unlikely]] to improve expected branching
- std::move or `const &` PropertyIx/LabelIx types
- set underlying type on enum class to make other types smaller
- Preferred vector construction from move iterators
- Check `properties_on_edges` once outside the hot loop
- InMemoryStorage now has a stop_source, which async sources and get a stop_token from to check if they should stop.
- Optimize the …
=> Performance tuning based on stress test

.github/workflows/diff.yaml, tests/jepsen/run.sh
This PR will reduce flakiness of Jepsen tests which is mainly due to issues with the local Jepsen cluster.
Every time a Jepsen test is run, the cluster will be refreshed, ie. brought down and back up again.
=> Add step to refresh jepsen cluster before test

src/auth/auth.cpp, src/auth/crypto.cpp, src/auth/crypto.hpp, src/auth/models.cpp, src/auth/models.hpp, src/utils/enum.hpp, tests/unit/auth.cpp, tests/unit/auth_handler.cpp
To facilitate replication of auth information the hash algorithm used for the hash can not be just flag controlled --password-encryption-algorithm. 
Auth durability migration will introduce a new `version` key.
New "V1" will take the password_hash strings and make them a object which includes both algorithm and hashed password.
Also allow SHA256 hash algorithm to upgrade itself to include a hash once user has validated there password.
Changelog message: Added the password hashing algorithm into auth durability along side the password hash. Also sha256 based passwords hash will upon validation be upgraded to be rehashed with salt.
=> Change auth durability to store hash algorithm

.github/workflows/daily_benchmark.yaml, .github/workflows/diff.yaml, .github/workflows/full_clang_tidy.yaml, .github/workflows/package_memgraph.yaml, .github/workflows/performance_benchmarks.yaml, .github/workflows/release_debian10.yaml, .github/workflows/release_docker.yaml, .github/workflows/release_mgbench_client.yaml, .github/workflows/release_ubuntu2004.yaml, .github/workflows/stress_test_large.yaml, .github/workflows/upload_to_s3.yaml
=> Upgrade deprecated github actions

.github/workflows/release_debian10.yaml, .github/workflows/release_ubuntu2004.yaml, .github/workflows/stress_test_large.yaml
Update timeouts for release CI
---
=> Update release CI job timeouts

libs/setup.sh, src/storage/v2/delta.hpp, src/storage/v2/disk/storage.cpp, src/storage/v2/durability/wal.cpp, src/storage/v2/edge_accessor.cpp, src/storage/v2/id_types.hpp, src/storage/v2/indices/indices_utils.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/inmemory/unique_constraints.cpp, src/storage/v2/mvcc.hpp, src/storage/v2/property_value.hpp, src/storage/v2/transaction.hpp, src/storage/v2/vertex_info_helpers.hpp, src/utils/disk_utils.hpp, src/utils/string.hpp, tests/unit/storage_v2_property_store.cpp, tests/unit/storage_v2_wal_file.cpp
- Reduce delta from 104B to 80B
- Hold and pass them around as in a deque
- Detect and deleted deltas within commit if safe to do so
relates to #1685
| Before        | After           | 
| ------------- |-------------| 
| ![Before](https://github.com/memgraph/memgraph/assets/67672/7d3107ce-fb1c-4960-b7f2-4da3b389387d)      | ![After](https://github.com/memgraph/memgraph/assets/67672/0a88e9b0-db35-4a31-952e-b49b3ceedf16) |
=> Improve memory handling of Deltas

src/query/frontend/semantic/symbol_generator.cpp, tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
Having an unbound variable inside a subquery causes a crash due to checking all scopes instead of only the local (last) one in case of a call subquery.
closes #1636 
Unbound variable inside a subquery no longer causes a crash.
=> Fix unbound variable causing crash inside subquery

.github/workflows/release_debian10.yaml, .github/workflows/release_ubuntu2004.yaml, .github/workflows/stress_test_large.yaml
This PR will modify  `release_debian10.yaml`, `release_ubuntu2004.yaml` and `stress_test_large.yaml` workflows in the following ways:
- introduce concurrency groups and add concurrency rules
- trigger release builds on pushes to release branches
- trigger all 3 workflows on pushed RC tags `vX.Y.Z-rcN`
---
=> Add rules for rc workflows

.github/workflows/release_debian10.yaml, .github/workflows/release_ubuntu2004.yaml
=> Turn e2e tests back on for release build workflows

libs/.gitignore, libs/nuraft2.1.0.patch, libs/setup.sh
NOTE: Required to be able to use toolchain-v5
It seems better compared to using the latest commit from https://github.com/eBay/NuRaft/tree/master (because versioning is not clear -> who knows what will break memgraph's code).
=> Patch NuRaft for clang-17 compilation

src/query/plan/operator.cpp, tests/gql_behave/tests/memgraph_V1/features/match.feature, tests/gql_behave/tests/memgraph_V1/features/memgraph_bfs.feature, tests/gql_behave/tests/memgraph_V1/features/memgraph_wshortest.feature, tests/gql_behave/tests/memgraph_V1/graphs/graph_edges.cypher
=> In BFS expansion filter by path we should shrink path to restore state prior to expansion only if the path was changed.

.github/workflows/release_build_test.yaml
Minor fix, the push to s3 action doesn't work on macOS
---
=> Add jobs for pushing ARM packages

src/memory/global_memory_control.cpp, src/mg_import_csv.cpp, src/query/procedure/mg_procedure_impl.cpp, src/storage/v2/delta.hpp, src/utils/disk_utils.hpp, src/utils/string.hpp
Make special structure for `old_disk_key`. `std::optional<std::string>` was 40B, which is the largest member of out action union. Replaced with 8B, structure.
This makes largest member now `vertex_edge` at 24B, this means Delta is now only 56B.
🥳🎉 Now less than a cacheline 🎊✨
For reference you can compare with the last Delta improvement #1688 
Query used: `FOREACH (i in range(1, 3000000) | CREATE (:Label1:Label2:Label3:Label4:Label5:Label6));`
=> Compact Delta 80B -> 56B

src/utils/uuid.hpp
Older libuuid did not have this macro, we need to publish for older distro with older libs.
=> Do not use UUID_STR_LEN

src/coordination/CMakeLists.txt, src/coordination/coordinator_config.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/coordination/coordinator_config.hpp, src/coordination/include/nuraft/coordinator_state_machine.hpp, src/coordination/include/nuraft/raft_log_action.hpp, src/replication_coordination_glue/mode.hpp, tests/unit/CMakeLists.txt, tests/unit/raft_log_serialization.cpp
Use JSON library instead of manual (de)serialization for raft log operations
=> Improve raft log serialization

src/query/frontend/ast/ast.hpp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/frontend/opencypher/grammar/MemgraphCypher.g4, src/query/interpreter.cpp, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/not_replicate_from_old_main.py, tests/e2e/high_availability/single_coordinator.py, tests/e2e/high_availability/workloads.yaml, tests/unit/cypher_main_visitor.cpp
Change registration queries to support config map syntax.
Example:
```
"REGISTER INSTANCE instance_1 WITH CONFIG {'bolt_server': '127.0.0.1:7688', 'management_server': '127.0.0.1:10011', 'replication_server': '127.0.0.1:10001'};",
```
```
"ADD COORDINATOR 1 WITH CONFIG {'bolt_server': '127.0.0.1:7690', 'coordinator_server': '127.0.0.1:10111'}",
```
=> Improve registration queries

release/package/mgbuild.sh
Fix for this [issue](https://github.com/memgraph/memgraph/actions/runs/8289405797/job/22685772108?pr=1603#step:4:2005)
Cargo is installed inside mgbuild container but can't be found. 
`PATH` environment variable inside the container contains `/home/mg/.cargo/bin`
However, when running `docker exec container bash -c "cargo"`, the `PATH` environment variable doesn't contain `/home/mg/.cargo/bin`
Read more on this [here](https://serverfault.com/questions/816709/why-are-environment-variables-different-with-bash-c)
The fix is to add `source /home/mg/.cargo/env` before `cmake` and `make` commands
- Add source /home/mg/.cargo/env before cmak` and make commands in mgbuild.sh
=> Fix cargo not found when buidling in mgbuild container

.github/workflows/diff.yaml
Running `diff` on push to `master` and being able to run `diff` manually was mistakenly disabled in this [commit](https://github.com/memgraph/memgraph/commit/b0cdcd3483ab7e088d338752fdac64482d40af1a)
This PR will revert those changes.
- Enable running diff manually and on push to master
=> Make diff run on push to master again

tests/jepsen/run.sh
This is a pretty brutish fix, but it works!
This PR will add a loop to check if all nodes started correctly and restart if any failed. The loop will do 5 iterations.
- add a loop to check if all nodes started correctly and restart if any failed
=> Fix jepsen nodes not starting up healthy

src/coordination/coordinator_client.cpp, src/coordination/coordinator_cluster_state.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/coordination/coordinator_client.hpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/coordinator_rpc.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/include/coordination/register_main_replica_coordinator_status.hpp, src/coordination/include/coordination/replication_instance.hpp, src/coordination/include/nuraft/coordinator_cluster_state.hpp, src/coordination/include/nuraft/coordinator_state_machine.hpp, src/coordination/include/nuraft/raft_log_action.hpp, src/coordination/raft_state.cpp, src/coordination/replication_instance.cpp, src/query/interpreter.cpp, src/replication_coordination_glue/common.hpp, src/replication_coordination_glue/role.hpp, tests/drivers/run.sh, tests/drivers/run_cluster.sh, tests/e2e/high_availability/distributed_coords.py
This PR introduces a force reset of cluster state to state that was before the operation started.
_Implemented_
_Enable force reset to work on:_
_Additional work:_
Add force reset of cluster in HA
- When the action doesn't succeed atomically cluster enters a force reset state. 
- For instances that are down introduce demote to replica callback.
- Use unique lock and unlock raft log to change state
- Add action for instance which needs to be demoted to replica
=> HA: Add force reset of cluster

.github/workflows/release_build_test.yaml
This PR will add the ability to build and push RC ARM builds to S3.
- add job to package and upload successful RC ARM builds to S3
=> Package and upload RC builds for ARM

.github/workflows/release_docker.yaml
Update release docker workflow to work with toolchain v5.
- download memgraph debian-12 binaries instead of debian-11
- use v5_deb.dockerfile
- 
- update release docker workflow to work with toolchain v5
=> Update release docker workflow to work with toolchain v5

.github/workflows/package_memgraph.yaml, release/package/arm-builders-v5.yml, release/package/mgbuild.sh
This PR adds `debian-11-arm` as a supported OS for building and packaging memgraph with `toolchain v5`.
This is needed in order to push the `1.15.1` release on `mage`
=> Add debian-11-arm build with toolchain v5

libs/setup.sh
This should be a fix for the problem where mgcxx deps suddenly change (memgraph's build randomly fails).
`Cargo.lock` added (freeze of dependencies) under https://github.com/memgraph/mgcxx/pull/9 (v0.0.6)
=> Freeze mgcxx deps properly

src/coordination/coordinator_cluster_state.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/include/nuraft/coordinator_cluster_state.hpp, src/coordination/include/nuraft/coordinator_state_machine.hpp, src/coordination/include/nuraft/coordinator_state_manager.hpp, src/coordination/include/nuraft/raft_log_action.hpp, src/coordination/raft_state.cpp, tests/e2e/high_availability/coord_cluster_registration.py, tests/unit/coordinator_cluster_state.cpp, tests/unit/coordinator_instance.cpp, tests/unit/coordinator_state_machine.cpp, tests/unit/raft_state.cpp
Coordinator aren't explicitly saved in raft log. They are auto-managed by using `srv_config` from NuRaft. Aux field is used for saving more info about coordinators.
- **Fix managing coordinators in HA**
=> Fix managing coordinators in HA

src/query/frontend/ast/cypher_main_visitor.cpp, src/query/frontend/ast/cypher_main_visitor.hpp, src/query/frontend/opencypher/grammar/Cypher.g4, tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature, tests/gql_behave/tests/memgraph_V1_on_disk/features/memgraph_exists.feature, tests/unit/cypher_main_visitor.cpp
Allowing only a single relation (`()-[]->()`) as input.
This will create better error messages. 
NOTE: This will not allow any function called exists to ever be called.
closes https://github.com/memgraph/memgraph/issues/1564
=> Better EXISTS handling

src/query/frontend/ast/ast.hpp, src/query/frontend/ast/cypher_main_visitor.cpp, tests/gql_behave/tests/memgraph_V1/features/create.feature
We already allow a write query to omit RETURN.
However, queries like
```
CREATE (a:A {id: 1});
MATCH (a:A {id: 1})
WITH a
UNWIND range(1,1000) as id
CALL {
WITH id, a
CREATE (b:B {prop: 1})
CREATE (b)-[:IN]->(z)
};
```
would be categorized as read, because the subquery's (query under CALL) read/write status would be ignored.
Now a query has updates if any one of the subqueries has updates.
closes https://github.com/memgraph/memgraph/issues/1544
=> Allow query with a write subquery to omit RETURN

tests/code_analysis/clang_tidy.sh, tools/github/clang-tidy/grep_error_lines.sh
This diff fixes clang tidy to report errors again.
- Fixes clang tidy
=> Fix clang tidy

.github/workflows/diff_release.yaml, tests/unit/coordinator_instance.cpp
HA unit tests had the same port defined for the `nuRaft` server for `coordinator_instance`.cpp and `coordinator_raft_state.cpp`, which is `40112`
- Fix same port bug
- Internal, no docs
- Internal, no docs
=> Fix same port bug on HA unit tests

.sonarcloud.properties
As suggested by phind.com AI
Change the SonarCloud configuration to exclude the tests directory. This should reduce the noise and distraction.
=> Exclude tests/**/* directory and files from the static analysis by SonarCloud

libs/setup.sh
nuRaft needs also `git fetch` to checkout to specific older commits. This fixes the issue @gvolfing experienced with the `./init` script. Link to slack thread here: https://memgraph.slack.com/archives/CS5827FK3/p1713266466780389
- Fix nuRaft init script issue
- No docs, internal
- *No docs, internal
=> Fix nuRaft init script issue

.sonarcloud.properties, src/flags/all.hpp, src/memgraph.cpp
This diff adds exit on construction error for coordinator state in case raft launcher throws an error
- Add exit on coordinator state ctor error
=> Add exit on coordinator state ctor error

src/query/plan/rewrite/index_lookup.hpp, tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
Fix index lookup rewrite in case of pattern comprehension
=> Fix index lookup rewrite in case of pattern comprehension

src/coordination/coordinator_communication_config.cpp, src/coordination/coordinator_instance.cpp, src/coordination/include/coordination/coordinator_communication_config.hpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/instance_status.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/include/coordination/replication_instance_connector.hpp, src/coordination/raft_state.cpp, src/coordination/replication_instance_connector.cpp, src/query/interpreter.cpp, tests/e2e/high_availability/common.py, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/not_replicate_from_old_main.py, tests/e2e/high_availability/single_coordinator.py
`SHOW INSTANCES` now also returns the time passed in ms since the last successful response from coordinators and replication instances. When ran by followers, return value will be 0.
- **Add last_succ_resp_ms to SHOW INSTANCES output**
- **Users can now see elapsed time in milliseconds since the last successful response from instances to the leader's health ping.**
- **https://github.com/memgraph/documentation/pull/729**
=> Add last_succ_resp_ms to SHOW INSTANCES output

src/dbms/inmemory/replication_handlers.cpp, src/storage/v2/durability/serialization.hpp, src/storage/v2/inmemory/replication/recovery.cpp, src/storage/v2/replication/replication_client.cpp, src/utils/file.hpp, tests/jepsen/src/jepsen/memgraph/bank.clj
Send only durable part of the buffer to replicas during recovery
Better checker for jepsen test for easier debugging.
Improved logs to more easily reason about applying deltas during recovery.
Before this PR, even with `fsync` set to 1, replicas could get non-durable data from main. If main would die and get back, replica could be in more advanced state than main = issue.
- **Replica only durable commits to replicas during recovery**
- **During recovery process, when replicas are behind main, they will receive only commits which are already fsynced on main.**
=> Replicate only durable commits to replicas during recovery

src/communication/buffer.cpp, src/communication/buffer.hpp, src/rpc/protocol.cpp, src/storage/v2/inmemory/storage.cpp
On REPLICA the commit timestamp is calculated in an interesting way. This is for reasons related to durability based on the timestamp. The problem is that some timestamps can be skipped, and hence never used on the replica side and hence never finalised. This would mean the commit log would provide incorrect information to GC about what the oldest active timestamp is. Causing GC not to clear away the Deltas being made.
Fix is to make all skipped timestamps to be marked as finalised.
Another memory related issue was the RPC session buffer retained the size of its high watermark. Post Session::Execute we now limit the buffer back to a max of 4MiB.
fixes: #1995
- **Bugfix: Replica now handles skipped transactions**
- **Replica now …
=> Bugfix: Replica now handles skipped transactions

tests/e2e/high_availability/distributed_coords.py, tests/e2e/mg_utils.py
In some tests we were incorrectly assuming which instance will become new in situations when both current main and current leader of the cluster died.
- **Improve testing output of `SHOW INSTANCES`**
=> Improve testing output of `SHOW INSTANCES` 

tests/e2e/high_availability/distributed_coords.py
This diff fixes an issue with running show replicas on REPLICA instead of the correct MAIN
- Fix running SHOW REPLICAS; on main
=> Fix: Running show replicas on REPLICA in e2e test

src/query/procedure/mg_procedure_impl.cpp
This PR fixes type conversion by adding a missing break statement.
> Fix missing break statement in type conversion
=> Fix missing break statement in type conversion

.github/workflows/release_build_test.yaml
Environment variables defined at the workflow level cannot be passed to called reusable workflows.
This PR removes the environment variables and replaces their references with literal strings.
=> Fix release build test workflow syntax

tests/unit/network_endpoint.cpp
Fixes DNS resolution to ipv6 in case of test. DNS can be resolved to ipv6 in case of localhost also
- Fix DNS resolution to ipv6 in case of test
- Not needed
- Not needed
=> Fix: ipv6 resolution in dns test

src/flags/replication.cpp, tests/e2e/configuration/default_config.py
Flag --replication_restore_state_on_startup is now by default set to true.
- **Set --replication-restore-state-at-startup to true by default**
- **Flag --replication_restore_state_on_startup is now by default set to true.**
- **https://github.com/memgraph/documentation/pull/762**
=> Set --replication-restore-state-at-startup to true by default

.github/workflows/diff_jepsen.yaml, src/dbms/inmemory/replication_handlers.cpp, src/dbms/inmemory/replication_handlers.hpp, src/replication_handler/replication_handler.cpp, src/storage/v2/CMakeLists.txt, src/storage/v2/disk/storage.cpp, src/storage/v2/disk/storage.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/replication/replication_storage_state.cpp, src/storage/v2/replication/replication_storage_state.hpp, tests/CMakeLists.txt
Jepsen found a few bugs in replication, this PR fixes two of them.
When the replica recovered completely, on the next txn replication, it expected `replica_stream_` to be already destroyed. There MG_ASSERT failed. Now, the replica stream is created as a local variable for transactions.
Another bug is related to the MVCC of the replica. Because REPLICA’s transaction timestamps are contingent on MAIN’s timestamps, resulting in the transaction timestamp counter (used for obtaining the start transaction ID, and commit timestamp ID) staying the same when the READ transaction started, MVCC guarantees were broken. Any time the WRITE transaction would commit before the READ transaction would finish, GC could incorrectly unlink deltas as the WRITE transaction would mark its start timestamp as …
=> Fix: MVCC design on replica and replica stream isolation

src/coordination/coordinator_instance.cpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/raft_state.cpp, tests/unit/coordinator_instance.cpp
Fixes bug in NuRaft by removing raft_launcher and instead manually setting up raft_server, rpc_listener...
We consider raft server successfully created once it is behaving as a leader.
- **Fix NuRaft launcher race condition when creating raft server**
- **Fix NuRaft launcher race condition when creating raft server**
=> Fix NuRaft launcher race condition when creating raft server

release/package/mgbuild.sh
This PR fixes permission issues when packaging memgraph by running the process as `root`.
[Example](https://github.com/memgraph/memgraph/actions/runs/9158067144/job/25212873759#step:8:45)
=> Fix arm packaging by running as root

src/communication/http/server.hpp, src/communication/websocket/server.hpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_server.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/include/coordination/coordinator_handlers.hpp, src/coordination/include/coordination/coordinator_slk.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/raft_state.cpp, src/io/network/addrinfo.cpp, src/io/network/endpoint.cpp, src/io/network/endpoint.hpp, src/io/network/socket.cpp, src/query/interpreter.cpp, src/query/replication_query_handler.hpp, src/replication/replication_server.cpp, src/replication/state.cpp, src/replication_handler/replication_handler.cpp, tests/e2e/replication/common.hpp, tests/e2e/replication/indices.cpp, tests/unit/network_endpoint.cpp, tests/unit/storage_v2_replication.cpp
`SHOW INSTANCES` now returns non-resolved IP address = DNS entry.
DNS can be used when adding coordinator instance.
You can use DNS for registering instances, DNS is resolved to IP every time when connecting sockets. Socket is connected when streaming data using RPC communication.
Replication is untouched and will be handled separately.
Output in Kubernetes cluster:
- **Improve HA networking**
- **`SHOW INSTANCES` now returns non-resolved IP addresses when using DNS in HA cluster.**
- **In HA cluster, `DNS` is being resolved every time when streaming data using RPC connections. This means that Kubernetes Pod can get restarted without …
=> Improve HA networking

.github/workflows/diff_jepsen.yaml
Refreshing Jepsen cluster can fail because of GitHub issues, move it earlier so we don't have to build Memgraph before.
- **Refresh Jepsen cluster before building Memgraph**
=> Refresh Jepsen cluster -> Memgraph build

src/coordination/CMakeLists.txt, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_log_store.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/include/coordination/coordinator_communication_config.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/include/nuraft/coordinator_state_machine.hpp, src/coordination/include/nuraft/coordinator_state_manager.hpp, src/coordination/include/nuraft/log_level.hpp, src/coordination/include/nuraft/logger.hpp, src/coordination/include/nuraft/logger_wrapper.hpp, src/coordination/logger.cpp, src/coordination/logger_wrapper.cpp, src/coordination/raft_state.cpp, src/flags/coordination.cpp, src/flags/coordination.hpp, src/memgraph.cpp, tests/e2e/configuration/default_config.py, tests/unit/coordinator_state_manager.cpp
- Added logger object for NuRaft logs which serves as adapter between spdlog and NuRaft logger :heavy_check_mark: 
- Logger object is shared between state machine, state manager and raft server :heavy_check_mark: 
- Existing logs from state machine and state manager are moved under this new logger :heavy_check_mark: 
- `CoordinatorInstanceInitConfig` extended with `nuraft_log_file` :heavy_check_mark: 
- if arg not provided, logger will still be created but without any sinks, effectively creating no-op logger :heavy_check_mark: 
- Added `nuraft_log_file` flag :heavy_check_mark: 
```
[2024-05-31 13:43:06.386] [NuRaft] [info] [asio_service.cxx:771] Raft ASIO listener initiated, UNSECURED
[2024-05-31 13:43:06.386] [NuRaft] [trace] [coordinator_state_machine.cpp:216] Getting last committed …
```
=> Add NuRaft logs

tests/manual/test_isolation_level.py
- asserts are changed to return statements in order to allow executing tests on lower isolation levels
- logic of g1b test has changed a bit in a way to allow `READ_COMMITTED` test to pass -> With `READ_COMMITTED` g1b = intermediate reads should pass
- Added test for testing gpred_a -> see definition in Adya's PhD
- Added test for gpred_b -> see definition in Adya's PhD
- **Improve txn isolation level tests**
- **https://github.com/memgraph/documentation/pull/807**
=> Improve txn isolation level tests

src/memgraph.cpp
- Instance down timeout config option must be greater than or equal to instance health check frequency config option. If not, abort starting Memgraph coordinator instance.
- **Fail starting coordinator with invalid config options for health pings**
- **Coordinator won't be started if `--instance-down-timeout-sec` option is smaller than `--instance-health-check-frequency-sec`.**
- **https://github.com/memgraph/documentation/pull/833**
=> Fail starting coordinator with invalid config options for health pings

tests/jepsen/0-3-5.patch, tests/jepsen/run.sh
Replace openjdk-21-jdk-headless with openjdk-22-jdk-headless in Dockerfile for control node
Jepsen startup is failing because it tries to apt-get openjdk-21-jdk-headless which is classified as unstable and so it cannot be found.
=> Fix Jepsen setup failing because of openjdk-21-jdk-headless

tests/jepsen/resources/cluster.edn
Jepsen HA test is now using one port as management port, one port as coordinator port, one port as replication port on all instances. Seems logical as this is what users will usually do/can do in their deployments.
- **Update Jepsen ports**
=> Update Jepsen ports

.github/workflows/diff.yaml, .github/workflows/diff_coverage.yaml, release/package/mgbuild.sh
Clang tidy now runs in parallel with coverage build and tests because it was taking too long.
=> Run clang tidy in parallel

src/flags/experimental.cpp, src/flags/experimental.hpp, src/flags/log_level.cpp, src/memgraph.cpp
1. Validate experimental flag values
2. Log which experimental features are enabled
- **Improve experimental-enabled flag**
- **Experimental-enabled flag is now validated.**
- **Users can see logs which experimental features are enabled.**
=> Experimental-enabled flag improvements

CMakeLists.txt, release/package/mgbuild.sh
`generate_opencypher_parser` and `mgcxx-proj` produce headers that clang-tidy will need to use for its analysis. Made a custom target for them and ensured `mgbuild.sh` will build them when needed.
=> Ensure headers exist for clang-tidy analysis

src/flags/coord_flag_env_handler.cpp, src/flags/coord_flag_env_handler.hpp, src/memgraph.cpp, tests/unit/CMakeLists.txt, tests/unit/coordinator_cluster_state.cpp, tests/unit/coordinator_env_flag_handler.cpp
Add NuRaft log file env variables
Refactored CoordinationSetup flag vs. env.
Added test
- **Add NuRaft log file env variable**
- @kgolubic NuRaft Logger is added in 2.18 so this is not yet released. This PR contains some improvements to that so I think no need for new release note, I think we should just extend release note from https://github.com/memgraph/memgraph/pull/2084 by adding: You can also use environment variable `MEMGRAPH_NURAFT_LOG_FILE` for setting path to NuRaft logs.
- **https://github.com/memgraph/documentation/pull/848**
=> Add NuRaft log file env variable

src/coordination/coordinator_instance.cpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/raft_state.cpp, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/not_replicate_from_old_main.py, tests/e2e/high_availability/single_coordinator.py, tests/e2e/mg_utils.py, tests/jepsen/src/jepsen/memgraph/habank.clj, tests/jepsen/test/jepsen/memgraph/memgraph_test.clj
In the output of show instances; users can now see which coordinator is the leader and which coordinators are followers. Before, coordinator role was always returned for all coordinator instances.
Expected result of `show instances`:
```
+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
| name               | bolt_server        | coordinator_server | management_server  | health             | role               | last_succ_resp_ms  |
+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+
| "coordinator_1"    | "0.0.0.0:7687"     | "0.0.0.0:10111"    | ""                 | "up"               | …
```
=> Add leader/follower role in show instances output

.github/workflows/diff.yaml, tools/diff_setup.py
This PR fixes CI being stalled when updating files previously defined under paths-ignore in diff.yaml
=> Move paths-ignore logic from diff.yaml to tools/diff_setup.py

src/coordination/coordinator_communication_config.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/include/coordination/coordinator_communication_config.hpp, src/coordination/raft_state.cpp, src/flags/coord_flag_env_handler.cpp, src/flags/coord_flag_env_handler.hpp, src/flags/coordination.cpp, src/flags/coordination.hpp, src/memgraph.cpp, src/query/interpreter.cpp, tests/drivers/run_cluster.sh, tests/e2e/configuration/default_config.py, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/manual_setting_replicas.py, tests/e2e/high_availability/not_replicate_from_old_main.py, tests/e2e/high_availability/single_coordinator.py, tests/e2e/high_availability/workloads.yaml, tests/jepsen/src/jepsen/memgraph/support.clj, tests/unit/coordinator_env_flag_handler.cpp, tests/unit/coordinator_instance.cpp, tests/unit/coordinator_raft_state.cpp, tests/unit/coordinator_state_machine.cpp, tests/unit/coordinator_state_manager.cpp, tests/unit/coordinator_utils.cpp
Configuration flag `--coordinator-hostname` is added which is used to fix the issue of having 0.0.0.0 in the output of `show instances` on the 1st leader. The flag has its environment variable equivalent in `MEMGRAPH_COORDINATOR_HOSTNAME`. The flag is used solely for the output of `show instances`, from the functional standpoint all stayed the same. High availability e2e tests are changed to use DNS (localhost instead of explicit 127.0.0.1) for consistency reasons. This change is breaking because now all coordinator instances need to provide a configuration option coordinator hostname.
The following output can be expected when setting `--coordinator-hostname=localhost` (no data instances):
memgraph> show instances;
+--------------------+--------------------+--------------------+----------- …
=> Add coordinator hostname config

src/query/plan/rewrite/index_lookup.hpp, tests/e2e/query_planning/CMakeLists.txt, tests/e2e/query_planning/query_planning_cartesian.py
Bugfix: Planner wrongly assumes Filter will always be right after an EdgeUniquenessFilter.
This in turn cases some plans to miss a Cartesian to Join swap.
=> Filter embedding after Cartesian operator

release/docker/package_docker
This PR fixes the name of resulting docker image for memgraph (memgraph:tag --> memgraph/memgraph:tag)
=> Fix name of docker image from memgraph to memgraph/memgraph

.github/workflows/reusable_package.yaml, libs/setup.sh
This PR fixes our arm machine bottleneck when building artifacts. When building for arm the builds will now be run on github hosted large ubuntu arm runner. Additionally this PR also adds the option to bypass the cache when setting up libs.
=> Run arm builds on github large runner

src/rpc/version.hpp, src/storage/v2/inmemory/storage.cpp, tests/e2e/replication/indices.cpp, tests/e2e/replication/workloads.yaml
Fix replication bug around auto index creation. Before it was not possible to have data and metadata deltas in same transaction. Now because of auto index creation it is, hence we need to ensure metadata deltas are sent first to make sure REPLICA uses unique access.
=> Unique memory access for replicating auto-created indices

tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/workloads.yaml, tests/e2e/memgraph.py
The only e2e HA test which used workloads.yaml for cluster definition. Moved this into coordinator.py file to be consistent with other tests.
=> Improve coordinator.py test

.github/workflows/diff.yaml
Jepsen tests are experiencing an issue due to `opendjk-22`, until the issue is fixed jepsen tests are disabled in CI.
=> Disable jepsen tests

.github/workflows/diff.yaml, tests/jepsen/0-3-5.patch
Building jepsen images has been experiencing issues due to dependency to latest libc6. This PR fixes that and brings back jepsen tests.
=> Fix jepsen cluster build

src/communication/bolt/v1/states/handlers.hpp
Also covers the case of if we accidentally use it. We should be checking MemoryErrorStatus upon nullptr, and then throwing typically OutOfMemoryException not std::bad_alloc.
=> Handle bad_alloc being thrown by 3rd party code

.github/workflows/package_memgraph.yaml, .github/workflows/reusable_package.yaml
This PR updates the package_memgraph.yaml workflow in the following ways:
- updates the description for s3_dest_dir input because it was deprecated
- moves step to validate S3 dest dir path to start of a job to fail fast
=> Update package_memgraph workflow

tests/jepsen/src/jepsen/memgraph/core.clj, tests/jepsen/src/jepsen/memgraph/habank.clj, tests/jepsen/src/jepsen/memgraph/utils.clj, tests/jepsen/test/jepsen/memgraph/memgraph_test.clj
Exception was thrown on coordinator state construction is now added to log checkers. Random number of coordinators are killed when nemesis turns on, before at most one coordinator was killed. Durability in HA made this possible.
=> Add killing of random number of coordinator nodes

src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state_manager.cpp, src/io/network/endpoint.cpp, tests/jepsen/src/jepsen/memgraph/support.clj
Management server on coordinator instances will be started at 0.0.0.0. Fix for K8 deployment.
=> Fix creation of management server in coordinators

.github/workflows/check_flakiness.yaml
This PR removes the benchmark job from the check_flakiness.yaml workflow.
=> Remove benchmark job from flakiness checker

src/storage/v2/property_store.cpp
The internal reader was not reading enough bytes. This caused problems when needing to consume the next item and the reader was in the wrong location.
For example:
`CREATE (n {prop:[X::A, ""]}) RETURN propertySize(n, 'prop');`
Use to give:
```
+-------------------------+
| propertySize(n, 'prop') |
+-------------------------+
| 0                       |
+-------------------------+
```
Now correctly gives:
```
+-------------------------+
| propertySize(n, 'prop') |
+-------------------------+
| 8                       |
+-------------------------+
```
=> Fix DecodePropertyValueSize for enums

tests/jepsen/src/jepsen/memgraph/habank.clj
- Avoid `NullPointerException` by checking if nil was returned from get-all-accounts. 
- Create all data as part of one txn to avoid partial data initialization.
- `accounts-exist` and `insert-data` use external session or txn
=> Fix insertion of data and NullPointerException

src/coordination/raft_state.cpp
Coordinators didn't yield leadership although they should according to the leadership_expiry_ flag. This diff fixes the issue nuRaft has with leadership expiry, where leadership_expiry is not respected as a limit, but instead, `heart_beat_interval_*raft_server::raft_limits_.response_limit_` is used as expiry for nodes to deem as unhealthy.
=> Change nuRAFT response limit to respect leadership expiry

tests/jepsen/src/jepsen/memgraph/support.clj
Fixes issue with fetching libpython3.11 packages when running Jepsen tests.
```
STDERR:
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.11/libpython3.11_3.11.2-6_amd64.deb  404  Not Found [IP: 146.75.2.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.11/libpython3.11-dev_3.11.2-6_amd64.deb  404  Not Found [IP: 146.75.2.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/python3.11/python3.11-dev_3.11.2-6_amd64.deb  404  Not Found [IP: 146.75.2.132 80]
```
=> Fix Jepsen upgrade

.github/workflows/diff.yaml
This PR temporarily disables benchmarks on diff workflow runs because we are experiencing issues with the mgbench depoyment. After the issue is fixed, benchmarks will be reenabled.
=> Temporarily disable benchmarks on diff workflow runs

src/audit/log.cpp, src/communication/bolt/v1/encoder/base_encoder.hpp, src/flags/run_time_configurable.cpp, src/flags/run_time_configurable.hpp, src/glue/communication.cpp, src/query/interpret/awesome_memgraph_functions.cpp, src/query/interpret/eval.hpp, src/query/procedure/mg_procedure_impl.cpp, src/query/procedure/py_module.cpp, src/query/typed_value.cpp, src/storage/v2/temporal.hpp, src/utils/CMakeLists.txt, src/utils/temporal.cpp, src/utils/temporal.hpp, tests/e2e/configuration/default_config.py, tests/e2e/temporal_types/roundtrip.cpp, tests/unit/CMakeLists.txt, tests/unit/bolt_decoder.cpp, tests/unit/bolt_encoder.cpp, tests/unit/cpp_api.cpp, tests/unit/query_dump.cpp, tests/unit/query_expression_evaluator.cpp, tests/unit/timezone_handler.hpp, tests/unit/utils_temporal.cpp
LocalDateTime now considers set database timezone
Bugfix: LocalDateTime assumed input date-time was always UTC
New command-line argument and database setting `timezone`, which is used for LocalDateTime conversion
=> LocalDateTime does not convert user date to UTC properly

src/utils/tmp_dir.hpp, tests/unit/timezone_handler.hpp
HandleTimezone was introduced with LocalDateTime update. 
It initialized a RocksDB for a the global settings. Its path was fixed and so would conflict while multiple tests were reading/writing to the same RocksDB.
=> Bugfix: HandleTimezone reusing same path in unit tests

src/replication_handler/replication_handler.cpp
Were missing data_info in community due to a bad database name check.
=> Bugfix: SHOW REPLICAS returning empty map for data_info in community edition

src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, tests/e2e/garbage_collection/CMakeLists.txt, tests/e2e/garbage_collection/common.py, tests/e2e/garbage_collection/gc_on_obsolete_indexes.py, tests/e2e/garbage_collection/workloads.yaml
Instead of deleting vertices or edges and removing obsolete index entries in `FastDiscardOfDeltas`, hand over that work to the GC.
Closes #1955 , closes #2226
=> Fix FastDiscardOfDeltas

src/auth/models.cpp, src/auth/models.hpp, src/glue/auth_handler.cpp, tests/unit/auth.cpp
This change will revert the breaking change from PR #2166
Now a password-less user can login using any string, but must define empty string when trying to change it.
=> Splitting the logic for authentication and password change

src/storage/v2/property_store.cpp, src/utils/memory.cpp, src/utils/skip_list.hpp, tests/e2e/interactive_mg_runner.py, tests/e2e/memgraph.py, tests/gql_behave/continuous_integration, tests/unit/utils_memory.cpp
Recent property store changes added a different correctness invariant that the existing on disk code was unaware of. 
Also minor changes:
- gql_behave test to pass their storage mode to the run command
- memory alignment fixes to avoid potential UB (+ test fix)
- better diagnostic in e2e/interactive_mg_runner.py
=> [BUGFIX] incorrect size representations properties when using on disk

.github/workflows/diff.yaml
The bench-graph deployment has been fixed, so now benchmarks are back in action in CI.
=> Bring benchmarks back on in CI

src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state.cpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/coordinator_state.hpp, src/coordination/include/coordination/register_main_replica_coordinator_status.hpp, src/coordination/include/coordination/replication_instance_connector.hpp, src/coordination/raft_state.cpp, src/coordination/replication_instance_connector.cpp, src/dbms/coordinator_handler.cpp, src/dbms/coordinator_handler.hpp, src/query/interpreter.cpp, src/query/metadata.cpp, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/distributed_coords.py
When becoming the leader in case everything seems okay we don't do any checks. But the coordinator can become leader and only do commits of older logs afterwards (when we exit become leader callback), meaning we could miss logs which put us in unhealthy state.
To fix that problem, we will alter become leader callback to always do check of whole cluster and set it in healthy state in the beginning.
=> Execute state check on becoming leader

src/io/network/endpoint.cpp
Endpoint resolution was an issue for failing the `coordinator.py` test. The problem is that we parsed both for ipv4 and ipv6, and `getaddrinfo` func could prefer ipv6 over ipv4, which would result in a problem when sending RPC message.
=> Order IP version resolution in endpoint

src/query/stream/streams.cpp
While the streams were being stopped, they were not  being destroyed, so Gatekeeper would never reach 0 and block.
=> Bugfix: Deadlock while destroying database with streams

src/storage/v2/inmemory/label_property_index.cpp, tests/unit/storage_v2_indices.cpp
Only add entry to label+property indexes when label matches.
=> Correct label+property index entry insertion

.github/workflows/diff_jepsen.yaml, tests/jepsen/run.sh
Processing results is now done in separate github tasks to avoid the situation where test fails and we are left without logs.
=> Separate processing jepsen results from the execution

tests/e2e/high_availability/common.py, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/manual_setting_replicas.py, tests/e2e/high_availability/not_replicate_from_old_main.py, tests/e2e/high_availability/single_coordinator.py
Coordinators instances in some tests were started without data directory flag causing problems on restarts.
=> Fix communication restarts

src/communication/bolt/v1/states/handlers.hpp, src/utils/logging.hpp, tests/e2e/memgraph.py
The logging code for every session had an expensive call, even when no logging was being done.
=> Fix perf regression

src/storage/v2/delta.hpp, src/storage/v2/edge_accessor.cpp, src/storage/v2/indices/edge_type_property_index.hpp, src/storage/v2/indices/indices.cpp, src/storage/v2/indices/indices.hpp, src/storage/v2/indices/label_property_index.hpp, src/storage/v2/inmemory/edge_type_index.cpp, src/storage/v2/inmemory/edge_type_index.hpp, src/storage/v2/inmemory/edge_type_property_index.cpp, src/storage/v2/inmemory/edge_type_property_index.hpp, src/storage/v2/inmemory/storage.cpp
There were issues around cleanup of the edge index when Abort was called. Potentially leading to a segfault. We added code to perform correct cleanup during Abort.
=> Fix Abort() on Edge Index

src/storage/v2/durability/snapshot.cpp, src/storage/v2/durability/version.hpp
In 2.19 we prematurely bumped the version unnecessarily. Hence 18 and 19 snapshot load versions are one and the same. Bump to 20 to distinguish new snapshots from those saved with 2.19.
=> Fix durability around the point index

.github/workflows/diff_release.yaml, release/package/mgbuild.sh, tests/CMakeLists.txt, tests/e2e/high_availability/common.py, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/manual_setting_replicas.py, tests/e2e/high_availability/not_replicate_from_old_main.py, tests/e2e/high_availability/single_coordinator.py, tests/e2e/interactive_mg_runner.py, tests/e2e/memgraph.py, tests/e2e/replication/common.py, tests/e2e/replication/replicate_enum.py, tests/e2e/replication/replicate_spatial_feature.py, tests/e2e/replication/replication_with_property_compression_used.py, tests/e2e/replication/show_while_creating_invalid_state.py, tests/e2e/replication/ttl.py, tests/e2e/run.sh, tests/e2e/runner.py, tests/e2e/sso/common.py, tests/e2e/sso/test_sso.py, tests/e2e/system_replication/auth.py, tests/e2e/system_replication/common.py, tests/e2e/system_replication/multitenancy.py, tests/jepsen/src/jepsen/memgraph/support.clj
Logs are now saved to build/e2e/logs and copied from there. All data directories are now inside build/e2e/data/. Developer should not generate new tmp folder. If she/he wants specific data directory, it can provide the name of it (e.g replica1). If user doesn't specify data_directory field, random 8-character long folder will be created for each test inside build/e2e/data/. All tests that were using tmp directory intentionally from system_replication, high_availability and replication are changed without changing the functionality. Interactive mg runner has now clearer API. The check if port is free is now improved in a way that the interactive_mg_runner will try pinging the socket for the maximum of 10s and if after 10s the socket is not free, it will throw an error that this port is …
=> Improvements on e2e testing infrastructure

src/query/frontend/ast/cypher_main_visitor.cpp, tests/e2e/awesome_functions/CMakeLists.txt, tests/e2e/awesome_functions/id.py, tests/e2e/awesome_functions/workloads.yaml
Bug was introduced when the function name was not passed as uppercase. It would result of ScanAllById operator not being utilized.
=> Fix: ScanAllById regardless of function case

config/flags.yaml, src/flags/query.cpp, src/flags/query.hpp, src/flags/run_time_configurable.cpp, src/flags/run_time_configurable.hpp, src/query/interpreter.cpp, tests/e2e/configuration/default_config.py, tests/e2e/query_log/workloads.yaml
`--query-log-directory` set to be empty at the beginning so it is not generated inside the data directory. Also set query log directory to be a runtime flag so it can be set easily.
=> Mg query log folder fix

src/communication/bolt/v1/states/handlers.hpp, src/query/exceptions.hpp, src/query/interpreter.cpp, tests/e2e/query_modules/schema_test.py, tests/e2e/query_modules/workloads.yaml
schema.assert will now fail when ran in explicit txn, before it was crashing Memgraph. Added log when handling BEGIN message. Restored schema tests which weren't running. One test disabled since it has non-deterministic execution path.
=> Throw when schema.assert in explicit txn. Restore schema tests

.editorconfig, tests/.clang-tidy
Added .editorconfig for nvim development and updated .clang-tidy for tests folder with llvm checks.
=> Add .editorconfig for vim and .clangd clang symbols

.github/workflows/check_flakiness.yaml, .github/workflows/stress_jepsen.yaml, tests/jepsen/src/memgraph/core.clj, tests/jepsen/src/memgraph/high_availability/bank/test.clj, tests/jepsen/src/memgraph/high_availability/create/nemesis.clj, tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/high_availability/utils.clj, tests/jepsen/src/memgraph/query.clj, tests/jepsen/src/memgraph/utils.clj, tests/jepsen/test/memgraph/memgraph_test.clj
Added `hacreate` test meant to test high availability capabilities of Memgraph. Test starts 6 instances (3 data instances and 3 coordinators) and uses 2 generators to generate operations. Client generator starts one thread per instance and every 2 seconds chooses between `add-nodes` operation (run on data instances) and `show-instances` operations (run on coordinators). Operation `add-nodes` creates a batch of nodes with monotonically increasing IDs and operation `show-instances` runs `SHOW INSTANCES` query. Nemesis generator turns on every ~30'' and then randomly chooses between killing current cluster's leader and cluster's main instance. The test is considered valid if all coordinators have the same view of the cluster (`show-instances` successful), if there are no `show-instances` …
=> Add create ha test

src/rpc/client.hpp, tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/query.clj
Nemesis could kill the thread between committing a transaction and incrementing the atomic counter. This caused the issue because multiple requests for creating same range of indices could be sent when the txn got committed and we didn't register that change. The issue is solved by finding the maximum current vertex id and creating nodes in the same transaction.
=> Fix txn handling

.github/workflows/stress_jepsen.yaml, src/coordination/coordinator_instance.cpp, tests/jepsen/src/memgraph/core.clj, tests/jepsen/src/memgraph/high_availability/create/nemesis.clj, tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/utils.clj, tests/jepsen/test/memgraph/memgraph_test.clj
Test is now running for 30' since more types of failures are added. We add partitioning network in random halves, ring partitioning, isolating nodes and network failures which will corrupt, delay, duplicate and not send some TCP packages. Fixes the bug when choosing main or leader to kill when there is no main or leader in the cluster at that time. Added utility functions for calculating cumulative probabilities and choosing random number based on provided probabilities. Log checker now also checks for occurrences of the word 'critical'. Added unit tests for new functionalities.
=> Test network chaos in HA

src/dbms/inmemory/replication_handlers.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/durability.hpp, src/storage/v2/durability/snapshot.cpp, src/storage/v2/durability/snapshot.hpp, src/storage/v2/durability/wal.cpp, src/storage/v2/durability/wal.hpp, src/storage/v2/inmemory/replication/recovery.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/storage.hpp, src/utils/uuid.cpp, src/utils/uuid.hpp, tests/unit/storage_v2_durability_inmemory.cpp, tests/unit/storage_v2_wal_file.cpp
Combined storage's private and configured UUIDs. 
Bugfix: When replicating using current WAL, replica would change its uuid if the incoming WAL was MAIN's first WAL file. The correct check however is for replica to change uuid if this is REPLICA's 1st WAL. 
Bugfix: Possibility to have multiple SystemRestore executed in parallel.
=> Bugfix: Inconsistent storage UUID on replica

src/memgraph.cpp, tests/unit/query_streams.cpp, tests/unit/ttl.cpp
Streams and TTL have their own interpreters that run in the background.
These interpreters prepare queries and execute them.
When shutting down, the InterpreterContext would be destroyed before stopping streams and TTL.
There was a possibility they would be preparing queries while the IC was being destroyed.
While Pulls are protected by the abort signal, Prepare is not.
=> Bugfix: Forcing streams and tll to stop before destroying InterpreterContext

src/dbms/inmemory/replication_handlers.cpp, src/query/exceptions.hpp, src/query/interpreter.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/durability.hpp, src/storage/v2/inmemory/edge_type_index.cpp, src/storage/v2/inmemory/storage.cpp, tests/unit/storage_v2_indices.cpp
EdgeType index would assign every element as obsolete
EdgeTypeProperty index did not run GC
Allowed edge index creation even when properties on edges was false
Recovered edge indices even if properties on edges was false
EdgeType was not updated via `CreateEdgeEx`
=> Bugfix: Various issues with edge index

include/mgp.hpp, query_modules/example.cpp, tests/e2e/memory/procedures/global_memory_limit_thread_proc.cpp, tests/e2e/memory/procedures/query_memory_limit_proc_multi_thread.cpp
Will cause compilation errors when compiling modules that set `mgp::memory`.
Module implementations must use `MemoryDispatcherGuard`, otherwise instance will segfault.
=> Compilation error if module tries to set mgp::memory

src/coordination/coordinator_cluster_state.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/coordination/replication_instance_client.hpp, src/coordination/include/coordination/replication_instance_connector.hpp, src/coordination/include/nuraft/coordinator_cluster_state.hpp, src/coordination/replication_instance_client.cpp, src/coordination/replication_instance_connector.cpp, tests/unit/coordinator_cluster_state.cpp
Fixes the bug with c++ ranges and zipping when doing failover.
=> Bugfix: duplicated get instance timestamp requests

src/storage/v2/inmemory/edge_type_index.cpp, src/storage/v2/inmemory/edge_type_property_index.cpp, tests/unit/storage_v2_indices.cpp
Edge index would not remove deleted (obsolete) entries, while the GC would delete the edge object.
Edge type index was impacted, while the property type would detect that the object was deleted due to it checking the property.
=> Bugfix: Edge index doesn't remove deleted edges

.github/workflows/stress_jepsen.yaml, src/communication/server.hpp, src/coordination/data_instance_management_server_handlers.cpp, src/coordination/include/coordination/data_instance_management_server_handlers.hpp, src/dbms/dbms_handler.cpp, src/query/interpreter.cpp, src/query/replication_query_handler.hpp, src/replication/include/replication/replication_client.hpp, src/replication/include/replication/state.hpp, src/replication/replication_client.cpp, src/replication/state.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/replication_handler/replication_handler.cpp, src/rpc/client.hpp, src/storage/v2/replication/replication_storage_state.cpp, src/utils/scheduler.hpp, src/utils/thread_pool.cpp, tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/query.clj
When a coordinator sends a request for promotion or demotion, the lock on replication state is taken so that it cannot be interleaved with commit. If main became a replica and was executing write txn, the txn will be aborted. Scheduler is now stopped before thread pool in rpc client.
=> Bugfix: Deadlock when demoting data instance

src/query/interpret/awesome_memgraph_functions.cpp, tests/gql_behave/tests/memgraph_V1/features/spatial.feature
When using point function and for example providing x, y, z and crs for 2D point and vice versa Memgraph would crash (only in debug mode) due to concluding point type is 2D but CRS being 3D (and vice versa).
=> Fix crash in point function when wrong CRS is provided

.github/workflows/stress_jepsen.yaml, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_instance_connector.cpp, src/coordination/coordinator_instance_management_server_handlers.cpp, src/dbms/inmemory/replication_handlers.cpp, src/dbms/inmemory/replication_handlers.hpp, src/query/interpreter.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/rpc/client.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/rpc.cpp, src/storage/v2/replication/rpc.hpp, tests/e2e/high_availability/distributed_coords.py, tests/jepsen/src/memgraph/high_availability/create/test.clj
Time for running Jepsen stress test increased to 3h. When replica receives a WAL file and has to create a vertex, it won't crash database if such vertex already exists. Rather it will throw an exception which will abort replication transaction and return the information to main instance which sent the WAL request. Main instance will then decide whether replica needs to go to recovery or some other state. If main becomes a replica with a write txn to commit, instead of calling Abort directly, the code will throw when exception and the interpreter will then abort through that exception. Otherwise we have a problem with transaction status.
=> Handle failure in WAL replication

src/coordination/coordinator_instance.cpp, src/coordination/data_instance_management_server_handlers.cpp
The system can get in a situation in which main gets re-elected as main again and hence, new uuid gets chosen. Before, swap uuid wouldn't be sent to main which would then cause issues on the replication side.
=> Support swapping uuid on main instances

.github/workflows/stress_jepsen.yaml, src/coordination/coordinator_instance.cpp
Jepsen stress test time increased to 4h. In ShowInstancesAsLeader, coord_instance_lock_ will be taken now before checking the status of a coordinator so we cannot get into situation where we check that the leader is ready but then whole become follower callback executes.
=> Fix ordering in show instances

.github/workflows/stress_jepsen.yaml, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_rpc.cpp, src/coordination/data_instance_management_server_handlers.cpp, src/coordination/include/coordination/coordinator_rpc.hpp, src/coordination/include/coordination/data_instance_management_server_handlers.hpp, src/coordination/include/coordination/replication_instance_client.hpp, src/coordination/replication_instance_client.cpp, src/coordination/replication_instance_connector.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/replication_handler/replication_handler.cpp, tests/e2e/high_availability/CMakeLists.txt, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/rpc_comm.cpp
When a MAIN missed a failover and is selected to be the new main, raft generates a new UUID.
This is then sent to main and replicas. 
Before this fix:
- replicas wouldn't update their durability
- main wouldn't update its clients, so the old uuid would still be used in places
Now the coordinator re-promotes main to main (updating uuid and epoch).
=> Bugfix: swapping UUID does not update durability nor active clients

src/memgraph.cpp
Users need to set `--coordinator-hostname` on coordinators.
=> Coordinator hostname must be set on coordinators

src/coordination/data_instance_management_server_handlers.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/replication_handler/replication_handler.cpp
- **Bugfix: Instance-level clients can now safely be closed after committing. Before, a promotion request would execute in parallel with committing and would cause locking a data instance.*
=> Lock repl state before closing instance-level replication clients

.github/workflows/stress_jepsen.yaml, tests/jepsen/src/memgraph/high_availability/create/test.clj
Recovery time increased to 15' since it's possible that at the end a lot of time is spent recovering from snapshot and WALs. Test will now run for 6h.
=> Increase running and recovery time for stress test

libs/CMakeLists.txt, src/communication/CMakeLists.txt, src/csv/CMakeLists.txt, src/query/interpret/awesome_memgraph_functions.cpp, src/query/interpret/eval.hpp, src/utils/CMakeLists.txt, tests/e2e/monitoring_server/CMakeLists.txt, tests/e2e/server/CMakeLists.txt, tests/gql_behave/tests/memgraph_V1/features/functions.feature, tests/gql_behave/tests/memgraph_V1_on_disk/features/functions.feature, tests/unit/CMakeLists.txt, tests/unit/query_expression_evaluator.cpp
There was compatibility issues noticed with `any` function.
`any(v IN [] WHERE v)` was returning NULL rather than false.
This also highlighted other compatibility issues in any, all, none, single. Mainly around handling of nulls within the list.
Also added the IsEmpty function
=> Compatibility bugfix for any, all, none, single

.github/workflows/stress_jepsen.yaml, src/storage/v2/replication/replication_client.cpp
When main instance checks the state of the replica because frequent check failed, it should release rpc lock before taking engine lock.
- **Bugfix: When checking replica state, main will release RPC lock before taking engine lock to avoid deadlock with commit thread.**
=> Bugfix: Fix deadlock by releasing RPC lock before acquiring engine lock

src/replication/include/replication/replication_server.hpp, src/replication/include/replication/state.hpp, src/replication/replication_server.cpp, src/replication_handler/replication_handler.cpp
When replica concurrently executes recovery and promotion, WAL file can be accessed concurrently which could cause flushing a closed file. The fix contains of waiting for recovery to finish before preparing storage for new epoch.
=> Bugfix: Concurrent recovery and promotion crash database

libs/setup.sh, tests/unit/mgp_kafka_c_api.cpp
This PR updates the version of `librdkafka` currently in use and modifies existing tests to ensure compatibility with the new version.
=> Update librdkafka version

src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state.cpp, src/coordination/coordinator_state_manager.cpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/coordinator_state.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/include/nuraft/coordinator_state_manager.hpp, src/coordination/raft_state.cpp, src/dbms/coordinator_handler.cpp, src/dbms/coordinator_handler.hpp, src/query/frontend/ast/ast.hpp, src/query/frontend/ast/cypher_main_visitor.cpp, src/query/frontend/ast/cypher_main_visitor.hpp, src/query/frontend/opencypher/grammar/MemgraphCypher.g4, src/query/interpreter.cpp, src/query/interpreter.hpp, tests/e2e/high_availability/distributed_coords.py, tests/unit/cypher_main_visitor.cpp, tests/unit/query_required_privileges.cpp
Added `show instance` query which returns the state of the instance: instance_name, bolt_server, management_server and role.
=> Add SHOW INSTANCE coordinator query

src/query/interpreter.cpp
This PR fixes a bug in after-commit triggers where the database accessor becomes invalid after the transaction finishes.
closes #2238
=> Fix after commit triggers bug

src/query/plan/planner.hpp
Don't ASSERT, throw query exception. It is possible that an ill formed query can lead to problems during planning. Analysis and good error reporting is difficult for this case, for now we will in general just throw. In future we will improve planner.
=> Prevent server crash

src/query/plan/planner.hpp, src/query/plan/rule_based_planner.hpp, src/query/plan/variable_start_planner.cpp, src/query/plan/variable_start_planner.hpp, tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
If no valid query plan can be generated, QueryException will be thrown. Currently our planner can put a match clause before call subquery clause even if match depends on call subquery.
=> Bugfix: MATCH is not allowed in the query containing CALL subquery

src/storage/v2/inmemory/storage.cpp, src/utils/async_timer.cpp
--query-execution-timeout-sec causes an allocation which was small, but not being freed. This is now freed.
=> Fix subtle memory leak around AsyncTimer

src/dbms/inmemory/replication_handlers.cpp, src/storage/v2/replication/replication_client.cpp
Replica could receive a WAL file which contains all old data. If that is the case, old epoch would be added to the history together with the current durable timestamp on replica causing a wrong information contained inside replica. Replicas shouldn't naively use data from WAL files recieved.
=> Bugfix: Replica should ignore old WAL data

.github/workflows/stress_jepsen.yaml, tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/query.clj
Jepsen stress test is improved so that it doesn't use explicit transactions to find maximum id and then create a new batch based on that but rather all is done within one query (implicit transaction). This should prevent false-positives on Jepsen tests where multiple fast auto-failovers were done on data instances.
=> Bugfix: Insert new batch of nodes within one txn

tests/e2e/high_availability/common.py, tests/e2e/high_availability/coord_cluster_registration.py, tests/e2e/high_availability/coordinator.py, tests/e2e/high_availability/disable_writing_on_main_after_restart.py, tests/e2e/high_availability/distributed_coords.py, tests/e2e/high_availability/single_coordinator.py
Isolated coordinator queries in e2e tests to reduce duplication and make code more readable.
=> Use partial function application in e2e HA tests

include/mgp.hpp, query_modules/convert.cpp, tests/e2e/query_modules/convert_test.py
`convert.str2object` implementation in C++ is fixed to also work with primitive values
=> Fix convert.str2object to work for primitives

src/storage/v2/inmemory/storage.cpp, src/utils/async_timer.cpp, src/utils/async_timer.hpp
Recent fix for ensuring memory was being released caused a noticeable cost to throughput for single_vertex_write benchmark. Moving the GC work to be done less frequently (likely to improve batching).
=> Reduce frequency of AsyncTimer GC

src/storage/v2/inmemory/storage.cpp, tests/e2e/constraints/constraints_validation.py
Unique constraint error would release the deltas to GC as part of Abort, but not make the commit timestamp as finished. Hence the deltas and any future deltas would be prevented from being deleted during GC.
=> Fix delta release on unique constraint error

tests/e2e/runner.py, tests/e2e/schema_info/schema_info.py
Currently, when an e2e test fails, cleanup is not performed. With these changes, we ensure that cleanup is executed in all cases.
=> Fix cleanup for e2e tests

src/storage/v2/indices/indices_utils.hpp, src/storage/v2/inmemory/edge_type_index.cpp, src/storage/v2/inmemory/edge_type_index.hpp, src/storage/v2/inmemory/edge_type_property_index.cpp, src/storage/v2/inmemory/edge_type_property_index.hpp, src/storage/v2/inmemory/storage.hpp
The edge indices have raw pointers into vertex and edges. Need to pin access to ensure objects are not deleted mid iteration.
=> Pin storage accessors when iterating edge indices

src/query/interpret/awesome_memgraph_functions.cpp, tests/unit/query_expression_evaluator.cpp
This also refactors the existing `toString` function, to bring the implementation of both of these functions into accord.
=> Add Cypher `toStringOrNull` function

src/storage/v2/inmemory/edge_type_index.cpp, src/storage/v2/inmemory/edge_type_index.hpp, src/storage/v2/inmemory/edge_type_property_index.cpp, src/storage/v2/inmemory/edge_type_property_index.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/storage_error.hpp, tests/e2e/edge_indices/edge_indices.py, tests/unit/storage_v2_indices.cpp
Abort does cleanup of objects and indexes. To work out what entries to remove from the index the current value of the entry needs to be figured out from the object as it is and the delta. The edge type information is held on the Vertex, not the Edge, hence need to process all edges first, otherwise we loose the information held on vertex which is needed to know which index entries need cleaning up.
=> Fix edge type index cleanup on Abort

src/query/replication_query_handler.hpp, src/replication/include/replication/replication_client.hpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/replication_handler/include/replication_handler/system_replication.hpp, src/replication_handler/replication_handler.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/replication/replication_storage_state.cpp, src/storage/v2/replication/replication_storage_state.hpp, src/storage/v2/storage.hpp, tests/unit/storage_v2_replication.cpp
`ReplicasInfo` method from the storage and repl storage state wasn't used.
=> Remove unused ReplicasInfo method

src/storage/v2/edge_ref.hpp, src/storage/v2/inmemory/storage.cpp, src/utils/CMakeLists.txt, src/utils/skip_list.cpp, src/utils/skip_list.hpp, src/utils/small_vector.hpp, tests/unit/small_vector.cpp
- Remove the linear seach validation when in release build
- Bulk edge removal O(nm) -> O(n+m)
- Disable skiplist GC during bulk removal
- Probabilistically run skiplist GC on accessor dtr
- Use vector rather than list
=> Perf improvement for Abort

include/mgp.hpp, query_modules/convert.cpp, query_modules/text_search_module.cpp, query_modules/vector_search_module.cpp, src/query/plan/operator.cpp, src/query/procedure/mg_procedure_impl.cpp
- Change query modules to use multipool instead of monotonic allocator because monotonic would sometimes cause OOM on query modules that create and delete a lot of objects due to not being able to reclaim memory.
- Add reference type to C++ API and change MGP::List and MGP::Map get operations to return a reference.
- Removed noexcept from C++ API calls that didn't make sense.
BREAKING: Incorrect usage of mgp_value (C - API) now causes a crash - you must be very careful not to do a double deallocation. `mgp_value` has a destructor and therefore `mgp_value_destroy` must only be called on a pointer. Also after running `mgp_value_destroy` you MUST not call mgp_`type`_destroy on the underlying data because that will cause double deallocation and a crash.
=> Change query modules allocator

src/query/plan/operator.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/replication/replication_client.cpp
PeriodicCommit now handles commit errors.
On error the last commit is aborted, while everything committed previously is still permanent.
Ignoring the replication error, since it does not influence the data in any way (unlike other commit errors).
=> Bugfix: PeriodicCommit crashes if commit generates replication error

src/utils/async_timer.cpp, tests/unit/utils_async_timer.cpp
Async timer was causing flaky unit test results. This was because of incorrect memory ordering. To make it more predictable the memory ordering has been changed.
=> Correct async timer memory order

libs/CMakeLists.txt, libs/rocksdb8.1.1.patch
RocksDB had a bit of its code which was not tolerant to an exception. This is a patch exists until a fix is made in the upstream codebase.
=> Patch rocksdb to tolerate exceptions

init, src/auth/reference_modules/requirements.txt
Due to security reasons memgraph should use latest versions of `cryptography` and `pyJWT` packages.
=> Upgrade python dependencies

src/dbms/inmemory/replication_handlers.cpp, src/memgraph.cpp, src/query/plan/hint_provider.hpp, src/storage/v2/inmemory/replication/recovery.cpp, src/storage/v2/inmemory/replication/recovery.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/rpc.cpp, src/storage/v2/replication/rpc.hpp, tests/e2e/memgraph.py, tests/e2e/replication/workloads.yaml, tests/unit/storage_v2_replication.cpp, tests/unit/utils_async_timer.cpp
The semantic of snapshot handler changed in the following way: Either handling snapshot request passes or it doesn't. If it passes we return the current commit timestamp of the replica. If it doesn't pass, we return optional which will signal to the caller that it shouldn't update the commit timestamp value. If loading snapshot file failed, it won't crash the database anymore. If an error happened during snapshot recovery, instead of crashing the database, we will now log a message and clear the storage. For recovery using WALFile, commit timestamp on main's side shouldn't be updated if:
1.) the database accessor couldn't be obtained
2.) UUID sent with the request is not the current MAIN's UUID which replica is listening to
Only if loading all WAL files succeeded then main can continue …
=> Improving replication recovery process

include/_mgp.hpp, include/mgp.hpp
The recent changes in the memory allocator used for user defined functions (#2561), has revealed issues in our C++ API. There were double deallocations of objects that with the previous monotonic allocator were not an issue (the memory still existed). This fix extends the lifetime of those objects to avoid crashes with the new allocator.
The C++ API should be overhauled at some point soon.
=> Protect the iterator lifetime with shared_ptr

include/mgp.hpp, query_modules/convert.cpp
C++ API results had issue with list & map. `convert.str2object` also leaked.
=> Fix memory leak in query modules

src/memgraph.cpp, src/query/procedure/module.cpp
Some Python modules should not be loaded more than once. This PR adds `numpy` and `dgl` to that list to avoid potential issues. This is mandatory to use latest versions of mentioned packages. 
Additionally, a deprecated call to `PyEval_InitThreads` has been removed, as it no longer has any effect starting from [Python 3.9](https://docs.python.org/3/whatsnew/3.9.html).
=> Avoid reloading dgl and numpy modules; remove deprecated python C-API function

src/query/interpret/eval.hpp, src/query/typed_value.cpp, src/query/typed_value.hpp
- Avoid default ctr of TypedValue, prefer move ctr
- Make TypedValue dtr do only essential work
- Optimise TypedValue assignment when memory and type are same
- Only construct + destroy the arguments that are needed
=> Function calls made cheaper

.github/workflows/stress_jepsen.yaml
Stress test will now run for 10h with 15h timeout on GH.
=> Increase Jepsen stress test to 10h

.github/workflows/stress_jepsen.yaml, src/dbms/dbms_handler.hpp, src/dbms/inmemory/replication_handlers.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/replication_handler/system_replication.cpp, src/rpc/client.hpp, src/storage/v2/config.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/storage/v2/replication/rpc.cpp, src/storage/v2/replication/rpc.hpp
The AppendDeltas response message doesn't return current timestamp anymore since it wasn't used before. If a replica cannot read epoch id, the database won't crash, rather it will return negative response. System heartbeat RPC will now also use timeout set by default to 10''. Force reset RPC now also uses a pre-defined timeout of 10''. If resetting storage fails, the replica will be considered MAYBE_BEHIND and on the next ping, branching should be observed again and a new request for resetting storage should be created.
=> Add timeouts for force reset and system heartbeat RPC messages

src/query/interpret/awesome_memgraph_functions.cpp, tests/unit/query_expression_evaluator.cpp
This adds the following explicit conversions between compatible temporal types:
- Date from Date and DateTime via `date()`
- LocalTime from LocalTime and DateTime via `localtime()`
- LocalDateTime from and DateTime via `localdatetime()`
- DateTime from DateTime via `datetime()`
=> fix: Convert between temporal types (#2572)

src/dbms/inmemory/replication_handlers.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/durability.hpp, src/storage/v2/inmemory/storage.cpp, tests/unit/storage_v2_durability_inmemory.cpp
Recalculating vertex batches if WALs are present <- fixes indices/constraints recovery
Using parallel recovery only is vertex batches > 1 <- fixes recovery without snapshots
Replication and RECOVER SNAPSHOT now recover indices/constraints in parallel as well
A bit simpler RecoverData logic
=> Bugfix: Parallel recovery doesn't work with WAL files

src/communication/bolt/v1/decoder/chunked_decoder_buffer.hpp, src/communication/bolt/v1/encoder/chunked_encoder_buffer.hpp, src/communication/bolt/v1/encoder/client_encoder.hpp, src/communication/bolt/v1/encoder/encoder.hpp, src/glue/communication.cpp, src/utils/result.hpp, tests/unit/bolt_common.hpp, tests/unit/bolt_encoder.cpp, tests/unit/bolt_session.cpp, tests/unit/storage_v2_indices.cpp, tests/unit/storage_v2_wal_file.cpp, tests/unit/ttl.cpp
```sh
N=12
tmux new-session -d -s mysession
for ((i=1; i<N; i++)); do
tmux split-window -h
tmux select-layout tiled
done
tmux set-window-option synchronize-panes on
tmux attach-session -t mysession
mgconsole
unwind range(1,1000000) as a with a, 1 as b, 1 as c return *;
```
|       | before    | after     |
| ----- | --------- | --------- |
| N=1   | 1.715 sec | 1.725 sec |
| N=12  | 2.490 sec | 1.990 sec |
| N=24  | 4.810 sec | 2.925 sec |
=> Reduce contention around socket send

src/rpc/client.hpp
Set the timeout for ForceResetStorageRpc to 1' and added a timeout for SystemRecoveryRpc to 5'. Recovering 1000DBs takes approx 25''.
=> Add timeout for the SystemRecoveryRpc message

src/utils/rw_spin_lock.hpp
- Adds YIELD instruction when building on ARM64. This is preferred over `__builtin_aarch64_yield`, as only GCC supports that intrinsic.
- Adds compilation error if the `RWSpinLock` is built with any other architecture (other than i386, x86-64, or aarch64)
=> fix: Add YIELD instruction to `RWSpinLock` on ARM64

src/memory/global_memory_control.cpp, src/memory/query_memory_control.cpp, src/memory/query_memory_control.hpp, src/query/db_accessor.cpp, src/query/db_accessor.hpp, src/query/interpreter.cpp, src/query/interpreter.hpp, src/query/plan/operator.cpp, src/storage/v2/storage.cpp, src/storage/v2/storage.hpp, src/storage/v2/transaction.hpp, src/utils/query_memory_tracker.hpp, tests/e2e/memory/procedures/proc_memory_limit.cpp, tests/e2e/memory/procedures/query_memory_limit_proc.cpp, tests/unit/utils_query_memory_tracker.cpp
Removed skip lists and using thread locals to point to the correct tracker 
Simpler logic and better locality
Bugfixes, including calls to wrong functions or misaligned calls
=> Overhaul of the query memory tracker

src/coordination/coordinator_instance.cpp, src/coordination/data_instance_management_server_handlers.cpp, tests/e2e/high_availability/coord_cluster_registration.py
Issue in the C++ code, using remove without erase. Unregistering now works correctly even after restarting instances.
=> Bugfix: Unregister replication instance wasn't durable

src/query/interpret/awesome_memgraph_functions.cpp
This lead to non-determanistic behaviour when combined with other recent changes around improving performance of function calls.
=> Bugfix, timestamp didn't check nargs

src/storage/v2/storage.cpp, src/storage/v2/storage.hpp, tests/e2e/concurrency/concurrency.py, tests/unit/CMakeLists.txt, tests/unit/storage_v2_acc.cpp
Fixes a potential deadlock.
Deadlock is possible every time one query takes a unique lock during prepare.
This lock won't be released until pull. In the meantime, other requests can saturate the worker pool, which leads to all workers waiting on the lock  (unique or shared) during prepare and not letting any work (pull) through.
=> Timing out storage access

src/coordination/coordinator_instance_management_server_handlers.cpp, src/coordination/include/coordination/coordinator_instance_management_server_handlers.hpp, src/dbms/inmemory/replication_handlers.cpp, src/dbms/inmemory/replication_handlers.hpp, src/rpc/client.hpp, src/rpc/utils.hpp, src/storage/v2/inmemory/replication/recovery.cpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/rpc.cpp, src/storage/v2/replication/rpc.hpp, tests/unit/CMakeLists.txt, tests/unit/replication_rpc_progress.cpp, tests/unit/rpc_in_progress.cpp
Added timeouts to AppendDeltas, CurrentWal and WalFiles RPC messages. For every 100k processed deltas, we send InProgressRes back to the client. If there are mutliple txns or multiple WAL files, the whole context is taken into account for counting deltas.
=> Add RPC timeouts for AppendDeltas, CurrentWal and WalFiles

src/query/interpreter.cpp
Due to the inconsistent use of the ranges library, there was an issue with vector index config map parsing.
=> Fix vector index config map parsing issues

.github/workflows/stress_jepsen.yaml, tests/jepsen/run.sh, tests/jepsen/src/memgraph/high_availability/create/test.clj
Run Jepsen stress test with arg `--leave-db-running`. Returns recovery time to 900s which was change due to error. Runs tar with `--ignore-failed-read` to prevent the command from exiting.
=> Restore recovery time on Jepsen, use leave-db-running and ignore-fail-read to prevent tar from early exit

src/coordination/coordinator_instance.cpp, src/coordination/include/coordination/register_main_replica_coordinator_status.hpp, src/coordination/include/coordination/replication_instance_client.hpp, src/query/interpreter.cpp, tests/e2e/high_availability/common.py
Added timeouts for lock acquiring in success and fail callbacks. Unregistration is also forbidden in the case when there is no current main in the cluster to prevent drifting between in-memory and raft state on coordinators. 
Instance checker will now be destroyed before RPC client to prevent possible UB.
=> Bugfix: Unregister replication instance could deadlock

src/dbms/dbms_handler.hpp, tests/e2e/durability/CMakeLists.txt, tests/e2e/durability/common.py, tests/e2e/durability/multitenancy.py, tests/e2e/durability/snapshot_recovery.py, tests/e2e/durability/workloads.yaml
Memgraph can be started in K8s environment with various storage providers. Some of them create `.snapshot` file which was preventing the database from starting. When Memgraph is started in a single-tenant mode, durability files are linked to those from the root for the back-compatibility. All hidden files should be ignored.
=> Bugfix: Ignore hidden files when symlinking data directory

.github/workflows/stress_jepsen.yaml, .gitignore, tests/jepsen/resources/ha-mt.edn, tests/jepsen/run.sh, tests/jepsen/src/memgraph/core.clj, tests/jepsen/src/memgraph/mtenancy/nemesis.clj, tests/jepsen/src/memgraph/mtenancy/test.clj, tests/jepsen/src/memgraph/mtenancy/utils.clj, tests/jepsen/src/memgraph/query.clj, tests/jepsen/src/memgraph/utils.clj, tests/jepsen/test/memgraph/memgraph_test.clj
Adds multi-tenancy with HA test. Currently, we create N tenants and import nodes and edges on all of them. Nemesis is run with network and killing disruptions turned on. Throughout the execution, we only run `SHOW INSTANCES`. 
Additionally, the PR also removes `--leave-db-running` when running HA tests since the issue for which the flag was added is fixed. Hence, no need anymore to keep the logs more than necessary.
Related PR https://github.com/gorillalabs/neo4j-clj/pulls.
=> Add multitenancy HA stress test

include/_mgp.hpp, include/mg_procedure.h, src/query/procedure/mg_procedure_impl.cpp
Rename `graph_count_vertices` and `graph_count_edges` to `approximate_x_count` to show they are approximative. Functions were added in [PR2762](https://github.com/memgraph/memgraph/pull/2762) and docs are handled there.
=> Rename newly added count mgp functions for better clarity

src/dbms/database.hpp, src/query/interpreter.cpp, src/storage/v2/disk/storage.cpp, src/storage/v2/disk/storage.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/storage.cpp, src/storage/v2/storage.hpp, tests/unit/storage_v2_acc.cpp
Recent changes made possible for Storage::Access to timeout.
This is needed for Cypher queries, as their execution is split into Prepare and multiple Pulls. Not timing out could lead to a deadlock.
On the other hand, this is not fine in other circumstances (ex. SnapshotCreate).
This fixes the issue by allowing the access timeout only for Prepare.
=> Bugfix: Storage access timeout allowed everywhere

src/dbms/inmemory/replication_handlers.cpp, src/dbms/rpc.hpp, src/rpc/messages.hpp, src/rpc/server.hpp, src/storage/v2/inmemory/replication/recovery.cpp, src/storage/v2/inmemory/replication/recovery.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/rpc.hpp, src/storage/v2/replication/serialization.cpp, src/storage/v2/replication/serialization.hpp, tests/unit/replication_rpc_progress.cpp
Replica won't crash anymore when performing recovery and when disk access to durability folder fails. Instead, it will return empty response which will signal to main that the recovery isn't completed.
=> Bugfix: prevent main from crashing while recovering replica due to disk failures

src/coordination/data_instance_management_server_handlers.cpp, src/dbms/inmemory/replication_handlers.cpp, src/io/network/endpoint.cpp, src/replication/include/replication/epoch.hpp, src/replication/status.cpp, src/rpc/protocol.cpp, src/slk/streams.cpp, src/slk/streams.hpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/durability.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/replication/replication_client.cpp, src/utils/uuid.hpp, tests/jepsen/run.sh, tests/jepsen/src/memgraph/core.clj, tests/unit/slk_streams.cpp, tests/unit/storage_v2_durability_inmemory.cpp
slk::Reader would throw before if data from the buffer wouldn't be completely ready. This caused network connections between main and replica to be constantly dying when unnecessary. Now when replica doesn't read all data from the buffer, the exception thrown in the slk part of the code is handled properly, avoiding the connection drop. Additionally, the PR tries to reduce the massive amount of logs produced in HA code when trace log level is used. The PR also improves jepsen's run script so that it doesn't fail when jepsen.log cannot be read. With this fix, we should be able to see at least part of the logs which can also be helpful for debugging. Jepsen tests are also checking whether `There is still leftover data in the SLK stream` exception will be thrown during the execution.
=> Bugfix: Avoid throwing in slk when a buffer isn't read fully

src/dbms/inmemory/replication_handlers.cpp, src/io/network/addrinfo.cpp, src/io/network/endpoint.cpp, src/io/network/socket.cpp, src/io/network/socket.hpp, src/rpc/protocol.cpp, tests/jepsen/src/memgraph/core.clj
The following set of events caused a deadlock in our HA:
1. MAIN receives query to commit as implicit txn.  Main lock is hold all the time because of query,
2. While executing and before the commit, main is demoted to replica.
3. Replica receives snapshot rpc and tries to acquire the main lock.
4. Replica receives request to get promoted. RPC server cannot be closed because snapshot rpc isn't finished.
The fix consists of waiting for a lock in replication handlers for SnapshotRpc, WalFilesRpc and CurrentWalRpc but with a predefined timeout. Additionally, log message for addrinfo is now added, same as log message when trying to close Socket.
=> Bugfix: Prevent deadlock on data instance

src/auth/models.cpp
Bad check for old auth data leads to broken auth data, which in turn causes an exception.
Fixed check resolved this issue.
Bug present from v3.1
=> Bugfix: Broken migration from old durable auth data

src/auth/reference_modules/requirements.txt
Add xmlsec to requirements so the correct version gets installed on MAGE which fixes SAML not working on MAGE.
=> Add xmlsec to requirements for auth modules

.github/workflows/diff_release.yaml, release/package/mgbuild.sh, tests/gql_behave/continuous_integration, tests/gql_behave/tests/memgraph_V1/features/match.feature
Currently, we don't save logs from GQL Behave test CI runs. Since these tests are executed by running queries in Memgraph, we have no log data to diagnose failing tests. This PR adds log saving after the job finishes.
=> Save logs from GQL behave tests on CI

tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/mtenancy/test.clj, tests/jepsen/src/memgraph/utils.clj
Some exceptions are normal and expected. We want to catch them in the test so we don't need to reason about whether something was expected or not.
=> Handle allowed failures in MT Jepsen test

src/query/interpreter.cpp, src/replication_handler/replication_handler.cpp, src/storage/v2/durability/snapshot.cpp, src/storage/v2/durability/snapshot.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/utils/timer.hpp
When main becomes replica, snapshot scheduler is paused and all snapshot locks are taken. When replica gets promoted, abort is set to false and scheduler resumed. On demotion, if there is a snapshot currently getting created, it will get aborted.
=> Bugfix: Concurrent snapshot creation and demotion cause replica to crash on restart

tests/jepsen/run.sh
Datasets folder should be deleted after the copying to all nodes had finished.
=> Bugfix: Delete datasets folder at the end of copying in HA-MT jepsen workflow

src/coordination/data_instance_management_server_handlers.cpp, src/coordination/include/coordination/data_instance_management_server_handlers.hpp
When a replica gets promoted to main, it tries to register all other replicas. If registering one of replicas failed, there was a bug in SLK where the buffer would contain both false + true. When an error is encountered during promotion, promote is aborted and this information is returned back to coordinator. The coordinator should then try to repeat the registration process.
=> Eagerly return if registering one of replicas fail upon promotion.

tests/gql_behave/steps/graph.py
If you're testing indices and checking the number of entries in the index, you might get the wrong impression of what's happening. This is because the "correct" entry count is only visible after a GC run, not immediately after a node is marked as deleted.
=> Fix graph cleanup in GQL Behave tests

.github/workflows/diff_community.yaml, .github/workflows/diff_coverage.yaml, .github/workflows/diff_debug.yaml, .github/workflows/diff_release.yaml, .github/workflows/release_build_test.yaml, .github/workflows/reusable_release_tests.yaml, .github/workflows/stress_test_large.yaml
Use Ubuntu 24.04 by default for every workflow except for `jepsen`.
=> Use ubuntu 24.04 for (almost) everything

tests/jepsen/clean_old_directories.sh
The PR tries to clean .old directories inside databases/ folder also to handle the case when test is run with MT configuration.
=> Clean .old snapshot directories for MT test

include/mg_procedure.h, src/query/plan/operator.cpp, src/query/procedure/mg_procedure_impl.cpp, src/query/procedure/mg_procedure_impl.hpp, src/query/procedure/module.cpp, src/query/stream/streams.cpp
- Change `mgp_result_record ` to use std::vector instead of std::map: 72 bytes -> 48 bytes + additional memory saved from not having map entries (strings)
- Instead of searching for the procedure on every pull cache it on cursor creation.
- Add `mgp_result_reserve`in C-API.
- As a consequence of the first entry procedures don't throw anymore if all results don't get inserted.
=> Query modules memory improvements

src/utils/scheduler.cpp, tests/unit/utils_scheduler.cpp
If a task takes longer than the period, scheduler will execute one task immediately, instead of N backed up tasks
=> utils::Scheduler now skips backed up tasks

src/storage/v2/indices/indices.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/unique_constraints.cpp, src/storage/v2/inmemory/unique_constraints.hpp, tests/unit/storage_v2_indices.cpp
Added missing GC runs for edge propery index and unique constraints.
Fixed edge property update in Abort.
Performance improvement: Abort doesn't loop through all edge type indices
=> Bugfix: Missing edge property index and unique constraint garbage collection

tests/unit/integrations_kafka_consumer.cpp
Remove batch check that doesn't need to be true due to reasons explained in the previous [PR](https://github.com/memgraph/memgraph/pull/2881).
=> Fix flaky Kafka consumer test 2

src/query/interpreter.cpp, src/query/time_to_live/time_to_live.cpp, src/query/time_to_live/time_to_live.hpp, tests/unit/ttl.cpp
Did not limit edge TTL to InMemory in the initial implementation. All changes are part of v3.2
=> Disable edge TTL for OnDisk

src/storage/v2/inmemory/storage.cpp, src/storage/v2/schema_info.cpp, src/storage/v2/schema_info.hpp, src/storage/v2/schema_info_glue.hpp, src/storage/v2/schema_info_types.hpp, src/storage/v2/transaction.hpp, src/storage/v2/vertex_accessor.cpp, tests/integration/audit/runner.py, tests/unit/storage_v2_schema_info.cpp
Changed how post-processing work. Previous implementation was too pessimistic. 
Now checking when and who made changes in order to better figure out if edge post-processing is needed.
In addition, added caching for vertex labels, so no need to re-create the object every time.
=> Schema info speed up

.github/workflows/reusable_release_tests.yaml
Remove `continue-on-error` on daily build tests to stop failing tests being marked as successful.
=> Stop build tests from failing successfully

.github/workflows/reusable_release_tests.yaml, tests/jepsen/run.sh
Fixes missing test option by running the same tests used in the `diff_jepsen` workflow.
=> Fix Jepsen release tests

.github/workflows/daily_build.yml
Use UTC when setting up daily build with the `date` command (i.e. `$(date -u +'%Y%m%d')`)
=> Use UTC when setting up daily build

src/dbms/inmemory/replication_handlers.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/metadata.hpp, src/storage/v2/durability/wal.cpp, src/storage/v2/durability/wal.hpp, src/storage/v2/inmemory/storage.cpp
Last applied timestamp is now updated only if WAL files are used in the recovery.
=> Bugfix: Rely (almost) solely on last durable ts

.github/workflows/reusable_stress_jepsen.yaml, tests/jepsen/src/memgraph/mtenancy/nemesis.clj, tests/jepsen/src/memgraph/mtenancy/test.clj, tests/jepsen/src/memgraph/mtenancy/utils.clj
When changing test to use 3 data instances instead of 2, some things weren't updated appropriately.
=> Bugfix: MT test now runs with 3 data instances

.github/workflows/reusable_release_tests.yaml
Increase the timeout for the debug tests to avoid flaky timeouts on daily builds and release builds.
=> Increase debug test timeout

src/coordination/coordinator_cluster_state.cpp, src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/coordination/constants.hpp, src/coordination/include/coordination/coordinator_cluster_state.hpp, src/coordination/include/coordination/coordinator_communication_config.hpp, src/coordination/include/coordination/coordinator_state_machine.hpp, src/coordination/include/coordination/raft_state.hpp, src/coordination/raft_state.cpp, src/replication_coordination_glue/role.hpp, tests/e2e/high_availability/distributed_coords.py, tests/unit/coordinator_cluster_state.cpp, tests/unit/coordinator_log_store.cpp
Using the query `set coordinator setting 'sync_failover_only' to 'true'/'false'` users can modify the failover logic when deciding on which instance to perform a failover. When the option is set to true, only sync replicas will be considered. The option is by default set to true to minimize the chances of experiencing a data loss upon failover.
=> User-configurable option to failover only to SYNC replica

.github/workflows/reusable_release_tests.yaml
Some tests are timing out in slightly slower runners, this PR increases those timeouts by a small amount to reduce the number of failing daily builds.
=> Increase runner timeouts

src/communication/bolt/client.cpp, src/communication/bolt/client.hpp, src/glue/SessionHL.cpp, src/glue/SessionHL.hpp, src/query/frontend/semantic/required_privileges.cpp, src/query/interpreter.cpp, src/query/interpreter.hpp, tests/drivers/python/v5_8/impersonate_user.py, tests/integration/audit/runner.py, tests/integration/audit/tester.cpp
SessionHL would update the interpreter with the imp_user, but the logic was split between the two
Parts of the logic inside SessionHL:
- query authorization
- audit logs
- MT authoriztaion 
Query authorization has been moved to the interpreter.
Other parts remain in the SessionHL, but use the interpreter's user.
=> Bugfix: Impersonate user misalignment between interpreter and session

src/coordination/coordinator_instance.cpp, src/coordination/coordinator_log_store.cpp, src/coordination/coordinator_state_machine.cpp, src/coordination/include/coordination/coordinator_log_store.hpp, src/coordination/include/coordination/coordinator_state_machine.hpp
Removes unused atomic variables and fixes some of the concurrency bugs noticed in HA stack. The operation`compare_exchange_strong` in coordinator_instance.cpp now uses acquire-release memory order semantics on success and failure operations. The variable `start_idx` now uses also acquire-release semantics instead of sequentially consistent operations. The lock `last_snapshot_lock` wasn't used and atomic variable `next_idx` from coordinator_log_store.
=> Bugfix: Improve the usage of RMW pattern in HA coordinators

src/query/frontend/semantic/rw_checker.cpp, src/query/interpreter.cpp, src/query/plan/fmt.hpp, src/query/plan/read_write_type_checker.hpp, src/storage/v2/storage.hpp, tests/unit/cypher_main_visitor.cpp
RWChecker would overwrite status based on procedure rw status
This would break if a write query was calling a read procedure
Nicer error message in case of accessor misalignment
=> Bugfix: RWChecker gives wrong result for read proc

release/docker/v6_deb.dockerfile, release/docker/v6_deb_relwithdebinfo.dockerfile
For compatibility with MAGE containers we need to match the UID and GID of the `memgraph` user. This fix has already been applied to MAGE in [#568](https://github.com/memgraph/mage/pull/568).
=> Set the UID of memgraph user in Docker container to match that of MAGE

tests/e2e/replication/read_write_benchmark.cpp, tests/e2e/replication/workloads.yaml
Added checks for the correct `vertex_count` and `edge_count` in the storage info response before proceeding with the test, ensuring that data is correctly replicated. This allows the test to fail early if the expected replication data is missing.
Additionally, the endpoints flag was previously hardcoded in `common.hpp`, but the number of database instances being tested has changed. Instead of relying on the default value, the correct value is now explicitly passed.
=> Improve read-write benchmark test

.github/workflows/promote_rc_release.yml, .github/workflows/release_build_test.yaml
- Added `relwithdebinfo` Docker image build for `arm64`
- Push `relwithdebinfo` Docker images to `download.memgraph.io` bucket during RC promotion
- Push `relwithdebinfo` DEB packages to `download.memgraph.io` bucket during RC promotion
=> Added missing debug builds

src/io/network/socket.cpp, src/io/network/socket.hpp, src/rpc/client.hpp, tests/jepsen/src/memgraph/core.clj
The PR adds the functionality of socket connect with timeout. The only portable way of doing this is creating a socket in a non-blocking mode, timeout check using `poll` and switching it back to a blocking mode since we all our sockets are used in blocking mode. UNIX doesn't have an API which would allow that from the start. The primary motivation for such a change is the fact that socket connect timeout can be quite high (~130s) and that it depends on the platform and on the number of SYN packets sent during connect. Two properties need to be satisfied for a system to be considered synchronous:
1. There is a known upper bound on processing delays. This includes the time needed to receive a message, perform a local computation and replying
2. There is a known upper bound on message …
=> Add timeout on socket connect

tests/e2e/interactive_mg_runner.py, tests/mgbench/benchmark.py, tests/mgbench/benchmark_context.py, tests/mgbench/runners.py, tests/mgbench/setup.py
Benchmark can now be started without necessarily starting instances during test time. Instead, by specifying configuration parameters `external-vendor` and `--client-bolt-address` client can get attached to any instance or even cluster.
=> Add support for replication benchmark

src/glue/auth_checker.cpp, src/glue/auth_checker.hpp, src/memgraph.cpp, src/query/auth_checker.hpp, src/query/stream/streams.cpp, src/query/time_to_live/time_to_live.cpp, tests/e2e/sso/test_sso.py, tests/unit/query_trigger.cpp
Explicitly creating empty users, instead of reusing generic auth logic 
This is because when using auth modules we force user/role 
It is only in these specific cases where we don't want to force it: init from cypher file, streams and TTL
=> Bugfix: fails to create empty user while using auth modules

src/utils/scheduler.cpp, tests/unit/utils_scheduler.cpp
After v3.2 the scheduler start time could drift in cases where tasks take longer to complete than the period
This is now fixed by using the period as the time increment instead of resetting the next iteration to be now
This issue could cause ttl to drift.
=> Bugfix: utils::Scheduler start_time drift

CMakeLists.txt, src/query/frame_change.hpp, src/query/graph.cpp, src/query/graph.hpp, src/query/interpret/awesome_memgraph_functions.cpp, src/query/interpret/eval.hpp, src/query/interpret/frame.hpp, src/query/path.hpp, src/query/plan/operator.cpp, src/query/plan/rewrite/index_lookup.hpp, src/query/procedure/mg_procedure_impl.cpp, src/query/procedure/mg_procedure_impl.hpp, src/query/procedure/py_module.cpp, src/query/typed_value.cpp, src/query/typed_value.hpp, src/utils/memory.cpp, src/utils/memory.hpp, src/utils/skip_list.hpp, tests/unit/query_expression_evaluator.cpp, tests/unit/typed_value.cpp, tests/unit/utils_memory.cpp
Remove our own `utils::MemoryResource` in favour of std::pmr::memory_resource. Also change to `std::pmr::polymorphic_allocator`.
The main reasons to do this:
- reduce code maintenance
- better tested, updated and, correct version in libstdc++
- handles pair like types better
Also changed TypedValue's map to `std::pmr::map<TString, TypedValue, std::less<>>` until we update boost to make flat_map correct.
=> Use std::pmr::memory_resource

tests/mgbench/benchmark.py, tests/mgbench/benchmark_context.py, tests/mgbench/client.cpp, tests/mgbench/runners.py, tests/mgbench/workloads/pokec.py
Databases can be specified when external-vendor is used.
```bash
./benchmark.py external-vendor --num-workers-for-benchmark 4 --export-results benchmark_result_external.json --client-bolt-address localhost --no-authorization --databases memgraph,db1,db2,db3 pokec/small/arango/single_vertex_read
```
When multiple threads are used, each thread uses a separate set of databases so that commit is as parallel as possible on the Memgraph level.
=> Add support for MT benchmark

src/storage/v2/replication/replication_client.cpp
The PR fixes the bug with asynchronous replication. If the recovery would've finished between starting and finishing txn, it would set the replica state to ready and then a txn wouldn't ever be replicated. This is fixed by protecting the exit from FinalizeTransactionReplication using engine lock.
The replication performance is improved by reducing the memory order level required from sequentially consistent to acquire.
=> Bugfix: Fix replication state machine when recovery and commit tasks are interleaved

.github/workflows/release_mgbench_client.yaml, .github/workflows/reusable_build_mgbench_client.yml
Additional job to re-tag `mgbench` images after pushing individual `amd64` and `arm64` tags.
=> Update workflows to re-tag mgbench images

.github/workflows/reusable_stress_jepsen.yaml
Jepsen MT will now run for 3h. In this way we try to reduce the pressure on disk consumption during run since machines often end without disk space.
=> Reduce running time to 3h for MT Jepsen test

src/rpc/client.hpp, src/rpc/exceptions.hpp, src/storage/v2/inmemory/replication/recovery.hpp, src/storage/v2/replication/replication_client.cpp
When using ASYNC replicas, MAIN could deadlock because in its thread pool there would be a commit task holding RPC lock. Commit task would wait for other tasks to finish but these tasks wouldn't not be able to get executed because RPC lock couldn't be acquired. The current fix is to try lock on RPC lock and if this is not possible, skip the task. This shouldn't be a problem because replica will stay in RECOVERY state,
=> Bugfix: Fix deadlock when using ASYNC replicas by skipping recovery tasks if lock cannot be obtained

src/dbms/inmemory/replication_handlers.cpp, src/replication_handler/replication_handler.cpp, src/storage/v2/commit_log.cpp, src/storage/v2/commit_log.hpp, src/storage/v2/inmemory/storage.cpp, tests/unit/commit_log_v2.cpp
When an instance becomes MAIN, `RECOVER SNAPSHOT` query is used or `SnapshotRpc` is received, IDs in range [old_storage_timestamp, ldt] are marked as finished in the commit log.
=> Bugfix: Unreleased deltas when using HA

tests/mgbench/runners.py
Address wasn't correctly propagated to the client in all execution paths.
=> Bugfix: mgbench using external vendor

environment/os/debian-11.sh, environment/os/ubuntu-22.04.sh, environment/os/ubuntu-24.04.sh, release/docker/v5_deb.dockerfile, release/docker/v5_deb_relwithdebinfo.dockerfile, release/docker/v6_deb.dockerfile, release/docker/v6_deb_relwithdebinfo.dockerfile
[Bug](https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/2096974) in `tzdata` has been [fixed](https://bugs.launchpad.net/ubuntu/noble/+source/tzdata/+bug/2107950),  so we can unpin the package version.
=> Unpin tzdata

src/utils/logging.cpp, src/utils/logging.hpp, src/utils/thread_pool.hpp
Use std::source_location instead of relying on __FILE and __LINE
=> Use std::source_location for MG_ASSERT

tests/mgbench/how_to_use_benchgraph.md
Added instructions on how to use the new `mgbench-client:0.0.4-full` image to benchmark Memgraph.
=> Update mgbench docs with instructions on new docker image

release/docker/v6_deb_relwithdebinfo.dockerfile
Accidentally staged a change to the relwithdebinfo dockerfile, breaking daily builds - this removes that change.
=> Remove accidental update to Dockerfile

environment/os/centos-10.sh, release/package/centos-10/Dockerfile, release/package/mgbuild.sh
Package update using `dnf update -y --nobest` was getting stuck at the stage where where it would attempt to install `nvidia-gpu-firmware`; this fix stops the update happening and should allow the build to continue.
=> Remove package update to stop CentOS 10 build getting stuck

src/glue/SessionHL.cpp, src/glue/communication.cpp, src/query/frontend/ast/pretty_print.cpp, src/query/procedure/mg_procedure_impl.cpp, src/query/serialization/property_value.cpp, src/storage/v2/delta.hpp, src/storage/v2/durability/serialization.cpp, src/storage/v2/property_store.cpp, src/storage/v2/property_value.hpp, src/storage/v2/replication/slk.cpp, tests/unit/storage_v2_indices.cpp
Replace `PropertyValue` `map_t` with `std::map` rather than `boost::container::flat_map`. 
boost's `flat_map` does not correctly propogate allocators in nested containers. This means that nested `PropertyValue`s created for `Delta`s are created using the incorrect allocator, and leak memory which is never reclaimed.
This temporary fix replaces the internal `map_t` with `std::map`, which *does* propogate allocators. Once we have established if a more recent `boost` version fixes the issue, we can revert this fix.
=> Replace `PropertyValue` map internals

release/package/mgbuild.sh
Install missing `lsof` command before E2E release tests.
=> Install `lsof` prior to E2E tests

src/coordination/coordinator_state_machine.cpp, src/storage/v2/durability/snapshot.cpp, src/storage/v2/inmemory/storage.cpp, src/utils/CMakeLists.txt, src/utils/atomic_max.hpp, src/utils/memory_tracker.cpp
Simplifies lock-free max impl.
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p0493r3.pdf
=> Add support for c++26 atomix_fetch_max_explicit

src/audit/log.cpp, src/communication/listener.hpp, src/dbms/dbms_handler.hpp, src/dbms/inmemory/replication_handlers.cpp, src/replication/state.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_storage_state.cpp, src/system/include/system/state.hpp, src/system/include/system/transaction.hpp, src/utils/barrier.hpp
We use seq_cst on multiple places which is unnecessarily slow.
For x86 platforms, stores with seq_cst use one of the alternatives:
(LOCK) XCHG // alternative: MOV (into memory),MFENCE
https://www.cl.cam.ac.uk/~pes20/cpp/cpp0xmappings.html
Changing it to release will reduce the need of generating MFENCE
=> Optimize usage of std::atomic for x86 platform around replication code

src/query/interpreter.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/snapshot.cpp, src/storage/v2/durability/snapshot.hpp, src/storage/v2/inmemory/replication/recovery.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/replication_client.hpp, src/utils/uuid.hpp, tests/e2e/system_replication/multitenancy.py
RECOVER SNAPSHOT did not work with replication.
Bugfix: Snapshot's UUID would override the storage one would cause the DBMS on REPLICAS to search for the wrong database. Now in case of user recovery, the local snapshot's UUID is overwritten.
Bugfix: Replication would not work in all cases due to the timestamp change. Now user recovery forces a reset of the replicas.
=> Enabling replication in case of RECOVER SNAPSHOT

tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/utils.clj
The test won't fail anymore if the following exception gets thrown: Transaction was asked to abort due to transaction timeout.
=> Fix Jepsen txn timeout handling

src/coordination/include/coordination/raft_state.hpp, src/coordination/include/coordination/utils.hpp, src/coordination/raft_state.cpp, src/coordination/utils.cpp, tests/unit/coordinator_raft_state.cpp
The important part of testing is preserved by isolating routing table creation into utils method.
=> Remove networking overhead from the flaky Raft state test

src/storage/v2/inmemory/label_property_index.cpp, tests/unit/storage_v2_indices.cpp
Queries using a label+property index now correctly return matching results when comparing properties against regular expressions. 
The problem was caused by index code rejecting ranges across different `PropertyType`s as being invalid. This is true in most cases, (e.g. `WHERE node.a > 'hello' AND node.a < 42`) but not in the case where the upper-bound is an exclusive (`<`) bound on the next (from an ordering standpoint) `PropertyType`. As the exclusive upper bound exclusive sentinel is not compared against, it means that the range is still across a single `PropertyType`.
Regexes uses a range that is inclusively lower bounded on the empty string, and exclusively upper bounded on the minimum value of whatever `PropertyType` happens to follow string.
(This bug was a regression introduced by …
=> Support regex queries with label+property indices

.github/workflows/reusable_stress_jepsen.yaml, src/dbms/inmemory/replication_handlers.cpp, src/dbms/inmemory/replication_handlers.hpp, src/storage/v2/durability/durability.cpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, src/storage/v2/inmemory/unique_constraints.cpp, src/storage/v2/replication/replication_transaction.cpp, src/storage/v2/replication/replication_transaction.hpp, tests/jepsen/src/memgraph/high_availability/create/test.clj, tests/jepsen/src/memgraph/utils.clj
- Fixes invalid cached accessor in the following way: If cached accessor is nullptr, it is impossible we should commit because replying to prepare happens after assignment to the accessor. If cached accessor is nullptr, and we should abort (e.g. exception was thrown while processing deltas), we can safely return here OK because it means that the abort already happened while destructing accessor during ReadAndApplyDeltasSingleTxn.
- small refactoring of unique constraints in order to make debugging easier.
- handling STRICT_SYNC replica down in Jepsen test
- removed unique constraint creation in Jepsen test since we have a bug in GC
- a lot of comments
=> Handle invalid accessor

src/dbms/inmemory/replication_handlers.cpp, src/replication_handler/replication_handler.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/durability/wal.cpp, src/storage/v2/replication/replication_client.cpp, tests/jepsen/src/memgraph/high_availability/create/test.clj
When WAL file is used during the restart, instead of setting ldt to wal.to_timestamp, we track which deltas were applied. 
The LOG_FATAL is removed since that property doesn't hold anymore for STRICT_SYNC replicas.
=> Use deltas' timestamp instead of wal.to_timestamp

config/mappings.json
Added mappings for following apoc functions:
apoc.convert.toJson()
apoc.convert.fromJsonList()
apoc.convert.toTree()
apoc.coll.flatten()
=> Added mappings for new apoc functions

src/storage/v2/replication/replication_transaction.cpp
Fixes the following scenario:
Main tries to commit while STRICT_SYNC and ASYNC replica are behind. For ASYNC replica we don't take the RPC lock. When aborting we were calling `client->AbortRpcClient()` although we didn't own the stream, hence we would destroy on-going FrequentHeartbeatRpc.
=> Bugfix: Don't abort rpc client for async replica which doesn't own the stream

release/docker/v6_deb.dockerfile, release/docker/v6_deb_relwithdebinfo.dockerfile
Reduce Docker image size saving almost 100 MB for both `release` and `relwithdebinfo` images (a reduction of about 23% and 14%, respectively).
=> Reduce docker image size

src/query/frontend/semantic/symbol_generator.cpp, tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
Fix unwind checking symbols in all scopes to checking in current scope
=> Fix unwind checking symbols in all scopes to checking in current scope

src/storage/v2/durability/durability.cpp, src/storage/v2/durability/metadata.hpp, src/storage/v2/durability/wal.cpp, src/storage/v2/inmemory/storage.cpp
When loading WAL we were adding epochs to history without checking whether it actually contained some changes.
=> Avoid adding to history epochs which didn't update database

.github/workflows/reusable_release_tests.yaml
The flag `--no-ccache` was put in the wrong place and broke the daily coverage build, now it should work again!
=> Fix daily coverage build test

src/dbms/inmemory/storage_helper.hpp, src/query/interpreter.cpp, src/storage/v2/durability/snapshot.cpp, src/storage/v2/durability/snapshot.hpp, src/storage/v2/inmemory/storage.cpp, src/storage/v2/inmemory/storage.hpp, tests/e2e/durability/snapshot_recovery.py, tests/unit/CMakeLists.txt, tests/unit/storage_v2_create_snapshot.cpp, tests/unit/storage_v2_durability_inmemory.cpp
`CREATE SNAPSHOT` now returns the path of the created snapshot.
User query also cannot fail because there is no change (snapshot is forced)
=> Return snapshot path

src/coordination/data_instance_management_server_handlers.cpp, src/query/interpreter.cpp, src/query/replication_query_handler.hpp, src/replication/include/replication/state.hpp, src/replication/include/replication/status.hpp, src/replication/state.cpp, src/replication/status.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/replication_handler/replication_handler.cpp, tests/unit/replication_persistence_helper.cpp, tests/unit/storage_v2_replication.cpp
The goal of this PR is to simplify the code by removing unneeded optionalness.
=> Remove optional UUID from replica's role

src/coordination/coordinator_instance.cpp, src/dbms/inmemory/replication_handlers.cpp, src/replication/include/replication/state.hpp, src/replication_handler/replication_handler.cpp, src/storage/v2/durability/durability.cpp, src/storage/v2/replication/replication_client.cpp, src/storage/v2/replication/rpc.hpp
When recovering from snapshot, there is no need to modify epoch history with the epoch from snapshot since this will modify history's state compared to the moment when snapshot is being taken.
There was a bug in one of the previous PR's in which epochs and ldt from wal would update the state even if there was no change made in that WAL (all txns were aborted).
=> Improve handling of epochs during data recovery

.github/actions/docker-login/action.yml, .github/workflows/benchmark_on_pokec_large.yaml, .github/workflows/build_rc.yml, .github/workflows/daily_benchmark.yaml, .github/workflows/diff_community.yaml, .github/workflows/diff_coverage.yaml, .github/workflows/diff_debug.yaml, .github/workflows/diff_jepsen.yaml, .github/workflows/diff_malloc.yaml, .github/workflows/diff_release.yaml, .github/workflows/release_mgbench_client.yaml, .github/workflows/reusable_package.yaml, .github/workflows/reusable_release_tests.yaml, .github/workflows/reusable_stress_jepsen.yaml, src/py/py.hpp
Fixes for the `3.5.0` release of Memgraph:
- Added action to login to Dockerhub in workflows with a retry mechanism
- Some minor fixes to the build RC workflow
- `Py_Is` macro for builds which use Python `<3.10` (CentOS 9 and Debian 11, currently)
=> Release 3.5 fixes

.github/workflows/reusable_package.yaml, release/package/mgbuild.sh
Added `--disable-testing` to the `mgbuild.sh` script to use in the packaging workflows. This should reduce the workflow time a little by not building the tests.
=> Add option to build without tests for packaging

release/docker/v6_deb.dockerfile, release/docker/v6_deb_relwithdebinfo.dockerfile
The PR adds python3.12-venv inside Memgraph's build image. This makes it easier to create environments when using Memgraph as part of the K8s cluster.
=> Add python3.12-venv inside Memgraph's build image

src/coordination/coordinator_instance.cpp, src/coordination/coordinator_rpc.cpp, src/coordination/data_instance_management_server_handlers.cpp, src/coordination/include/coordination/coordinator_rpc.hpp, src/coordination/include/coordination/replication_instance_client.hpp, src/query/replication_query_handler.hpp, src/replication/include/replication/state.hpp, src/replication/state.cpp, src/replication_handler/include/replication_handler/replication_handler.hpp, src/replication_handler/replication_handler.cpp
Instead of waiting for swap main uuid, old main can start listening new main faster with a single RPC call.
=> feat: Speed up demote process upon failover

src/query/plan/preprocess.cpp, src/query/plan/rewrite/index_lookup.hpp, tests/gql_behave/tests/memgraph_V1/features/match.feature
This fixes an issue where OR label filter expressions would produce incorrect results when we have both `MATCH (:L1)` and `WHERE (:L2 OR :L3)` in the same query. For example:
```cypher
CREATE INDEX ON :A;
CREATE INDEX ON :B;
CREATE INDEX ON :C
CREATE (:A:B);
CREATE (:A:C);
CREATE (:A)
MATCH (n:A)
WHERE (n:B OR n:C)
RETURN n;
```
Would return:
```
+--------+
| n      |
+--------+
| (:A:C) |
| (:A:B) |
| (:A)   |
+--------+
```
instead of the expected:
```
+--------+
| n      |
+--------+
| (:A:C) |
| (:A:B) |
+--------+
```
Also adds some additional tests for edges cases with OR expressions.
Closes #3236
=> Support `OR` label filters alongside label `MATCH`

src/planner/CMakeLists.txt
Fix packaging build which tries to include unit tests within `src/` while `MG_ENABLE_TESTING=OFF`
=> Fix packaging-only build

.github/workflows/reusable_stress_jepsen.yaml, .github/workflows/stress_jepsen_ha.yaml
Remove requirement for Jepsen jobs to run on machines with the `JepsenControl` tag, allowing the Jepsen stress tests to run on smaller CI machines. For future reference: MT jobs used about 4.5 GiB ram, and non-MT used around 3.2 GiB.
Additionally, modified concurrency to allow runs with different input parameters on the same git ref.
=> Allow Jepsen stress tests to run on machines with less RAM

src/dbms/inmemory/replication_handlers.cpp
When new epoch is detected, the replica should finalise its WAL file and start creating a new one. That wasn't the case before, we first updated the epoch and then compared them so the check was always true.
=> fix: Finalize WAL before updating epoch on replica

tests/drivers/run.sh, tests/drivers/run_cluster.sh, tests/e2e/runner.py, tests/util.sh
Disable tests using `npm` temporarily due to security risk.
=> Disable tests using npm

src/query/interpret/awesome_memgraph_functions.cpp
absl has some issue in the initializer with lambda.
=> fix: Change absl::flat_hash_map -> std::map

src/storage/v2/async_indexer.cpp, src/storage/v2/inmemory/storage.cpp, tests/e2e/index_auto_creation/index_auto_creation.py
1. Async indexer would sometimes block Memgraph from shutting down due to a concurrency bug. 
2. `DROP ALL INDEXES` now empties the async indexer queue to lessen the chance of a possible race condition happening when an index gets dropped and enqueued at the same time which would cause test flakyness.
=> Fix Memgraph failing to shutdown due to async indexer

query_modules/convert.c, tests/query_modules/to_tree_test/test_merge_duplicate_nodes/input.cyp, tests/query_modules/to_tree_test/test_merge_duplicate_nodes/test.yml, tests/query_modules/to_tree_test/test_multi_label_distinct/input.cyp, tests/query_modules/to_tree_test/test_multi_label_distinct/test.yml, tests/query_modules/to_tree_test/test_multiple_label_property_filtering/input.cyp, tests/query_modules/to_tree_test/test_multiple_label_property_filtering/test.yml
Fixes node identification when nodes have more than one label. Previously, the identity function wasn't working for these nodes, meaning that they would appear multiple times in the tree output if they were also duplicated in the input paths.
We now use a hash-based comparison on all labels, and nodes are deduplicated.
=> Remove duplicate nodes in `to_tree` result

tools/docker_cleanup.sh
The script to clean up Docker after each CI run is cleaning up the newest `mgdeps-cache` image, this PR should stop that happening.
=> Stop Docker cleanup script removing new deps container

src/coordination/coordinator_instance.cpp, src/coordination/coordinator_state.cpp, src/coordination/data_instance_management_server_handlers.cpp, src/coordination/include/coordination/coordinator_instance.hpp, src/coordination/include/coordination/coordinator_state.hpp, src/memgraph.cpp, src/replication/include/replication/state.hpp, src/replication/state.cpp, src/telemetry/telemetry.cpp, src/telemetry/telemetry.hpp, src/utils/event_map.cpp, src/utils/event_map.hpp, src/utils/system_info.cpp, src/utils/system_info.hpp, tests/integration/telemetry/client.cpp, tests/unit/CMakeLists.txt, tests/unit/event_map.cpp, tests/unit/storage_v2_replication.cpp
The PR adds a support for exposing replication and coordination data to the telemetry server:
- the number of strict_sync, sync and asynchronous replicas
- coordinator's configuration: cluster size and its runtime configuration options
Problems with detecting Docker env:
- https://github.com/moby/moby/issues/47420
=> feat: Add HA telemetry collectors

.github/workflows/diff_release.yaml, release/package/amd-builders-v5.yml, release/package/amd-builders-v6.yml, release/package/arm-builders-v5.yml, release/package/arm-builders-v6.yml
The mgbuild containers currently use the old hosts for `mgdeps-cache` and `bench-graph-api`. This updates the docker compose scripts to use the new hosts.
=> Move container hosts

.github/workflows/reusable_package.yaml
The addition of the external PR diff/packaging workflows had the unintended effect of breaking the package naming for release candidate builds that are started from `master` (i.e.  without creating the `release/x.y.z` branch beforehand). This should fix that.
=> Do not rename packages if RC workflow runs from master
